### PR TITLE
[PWGCF] initial commit of tutorial code for event plane

### PR DESCRIPTION
**Pull request by jikim1290**
initial commit of tutorial code for event plane

### CODE REVIEW

**Review by victor-gonzalez — APPROVED** [review]
Be aware that for people following the hands-on they should have updated their local O2Physics with this PR in the latest tag before the session starts

You have to announce that

**Comment by jikim1290** [comment]
@victor-gonzalez Yes Indeed, can I use mattermost channel for that?

**Comment by victor-gonzalez** [comment]
I would suggest you to contact Oton and/or Qiye and David

**Comment by jikim1290** [comment]
please merge this

**Pull request merged**
