### PR TITLE
[Common] RecoDecay::constrainAngle: Support harmonics

### PR DESCRIPTION
**Pull request by vkucera**
Add support for the customisation of the angle periodicity.
Used in flow analyses for harmonics.

### CODE REVIEW

**Comment by vkucera** [comment]
Linter and compilation warnings to be fixed in a separate PR.

**Comment by vkucera** [comment]
FYI: @stefanopolitano @mhemmer-cern @fgrosa @fcatalan92

**Comment by mhemmer-cern** [comment]
Thanks a lot @vkucera !

**Comment by vkucera** [comment]
@ddobrigk Can you please have a look and approve if all looks sane to you?

**Review by ddobrigk — APPROVED** [review]

**Pull request merged**
