### PR TITLE
Event filtering: add QA histos

### PR DESCRIPTION
**Pull request by fgrosa**

### CODE REVIEW

**Comment by mpuccio** [comment]
Hi @TimoWilken , @fgrosa is in the codeowners but alibuild does not approve for him. Could you please have a look why?

**Comment by TimoWilken** [comment]
Hi @mpuccio, the auto-approval only happens when @fgrosa clicks the "enable auto-merge (squash)" button.

**Comment by fgrosa** [comment]
> Hi @mpuccio, the auto-approval only happens when @fgrosa clicks the "enable auto-merge (squash)" button.

Hi @TimoWilken, thanks for the hint! However I do not have the button, this is what I see 
grafik
Does it appear after the test turn green?

**Comment by TimoWilken** [comment]
@fgrosa looks like you didn't have write access to the repo. I've added you -- when you accept the "invite" from GitHub (you should have received an email), the button should appear.

**Comment by fgrosa** [comment]
> @fgrosa looks like you didn't have write access to the repo. I've added you -- when you accept the "invite" from GitHub (you should have received an email), the button should appear.

I accepted it and now the button appeared, thanks a lot!

**Review by vkucera — APPROVED** [review]

**Pull request merged**
