### PR TITLE
Common/PWGHF: fix smearing of sigmaYZ cov. matrix term in TrackTuner, and add protection.

### PR DESCRIPTION
**Pull request by mfaggin**
Fix in the smearing of out-of-diagonal term `sigmaZY` of the track cov. matrix in the `trackTuner`.
Error found running on derived data on HF trigger MC (`LHC22b1a`, `LHC22b1b`) on Hyperloop and enabling the `candidateCreator3Prong`.

In few cases the code was throwing the `invalid track covariance` error, triggered by [this](https://github.com/AliceO2Group/AliceO2/blob/66de30958153cd7badf522150e8554f9fcf975ff/Common/DCAFitter/include/DCAFitter/DCAFitterN.h#L38-L54), i.e. when the `detXY` is negative.
By fixing the `sigmaZY`, and adding a protection that restores the original `sigmaY2`, `sigmaZ2` and `sigmaZY` values in case of `detYZ = sigmaY2 * sigmaZ2 - sigmaZY * sigmaZY < 0` after the smearing, the `candidateCreator3Prong` worked with both `updateTrackCovMat=1` and `updatePulls=1`. The `hQA` histogram has been added to monitor how frequently these pathologic cases happen, but now they seem very rare (see below).

Tagging @phymanshu and @arossi81 , as well as @fgrosa and @DelloStritto for their knowledge.

photo_2024-02-28_18-34-46

### CODE REVIEW

**Comment by arossi81** [comment]
Hi @mfaggin ,
your changes to the math look ok to me, and necessary. After the bug fix, are still there pathological cases? There should not.

**Comment by mfaggin** [comment]
> Hi @mfaggin , your changes to the math look ok to me, and necessary. After the bug fix, are still there pathological cases? There should not.

Ciao @arossi81 , you can see the situation after the bug fix in the screenshot attached to this PR. 
Dumping stuff at screen, the product `sigmaY2 * sigmaZ2 - sigmaZY * sigmaZY ` goes negative with small values of the order of $10^-14$, being the elements `sigmaY2`, `sigmaZ2` and `sigmaZY` of the order of `10^-7`.
According to my test on 1 file, there are still a (very) few pathological cases (9 out of 5x10^7) which are anyway "cured" in the sense that for them I recover the original values of the cov. matrix elements. You can see that they are very few, I would not worry about them at the moment.
Anyway, now we should be on the safe side, and with the modified `trackTunedTracks` histogram we can monitor how many times these pathological cases happen

**Comment by arossi81** [comment]
Ciao @mfaggin ,
that's strange, mathematically it's impossible (the determinant is multiplied by a positive factor), so  I guess this could be due just to numerical issues emerging when e.g. the original determinant is already very close to zero. While debugging did you check the original determinant values? 
 I am wondering whether the best thing would be to not track-tuned at all these tracks, but unless they pop up at very high momentum (where the total counts could be a small fraction of 5x10^7, so 9 could be at % level), it is irrelevant.

**Comment by mfaggin** [comment]
> Ciao @mfaggin , that's strange, mathematically it's impossible (the determinant is multiplied by a positive factor), so I guess this could be due just to numerical issues emerging when e.g. the original determinant is already very close to zero. While debugging did you check the original determinant values? I am wondering whether the best thing would be to not track-tuned at all these tracks, but unless they pop up at very high momentum (where the total counts could be a small fraction of 5x10^7, so 9 could be at % level), it is irrelevant.

hi @arossi81 as I said this might indeed be correlated with the issue fixed in [here]{https://github.com/AliceO2Group/O2Physics/pull/4681}, not yet solved when the HF derived data for MC were produced.
Anyway: let me try a few more tests, I'll keep you updated here.

**Comment by mfaggin** [comment]
Hi @arossi81 , here I am with come further checks. In the last commit ([this](https://github.com/AliceO2Group/O2Physics/pull/4917/commits/bc9d60204d7d0e0685cedf9366b559fb7ad6fa2c)):

- I added the possibility to count how many of the pathological cases were such even before the `trackTuner`
- I restore also Y and Z parameters (not only cov. matrix elements) for these pathological cases

You can find below the result of my further test. As you can see:

1. all pathological cases are such already before the trackTuner is applied (i.e. also the original `detYZorig` is negative). The first thing to check is whether things will change when we'll redo HF derived data for this MC. Anyway, the fixed trackTuner does not introduce any bias apparently;
image

2. I do not know if it is by chance or not, but all the pathological cases seem to come from intermediate or high pt tracks, see the cout below. Anyway, the caveat of the previous bullet still remains.
```
89104472:[3007862:track-propagation]: >>> ILL DEFINED COV. MATRIX <<<
89104473-[3007862:track-propagation]: [10:11:02][INFO]     sigmaY2 = 4.23399e-07
89104474-[3007862:track-propagation]: [10:11:02][INFO]     sigmaZY = 4.99928e-07
89104475-[3007862:track-propagation]: [10:11:02][INFO]     sigmaZ2 = 4.89578e-07
89104476-[3007862:track-propagation]: [10:11:02][INFO]     The product (sigmaY2*sigmaZ2 - sigmaZY*sigmaZY) = -4.26406e-14 is negative. Restoring the original sigmaY2, sigmaZY, sigmaZ2 cov. matrix elements:
89104477-[3007862:track-propagation]: [10:11:02][INFO]     sigmaY2orig = 3.70863e-07
89104478-[3007862:track-propagation]: [10:11:02][INFO]     sigmaZYorig = 4.34311e-07
89104479-[3007862:track-propagation]: [10:11:02][INFO]     sigmaZ2orig = 4.21839e-07
89104480-[3007862:track-propagation]: [10:11:02][INFO]     Original product (sigmaY2orig*sigmaZ2orig - sigmaZYorig*sigmaZYorgi) = -3.21819e-14
89104481-[3007862:track-propagation]: [10:11:02][INFO]     ===> track pt = 12.7234
--
89876731:[3007862:track-propagation]: >>> ILL DEFINED COV. MATRIX <<<
89876732-[3007862:track-propagation]: [10:11:07][INFO]     sigmaY2 = 6.20006e-07
89876733-[3007862:track-propagation]: [10:11:07][INFO]     sigmaZY = -7.47886e-07
89876734-[3007862:track-propagation]: [10:11:07][INFO]     sigmaZ2 = 8.481e-07
89876735-[3007862:track-propagation]: [10:11:07][INFO]     The product (sigmaY2*sigmaZ2 - sigmaZY*sigmaZY) = -3.35071e-14 is negative. Restoring the original sigmaY2, sigmaZY, sigmaZ2 cov. matrix elements:
89876736-[3007862:track-propagation]: [10:11:07][INFO]     sigmaY2orig = 5.82275e-07
89876737-[3007862:track-propagation]: [10:11:07][INFO]     sigmaZYorig = -7.15336e-07
89876738-[3007862:track-propagation]: [10:11:07][INFO]     sigmaZ2orig = 8.2616e-07
89876739-[3007862:track-propagation]: [10:11:07][INFO]     Original product (sigmaY2orig*sigmaZ2orig - sigmaZYorig*sigmaZYorgi) = -3.06539e-14
89876740-[3007862:track-propagation]: [10:11:07][INFO]     ===> track pt = 6.2479
--
121017864:[3007862:track-propagation]: >>> ILL DEFINED COV. MATRIX <<<
121017865-[3007862:track-propagation]: [10:14:49][INFO]     sigmaY2 = 7.64214e-09
121017866-[3007862:track-propagation]: [10:14:49][INFO]     sigmaZY = -6.46807e-08
121017867-[3007862:track-propagation]: [10:14:49][INFO]     sigmaZ2 = 1.42141e-07
121017868-[3007862:track-propagation]: [10:14:49][INFO]     The product (sigmaY2*sigmaZ2 - sigmaZY*sigmaZY) = -3.09733e-15 is negative. Restoring the original sigmaY2, sigmaZY, sigmaZ2 cov. matrix elements:
121017869-[3007862:track-propagation]: [10:14:49][INFO]     sigmaY2orig = 6.65459e-09
121017870-[3007862:track-propagation]: [10:14:49][INFO]     sigmaZYorig = -6.18344e-08
121017871-[3007862:track-propagation]: [10:14:49][INFO]     sigmaZ2orig = 1.49185e-07
121017872-[3007862:track-propagation]: [10:14:49][INFO]     Original product (sigmaY2orig*sigmaZ2orig - sigmaZYorig*sigmaZYorgi) = -2.83073e-15
121017873-[3007862:track-propagation]: [10:14:49][INFO]     ===> track pt = 118.07
--
150120576:[3007862:track-propagation]: >>> ILL DEFINED COV. MATRIX <<<
150120577-[3007862:track-propagation]: [10:18:42][INFO]     sigmaY2 = 4.45111e-08
150120578-[3007862:track-propagation]: [10:18:42][INFO]     sigmaZY = -1.90624e-07
150120579-[3007862:track-propagation]: [10:18:42][INFO]     sigmaZ2 = 1.72377e-07
150120580-[3007862:track-propagation]: [10:18:42][INFO]     The product (sigmaY2*sigmaZ2 - sigmaZY*sigmaZY) = -2.86649e-14 is negative. Restoring the original sigmaY2, sigmaZY, sigmaZ2 cov. matrix elements:
150120581-[3007862:track-propagation]: [10:18:42][INFO]     sigmaY2orig = 4.13849e-08
150120582-[3007862:track-propagation]: [10:18:42][INFO]     sigmaZYorig = -1.83358e-07
150120583-[3007862:track-propagation]: [10:18:42][INFO]     sigmaZ2orig = 1.71532e-07
150120584-[3007862:track-propagation]: [10:18:42][INFO]     Original product (sigmaY2orig*sigmaZ2orig - sigmaZYorig*sigmaZYorgi) = -2.65211e-14
150120585-[3007862:track-propagation]: [10:18:42][INFO]     ===> track pt = 11.0343
--
157383491:[3007862:track-propagation]: >>> ILL DEFINED COV. MATRIX <<<
157383492-[3007862:track-propagation]: [10:19:33][INFO]     sigmaY2 = 5.74023e-05
157383493-[3007862:track-propagation]: [10:19:33][INFO]     sigmaZY = -2.07802e-05
157383494-[3007862:track-propagation]: [10:19:33][INFO]     sigmaZ2 = 6.92307e-06
157383495-[3007862:track-propagation]: [10:19:33][INFO]     The product (sigmaY2*sigmaZ2 - sigmaZY*sigmaZY) = -3.44158e-11 is negative. Restoring the original sigmaY2, sigmaZY, sigmaZ2 cov. matrix elements:
157383496-[3007862:track-propagation]: [10:19:33][INFO]     sigmaY2orig = 5.0598e-05
157383497-[3007862:track-propagation]: [10:19:33][INFO]     sigmaZYorig = -1.88177e-05
157383498-[3007862:track-propagation]: [10:19:33][INFO]     sigmaZ2orig = 6.44068e-06
157383499-[3007862:track-propagation]: [10:19:33][INFO]     Original product (sigmaY2orig*sigmaZ2orig - sigmaZYorig*sigmaZYorgi) = -2.82224e-11
157383500-[3007862:track-propagation]: [10:19:33][INFO]     ===> track pt = 13.6015
--
172236676:[3007862:track-propagation]: >>> ILL DEFINED COV. MATRIX <<<
172236677-[3007862:track-propagation]: [10:21:27][INFO]     sigmaY2 = 6.05531e-05
172236678-[3007862:track-propagation]: [10:21:27][INFO]     sigmaZY = -1.2017e-05
172236679-[3007862:track-propagation]: [10:21:27][INFO]     sigmaZ2 = 2.31345e-06
172236680-[3007862:track-propagation]: [10:21:27][INFO]     The product (sigmaY2*sigmaZ2 - sigmaZY*sigmaZY) = -4.32215e-12 is negative. Restoring the original sigmaY2, sigmaZY, sigmaZ2 cov. matrix elements:
172236681-[3007862:track-propagation]: [10:21:27][INFO]     sigmaY2orig = 5.64694e-05
172236682-[3007862:track-propagation]: [10:21:27][INFO]     sigmaZYorig = -1.11973e-05
172236683-[3007862:track-propagation]: [10:21:27][INFO]     sigmaZ2orig = 2.15384e-06
172236684-[3007862:track-propagation]: [10:21:27][INFO]     Original product (sigmaY2orig*sigmaZ2orig - sigmaZYorig*sigmaZYorgi) = -3.75258e-12
172236685-[3007862:track-propagation]: [10:21:27][INFO]     ===> track pt = 5.99359
--
197436676:[3007862:track-propagation]: >>> ILL DEFINED COV. MATRIX <<<
197436677-[3007862:track-propagation]: [10:24:44][INFO]     sigmaY2 = 4.73564e-07
197436678-[3007862:track-propagation]: [10:24:44][INFO]     sigmaZY = 6.098e-07
197436679-[3007862:track-propagation]: [10:24:44][INFO]     sigmaZ2 = 5.79593e-07
197436680-[3007862:track-propagation]: [10:24:44][INFO]     The product (sigmaY2*sigmaZ2 - sigmaZY*sigmaZY) = -9.73822e-14 is negative. Restoring the original sigmaY2, sigmaZY, sigmaZ2 cov. matrix elements:
197436681-[3007862:track-propagation]: [10:24:44][INFO]     sigmaY2orig = 4.12783e-07
197436682-[3007862:track-propagation]: [10:24:44][INFO]     sigmaZYorig = 5.87403e-07
197436683-[3007862:track-propagation]: [10:24:44][INFO]     sigmaZ2orig = 6.16988e-07
197436684-[3007862:track-propagation]: [10:24:44][INFO]     Original product (sigmaY2orig*sigmaZ2orig - sigmaZYorig*sigmaZYorgi) = -9.03601e-14
197436685-[3007862:track-propagation]: [10:24:44][INFO]     ===> track pt = 9.51281
--
276131938:[3007862:track-propagation]: >>> ILL DEFINED COV. MATRIX <<<
276131939-[3007862:track-propagation]: [10:34:40][INFO]     sigmaY2 = 1.08611e-08
276131940-[3007862:track-propagation]: [10:34:40][INFO]     sigmaZY = -2.80366e-07
276131941-[3007862:track-propagation]: [10:34:40][INFO]     sigmaZ2 = 3.3592e-07
276131942-[3007862:track-propagation]: [10:34:40][INFO]     The product (sigmaY2*sigmaZ2 - sigmaZY*sigmaZY) = -7.49565e-14 is negative. Restoring the original sigmaY2, sigmaZY, sigmaZ2 cov. matrix elements:
276131943-[3007862:track-propagation]: [10:34:40][INFO]     sigmaY2orig = 8.63391e-09
276131944-[3007862:track-propagation]: [10:34:40][INFO]     sigmaZYorig = -2.76869e-07
276131945-[3007862:track-propagation]: [10:34:40][INFO]     sigmaZ2orig = 4.12099e-07
276131946-[3007862:track-propagation]: [10:34:40][INFO]     Original product (sigmaY2orig*sigmaZ2orig - sigmaZYorig*sigmaZYorgi) = -7.30986e-14
276131947-[3007862:track-propagation]: [10:34:40][INFO]     ===> track pt = 7.70785
--
283834593:[3007862:track-propagation]: >>> ILL DEFINED COV. MATRIX <<<
283834594-[3007862:track-propagation]: [10:35:40][INFO]     sigmaY2 = 4.55312e-07
283834595-[3007862:track-propagation]: [10:35:40][INFO]     sigmaZY = 6.40225e-07
283834596-[3007862:track-propagation]: [10:35:40][INFO]     sigmaZ2 = 6.00409e-07
283834597-[3007862:track-propagation]: [10:35:40][INFO]     The product (sigmaY2*sigmaZ2 - sigmaZY*sigmaZY) = -1.36515e-13 is negative. Restoring the original sigmaY2, sigmaZY, sigmaZ2 cov. matrix elements:
283834598-[3007862:track-propagation]: [10:35:40][INFO]     sigmaY2orig = 4.45277e-07
283834599-[3007862:track-propagation]: [10:35:40][INFO]     sigmaZYorig = 6.23343e-07
283834600-[3007862:track-propagation]: [10:35:40][INFO]     sigmaZ2orig = 5.81987e-07
283834601-[3007862:track-propagation]: [10:35:40][INFO]     Original product (sigmaY2orig*sigmaZ2orig - sigmaZYorig*sigmaZYorgi) = -1.2941e-13
283834602-[3007862:track-propagation]: [10:35:40][INFO]     ===> track pt = 11.8645

```

From my point of view everything looks ready ready to be merged @jgrosseo @ddobrigk

**Comment by arossi81** [comment]
Hi @mfaggin ,
thanks a lot! Indeed, very good that, as it should mathematically be (up to issue related to numerical precision), it's not the track tuner to change the determinant sign.  Now, the fact that you see these pathological cases only at high pt it's a bit more worrisome because, as I was saying before, they might not be so irrelevant. Anyhow, they are still few and I agree with you that we need to see what happens when the derived data re redone before being concerned.

**Comment by mfaggin** [comment]
> Hi @mfaggin , thanks a lot! Indeed, very good that, as it should mathematically be (up to issue related to numerical precision), it's not the track tuner to change the determinant sign. Now, the fact that you see these pathological cases only at high pt it's a bit more worrisome because, as I was saying before, they might not be so irrelevant. Anyhow, they are still few and I agree with you that we need to see what happens when the derived data re redone before being concerned.

thanks @arossi81 . Now everything is ready @jgrosseo @ddobrigk

**Comment by mfaggin** [comment]
informing also @fcolamar and @fcatalan92 for their interest

**Pull request merged**
