### PR TITLE
PWGCF: Added flags for Full PID IdBfFilter

### PR DESCRIPTION
**Pull request by bghanley1995**
Fixed an error on run where code was looking for Full PID from TPC and normal from TOF

### CODE REVIEW

**Comment by victor-gonzalez** [comment]
> Fixed an error on run where code was looking for Full PID from TPC and normal from TOF

Just to clarify, this description is misleading
The PR introduces Full PID in both TPC and TOF. Previously there were normal PID for both TPC and TOF
But that is not an error. With Full PID you just get better precision

**Review by victor-gonzalez — CHANGES_REQUESTED** [review]
This code will not run unless the line
```
    if constexpr (framework::has_type_v<aod::pidtpc::TPCNSigmaPi, typename TrackObject::all_columns>) {
```
is also modified accordingly

Reminder: PR code should have been tested locally before submission

**Comment by bghanley1995** [comment]
Hello Victor, I am confused. I did run locally and I don't seen any problem. I obviously trust your expertise, but I did not get any errors and saw results I expected to see when running the code.

**Comment by bghanley1995** [comment]
Oh I see. Is it because with non-full TPC PID the call is `aod::pidtpc_tiny::TPCNSigmaPi`? I see my oversight in testing.

**Comment by victor-gonzalez** [comment]
You should change the configuration for run it with Full PID
Also you have to use the Full TOF and Full TPC tasks in your workflow
In that way you will fully test your changes

**Review by victor-gonzalez — APPROVED** [review]

**Pull request merged**
