### PR TITLE
Update qaEfficiency.cxx

### PR DESCRIPTION
**Pull request by upasanasharma31**
To calculate the efficiency of the particle from the mother lambda and Xi

### CODE REVIEW

**Review by mfaggin — CHANGES_REQUESTED** [review]
2 big questions from my side:

1. you try to tag particles from Lambda and Xi using only the positive PDG code, i.e. ignoring anti-particles. Is it what you want?
2. even when you tag a Lambda or Xi daughter, it looks to me that you fill always the "inclusive" histograms, i.e. you do not separate the histograms for these particles. I'd do, in order not to touch the inclusive analysis

**Comment by njacazio** [comment]
Hi @upasanasharma31 I revised the code, please check it and let me know if it is unclear

**Comment by upasanasharma31** [comment]
Hi @njacazio , I checked it. Now it is clear to me, what i was doing wrong.  Here, if I'm not wrong, it ensures that `motherIsAccepted` is set to true if any of the mother particles' PDG codes match any PDG code specified in `mothersPDGs`. Otherwise, it remains false.  The `motherIsAccepted` is used to determine whether the mothers of the particle meet the specified criteria (i.e., if their PDG codes match any of the PDG codes in `mothersPDGs`). Thank you

**Comment by upasanasharma31** [comment]
Hi @mfaggin ,
1. Sorry, for my mistake. Yes,  it's crucial to consider both the positive and negative PDG codes (including both particles and antiparticles). Lambda and Xi particles can be either positively or negatively charged, so excluding antiparticles might lead to missing important events.
2. Yes, you're right. Sorry, for the misunderstanding from my side. Either I've to separate the histograms for Lambda and Xi particles while avoiding changes to the inclusive analysis,or checking the motherPDG of the particles.This way, we maintain the existing inclusive histograms while adding new ones dedicated to Lambda and Xi particles. Thank you for the useful suggestions.

**Review by mfaggin — CHANGES_REQUESTED** [review]
I'm still wondering if you really want `if(mother.pdgCode() == pdgToCheck)` of `if(std::abs(mother.pdgCode()) == pdgToCheck)`

**Comment by upasanasharma31** [comment]
Hello @mfaggin, I want `(mother.pdgCode() == pdgToCheck) ` treats the PDG codes as signed integers,  negative PDG codes (representing antiparticles) distinct from their corresponding positive PDG particles, not absolute one.
Thanks

**Review by mfaggin — APPROVED** [review]
ok, fine for me then

**Review by njacazio — APPROVED** [review]

**Review by njacazio — APPROVED** [review]

**Pull request merged**
