### PR TITLE
replaced abs->TMath::Abs + configurable DCA cuts

### PR DESCRIPTION
**Pull request by alcaliva**

### CODE REVIEW

**Review by maciacco — APPROVED** [review]

**Comment by vkucera** [comment]
@alcaliva , there is no benefit in replacing `std::abs` with `TMath::Abs`. You just increase dependency of your code on ROOT for no reason.

**Comment by vkucera** [comment]
@maciacco @alcaliva The commit title is too vague. It can be referring to any file in O2Physics. Please add information about the location of the changes in the title of the commit. Please note that changing the title of the PR is not enough.

**Comment by alcaliva** [comment]
@vkucera I don't understand your comment. Should I specify the name of the task in the comment field to avoid a reference to "any file in O2Physics"? How can I specify the location of the changes? I changed several lines ...

**Comment by vkucera** [comment]
First of all, please add a "PWGLF" prefix in your commit title. Second, adding e.g. "Nuclei in jets" in the commit title is already specific enough to give clear information about the concerned analysis or file.

**Pull request merged**
