### PR TITLE
[TOF] switch based on coll system

### PR DESCRIPTION
**Pull request by njacazio**
Reopening https://github.com/AliceO2Group/O2Physics/pull/7559

### CODE REVIEW

**Comment by njacazio** [comment]
@noferini

**Comment by njacazio** [comment]
@ddobrigk based on the GRP info I fetch if this is pp or Pb-Pb, this is a wider use case than the TOF. Could you please check if this is ok for e.g. the multiplicity case?

**Review by ddobrigk — APPROVED** [review]
approving, does not act in main core service but in alternate dev task AFAIK

**Comment by ddobrigk** [comment]
and thank you @njacazio !

**Pull request merged**
