### PR TITLE
[PWGCF] FemtoUniverse cascade task -- added process functions for cascade - cascade correlation

### PR DESCRIPTION
**Pull request by Eloviyo**
- added process functions for cascade - cascade pair same and mixed events
- fixed typos and added comments

### CODE REVIEW

**Review by saganatt — DISMISSED** [review]
Approving your changes.

Please note O2 linter warnings, they need to be fixed soon.

**Comment by saganatt** [comment]
Thank you very much for the fixes - I actually didn't expect them in the same PR. Sorry for not being clear!

What is the issue with struct / configurable names, where you put the comments for the linter?

**Comment by Eloviyo** [comment]
> Thank you very much for the fixes - I actually didn't expect them in the same PR. Sorry for not being clear!
> 
> What is the issue with struct / configurable names, where you put the comments for the linter?

You are most welcome. I thought the PR will not get merged without the O2 linter fixes. I kept the configurable names in

**Review by saganatt — APPROVED** [review]

**Comment by vkucera** [comment]
@Eloviyo Do not silence warnings without a valid reason. They do not prevent the merging of your PR.

**Comment by vkucera** [comment]
@Eloviyo The `using-directive` issues is still there and still silenced. It should be fixed.

**Comment by vkucera** [comment]
@Eloviyo @saganatt The `using-directive` issues is still there and still silenced. It should be fixed.

**Pull request merged**
