### PR TITLE
fix: znc input number and name of mb more opened

### PR DESCRIPTION
**Pull request by lietava**

### CODE REVIEW

**Comment by mpuccio** [comment]
@lietava Thanks a lot!

**Comment by ddobrigk** [comment]
@mpuccio @lietava guys, shall I approve or should I wait (for e.g. the O2 PR)? Just let me know. Have a nice weekend?

**Comment by mpuccio** [comment]
Ho @ddobrigk , I did not want to disturb in the weekend but yes, let’s merge, thanks a lot! The o2 PR will require some massaging

**Review by ddobrigk — APPROVED** [review]

**Comment by lietava** [comment]
@ddobrigk thanks.

**Pull request merged**
