### PR TITLE
Bitmask for alias and selection columns

### PR DESCRIPTION
**Pull request by ekryshen**

### CODE REVIEW

**Comment by ekryshen** [comment]
It seems CI needs these changes in O2 to compile:
https://github.com/AliceO2Group/AliceO2/commit/d540e181b23432bb4b584fe516589fcc16bc7469

Waiting for tomorrow's O2 tag

**Review by mhemmer-cern — APPROVED** [review]
Looks good from PWGEM side :)
Thanks for the work!

**Review by aalkin — APPROVED** [review]

**Comment by ekryshen** [comment]
This PR is still waiting for 40 pending reviewers. @pbuehler @strogolo @ginnocen @vkucera @fcolamar @jgrosseo @njacazio could you have a look?

**Review by mfaggin — APPROVED** [review]
I approve the changes for the DPG folder

**Review by njacazio — APPROVED** [review]

**Review by ddobrigk — APPROVED** [review]
Approved for `Common`. Super thanks, @ekryshen !

**Comment by ddobrigk** [comment]
Hi @ktf @pzhristov this looks fine but the number of approvals required is enormous, it will be very hard to converge... It would be good, if you agree, if we could use your superpowers to merge :-) thanks!!!

**Review by iarsene — APPROVED** [review]

**Comment by ktf** [comment]
Merged. Can you please either fix the megalinter or remove it?

**Comment by ekryshen** [comment]
@ktf Thanks for merging. I didn't fix megalinter warnings since they were related to user tasks and were not critical. I would let users to fix them at the next occasion.

**Comment by ktf** [comment]
Yes, I appreciate that. Nevertheless we should not have a check which becomes red depending on the files which are touched, because that prevents the automatic merging. If you want to have the MegaLinter, that's fine, but the starting state should be always "green", not "sometimes red".

**Comment by vkucera** [comment]
@ktf this is due to two things:
- When the MegaLinter check was added, there were already too many files in the repo which did not follow the O2 coding conventions.
- Since the MegaLinter check is not required for merging, it is the code owners' responsibility to merge PRs only when they pass all the checks, and unfortunately sometimes they merge them regardless, which then makes the check fail again whenever the file is touched next time.

**Pull request merged**
