### PR TITLE
PWGHF: Add centrality (FT0C as default) in Lc task

### PR DESCRIPTION
**Pull request by zhangbiao-phy**
To make the centrality differential analysis more convenient for offline process

### CODE REVIEW

**Comment by zhangbiao-phy** [comment]
Hi @vkucera, I would like to add the centrality information in the ThnSparse of the Lc task. Any comments and suggestions are welcome! Thanks for your review!

**Review by fgrosa — DISMISSED** [review]
@zhangbiao-phy looks good to me! Thanks for addressing our comment, it will improve the usage of resources on hyperloop a lot. Could you please just add a process function that does not consume any centrality table, so that we do not force to have it in the dependencies in case of MB analyses? Thanks!

**Review by vkucera — CHANGES_REQUESTED** [review]
Hi @zhangbiao-phy , looks good to me provided you implement the request by @fgrosa 
If `float cent = collision.centFT0C();` is the only line requiring the centrality table, you can also take it out of the function and provide it as an argument.

**Comment by fgrosa** [comment]
> Hi @zhangbiao-phy , looks good to me provided that you implement the request by @fgrosa If `float cent = collision.centFT0C();` is the only line requiring the centrality table, you can also take it out of the function and provide it as an argument.

Actually I think it would be even better to implement the method that uses the `concepts` defined by @fchinu (see Ds task https://github.com/AliceO2Group/O2Physics/blob/master/PWGHF/D2H/Tasks/taskDs.cxx#L252-L259)

**Comment by fgrosa** [comment]
@zhangbiao-phy thanks for the fast implementation! Let's see if @vkucera has other comments, otherwise it can be merged in my opinion.

**Review by vkucera — DISMISSED** [review]

**Comment by zhangbiao-phy** [comment]
Hi @vkucera, there are typos in the name of the process function. I fixed it now. Could you approve the PR again? Thanks a lot!

**Review by vkucera — APPROVED** [review]

**Pull request merged**
