### PR TITLE
Centrality task for ALICE 3

### PR DESCRIPTION
**Pull request by ddobrigk**

### CODE REVIEW

**Comment by njacazio** [comment]
Hi David, I think somehow there are unwanted changes in the cmakefile

**Review by njacazio — APPROVED** [review]
Looking good! In the future we might make sure that the selection is the same in both calibration and user task

**Comment by ddobrigk** [comment]
Thanks a lot, @njacazio ! As for getting the calib from the same task, I think this is the natural purpose of keeping the output histogram there: we can easily use that :-)

**Comment by njacazio** [comment]
I meant more, getting the limits from the ccdb object together with the calibration

**Pull request merged**
