### PR TITLE
tofSignal -> tracktime transition

### PR DESCRIPTION
**Pull request by jgrosseo**
Squashed PR https://github.com/AliceO2Group/O2Physics/pull/74 from @njacazio

### CODE REVIEW

**Review by vkucera — APPROVED** [review]
It is quite unfortunate that the [corresponding AliPhysics PR](https://github.com/alisw/AliPhysics/pull/18517) was already merged 2 days ago which now breaks running on converted data.

**Comment by jgrosseo** [comment]
Hi Vit.
We are reconverting the data over the weekend for which we obviously need the changes in AliPhysics. How would you do it?

**Comment by vkucera** [comment]
> Hi Vit.
> We are reconverting the data over the weekend for which we obviously need the changes in AliPhysics. How would you do it?

OK, if the plan is to deploy reprocessed data on AliHyperloop when the corresponding O2Physics tag is released, I agree there is not much that could be done better.

**Comment by jgrosseo** [comment]
> 
> 
> > Hi Vit.
> > We are reconverting the data over the weekend for which we obviously need the changes in AliPhysics. How would you do it?
> 
> OK, if the plan is to deploy reprocessed data on AliHyperloop when the corresponding O2Physics tag is released, I agree there is not much that could be done better.

Yes, this is the plan. As announced here: https://mattermost.web.cern.ch/alice/pl/i59pk56sx3bkzefz4dn971gxgy

**Pull request merged**
