### PR TITLE
Fix Compilation on macOS

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
https://github.com/AliceO2Group/O2Physics/pull/1422 broke macOS builds.

Notice also that lmeeLFCocktail.cxx seems to open local files. Is that the intended behaviour? I think that will not work in the trains, no?

@ddobrigk @jgrosseo

**Comment by ktf** [comment]
@TimoWilken is it normal that the O2Physics tests do not have macOS builds anymore? What happened?

**Comment by TimoWilken** [comment]
@ktf Nothing's changed. It's just that the Mac check isn't marked as required, so GitHub doesn't show it as "expected" before the CI picks it up. It'll only show up as yellow when the CI first sets its status as pending.

**Comment by ivorobye** [comment]
hi @ktf thanks a lot for quick fix, indeed it was weird that build on macOS was not checked automatically (can't we just mark the Mac check as required?) As for the access of the local files, this indeed won't work atm on train, but we are aware of it and @DanielSamitz will continue to improve the task

**Review by ivorobye — APPROVED** [review]

**Comment by dsekihat** [comment]
Hi @DanielSamitz , let's discuss where to store pT parameterizations for LF hadrons. I guess CCDB is the best place to store them.

**Comment by DanielSamitz** [comment]
@dsekihat sure. I have no experience with that, so wherever you think is suitable is fine for me.

**Pull request merged**
