### PR TITLE
Structure for the PWGCF hands-on session on the O2AT second edition

### PR DESCRIPTION
**Pull request by victor-gonzalez**

### CODE REVIEW

**Comment by victor-gonzalez** [comment]
@ddobrigk I guess it will clash with Nicolo's about LF at some point

Interesting I was not able to incorporate the tex files into the doc directory. It seems MegaLinter checks are much more restrictive that the actual LaTeX sintax

**Review by ddobrigk — APPROVED** [review]

**Comment by vkucera** [comment]
> 

Hi @victor-gonzalez , I guess you are the first one trying to commit TeX files in the repo so there is no prior experience with the LaTeX checks performed by MegaLinter. We could use this opportunity to see how strict they are and adjust them if needed. Feel free to add them in a separate PR if you prefer to merge this one first, of course.

**Comment by victor-gonzalez** [comment]
Thanks @vkucera!
Once this is merged I will create a new one with the tex files

**Comment by njacazio** [comment]
Hi Victor, I took the liberty of fixing the conflict since https://github.com/AliceO2Group/O2Physics/pull/2378 was merged

**Comment by victor-gonzalez** [comment]
Thanks a lot Nicolò!!!

**Comment by victor-gonzalez** [comment]
@TimoWilken  @ddobrigk We missed something on the road!
Compiling error 
```
/Volumes/build/build/alice-ci-workdir/o2physics/sw/SOURCES/O2Physics/2383/0/Tutorials/PWGCF/TwoParticleCorrelations/src/firstcfcorrelations.cxx:33:24: error: unused variable 'cfgPairCutDefaults' [-Werror,-Wunused-const-variable]
static constexpr float cfgPairCutDefaults[1][5] = {{-1, -1, -1, -1, -1}};
```
is only raised when producing O2Physics on macOS as part of CI

This should be raised when compiling locally either with `aliBuild` or `ninja`

**Comment by TimoWilken** [comment]
> Compiling error [...] is only raised when producing O2Physics on macOS as part of CI
> 
> This should be raised when compiling locally either with `aliBuild` or `ninja`

Hi @victor-gonzalez, sorry about that, the reason is that we use different compilers on Linux and Mac (GCC and LLVM/Clang respectively). These have different ideas of what `-Werror` means (i.e. which warnings are enabled by default), and there are so many that it's probably not practical to completely "unify" them (I think this was investigated some time last year).

Would it be alright for you to comment out the line with the variable declaration?

**Comment by victor-gonzalez** [comment]
Hi @TimoWilken, thanks a lot for the prompt answer!!!
Sure, no problem. There is an ongoing update which removes the unused variable
When I pinged you I was thinking more in the long term
Is useless that something that can be found and fixed locally goes up to involving centralized, scarce, resources
Thanks again!!

**Comment by victor-gonzalez** [comment]
@ddobrigk Could you please approve it again for it to be merged?
Thanks!!

**Comment by victor-gonzalez** [comment]
@iarsene Thanks!
But for some reason it is not merged!
Any clue?

**Comment by TimoWilken** [comment]
Tutorials/CMakeLists.txt has different code owners than the rest of the files in this PR, so one review wasn't enough. I've merged it manually.

**Comment by victor-gonzalez** [comment]
Thanks @TimoWilken!!

**Pull request merged**
