### PR TITLE
PWGHF: Move to using chi2 in vertexer

### PR DESCRIPTION
**Pull request by fcatalan92**
@vkucera I implemented what was discussed at the last HF O2 meeting. 
To not bloat the configuration too much, I have hardcoded the settings of the vertexer to the default minimisation (which is the chi2 one) everywhere unless for the `HfTrackIndexSkimCreator`, `HfCandidateCreator2Prong`, and `HfCandidateCreator3Prong` which could be used for further testing.

### CODE REVIEW

**Review by vkucera — CHANGES_REQUESTED** [review]
Thanks @fcatalan92 . Can you please also update [candidateCreatorToXiPi.cxx](https://github.com/AliceO2Group/O2Physics/blob/master/PWGHF/TableProducer/candidateCreatorToXiPi.cxx#L116)?

**Comment by fcatalan92** [comment]
For the [candidateCreatorToXiPi.cxx](https://github.com/AliceO2Group/O2Physics/blob/master/PWGHF/TableProducer/candidateCreatorToXiPi.cxx#L116), I thought these settings were used. Maybe @ZFederica could comment on that.

**Comment by ZFederica** [comment]
Hi @fcatalan92 and @vkucera , what you would change in the candidateCreatorToXiPi.cxx? Only the default value for useAbsDCA, right? (both these options are already implemented in my task, but the defaut value for useAbsDCA is true)

**Comment by fcatalan92** [comment]
Hi @ZFederica, we would remove the configuration parameters `useAbsDCA`, `useWeightedPCA`, and `refitWithMatCorr`, hardcoding the settings to their default values.

**Comment by ZFederica** [comment]
As for the candidateCreatorToXiPi.cxx, it's okay to remove the configuration parameters `useAbsDCA` and `useWeightedPCA`, but I prefer to leave the configurable `refitWithMatCorr` (if you want to change the default value of that configurable is fine)

**Review by vkucera — APPROVED** [review]

**Pull request merged**
