### PR TITLE
Remove using-directives from common headers

### PR DESCRIPTION
**Pull request by vkucera**
Using-directives should never appear in headers because they irreversibly pollute the global namespace wherever they are included and can lead to unexpected behaviour, such as name conflicts. See [O2 CodingGuidelines](https://rawgit.com/AliceO2Group/CodingGuidelines/master/coding_guidelines.html?showone=Using_declarations_and_directives#Using_declarations_and_directives).

In fact, the `evsel` namespace was indeed defined ambiguously, once as `o2::aod::evsel` in `EventSelection.h` and another time as just `evsel` in `EventSelectionParams.h`. Maybe @ekryshen can comment whether this was intentional or not.

@ddobrigk I think we should have a CI check that forbids `using namespace` in header files. That would require fixing remaining occurrences in the PWG directories (which I did not do in this PR).

### CODE REVIEW

**Comment by ekryshen** [comment]
@vkucera It wasn't intentional. Thanks for the fix.

**Review by nzardosh — DISMISSED** [review]

**Review by ekryshen — DISMISSED** [review]

**Review by ddobrigk — DISMISSED** [review]
Thanks! No objection to adding a CI; perhaps @TimoWilken can help with that? Thanks a lot!

**Comment by vkucera** [comment]
Sorry, there were a few fixes needed. It should be ready for merging now.

**Review by aalkin — DISMISSED** [review]

**Review by njacazio — APPROVED** [review]

**Comment by aalkin** [comment]
Regarding `evsel` and `aod::evsel`, I would prefer them separate. Namespace `aod` is reserved for columns and tables. Probably the functional namespace can be something like `evsel_impl` or `evsel_detail`, since it is supposed to be distinct from `aod::evsel` which contains column definitions.

**Comment by vkucera** [comment]
> 

Hi @aalkin , ok. Are you fine with renaming in a separate PR?

**Review by saganatt — APPROVED** [review]

**Review by fcatalan92 — APPROVED** [review]

**Comment by aalkin** [comment]
@vkucera yes, of course, let's not waste the approvals :)

**Comment by vkucera** [comment]
@ddobrigk @TimoWilken Is it fine for you to merge this without waiting for the remaining approvals?

**Review by ekryshen — APPROVED** [review]

**Comment by ktf** [comment]
Merged this now. I have noticed two other quite bad practices, while reviewing this:

* For no reason one should have `#include <iostream>` in headers, as it bloats every single file which includes it with statics.
* In general there should not be any reason for having statics in the header files.

**Pull request merged**
