### PR TITLE
[FIT] Add more QA plots for FIT detectors and correlation among them

### PR DESCRIPTION
**Pull request by arvindkhuntia**

### CODE REVIEW

**Comment by arvindkhuntia** [comment]
Hi @chiarazampolli, could you please approve this PR. Many thanks.

**Comment by arvindkhuntia** [comment]
Hi @noferini, could you please approve the PR. Thanks in advance.

**Review by noferini — APPROVED** [review]

**Review by noferini — CHANGES_REQUESTED** [review]
Hi @arvindkhuntia ,
it is fine with me. Can you just merge all this commits in a single one?

**Comment by arvindkhuntia** [comment]
Hi @noferini, any idea why it is not auto-merged. Thanks.

**Comment by noferini** [comment]
Hi @arvindkhuntia , I have no idea. Unfortunately I cannot do anything.
@ddobrigk , @ktf , @jgrosseo: can you approve/merge this?

**Pull request closed without merging**
