### PR TITLE
PWGHF:  B+ reduced workflow

### PR DESCRIPTION
**Pull request by apalasciano**
Implementation of the reduced workflow for the B+ ( following B0: #2456)

### CODE REVIEW

**Comment by vkucera** [comment]
@AlexBigO can you please have look and check the implementation, since this work is based on yours?

**Comment by AlexBigO** [comment]
Hi @apalasciano @vkucera ! I will have a look :)

**Review by AlexBigO — COMMENTED** [review]
Hi @apalasciano ! Nice work, everything is fine on my side :) I just have a few minor comments regarding the documentation (B0 --> Bplus mainly), `array` --> `std::array` (that I will also need to to in a future update on B0) and the `debug` variable in `processMC` of `dataCreatorD0PiReduced.cxx`.

**Comment by vkucera** [comment]
Thanks @AlexBigO for your comments. Do you consider them to be addressed?

**Review by vkucera — CHANGES_REQUESTED** [review]
Please add your name in the files you modified/added.
Update your branch and if needed, correct the list of header includes and linked libraries and the order in `CMakeLists.txt`.

**Comment by vkucera** [comment]
Hi @apalasciano , thanks for the update. Please also fix the header includes and the `CMakeLists` entries.

**Review by vkucera — CHANGES_REQUESTED** [review]

**Review by vkucera — APPROVED** [review]
Thanks @apalasciano for the fixes. It looks fine to me now.
Handing the PR over back to @fcatalan92 @lvermunt

**Review by fcatalan92 — APPROVED** [review]
Hi @apalasciano, thanks a lot for implementing the B+ workflow!
I added a few minor comments/suggestions. Nevertheless, the PR is already in very good shape.

**Review by fcatalan92 — APPROVED** [review]

**Review by vkucera — APPROVED** [review]

**Pull request merged**
