### PR TITLE
Move mcCollsExtra table producer in Common, and adapt interested workflows.

### PR DESCRIPTION
**Pull request by mfaggin**

### CODE REVIEW

**Comment by mfaggin** [comment]
@ddobrigk here the implementation we discussed this morning.
I tried locally to run my workflow of DPG (i.e. `DPG/Tasks/AOTTracks/qaEventTracksLiteProducer.cxx`) and it worked properly.
I adapted also all the workflows consuming the `McCollsExtra` table (found with ` grep -rni "McCollsExtra"`).

**Comment by ddobrigk** [comment]
Many many thanks @mfaggin ! While at it could you perhaps also change `hasRecoCollision` to `nRecoCollision`? Since it is an integer and not a bool I guess this naming is better. Thanks a lot!

**Comment by mfaggin** [comment]
Hi @ddobrigk , done in my last commit

**Review by ddobrigk — APPROVED** [review]

**Comment by mfaggin** [comment]
just a reminder for this PR

**Review by ChiaraDeMartin95 — APPROVED** [review]

**Comment by mfaggin** [comment]
just a reminder for this PR @lramona @lbariogl @chiarapinto @njacazio @BongHwi @mbombara @iravasen @skundu692 @jgrosseo @iarsene @ktf

**Review by chiarapinto — APPROVED** [review]

**Comment by chiarapinto** [comment]
@njacazio can you please have a look? ;)

**Comment by ddobrigk** [comment]
HI @mfaggin I am not actually sure what happened here. This has been fully approved - I think - but then there was a CI problem, and now it is still stuck somehow. I also cannot approve this (I already approved it before)...

Maybe we need some expert intervention? Tagging @TimoWilken - thanks!

**Review by njacazio — APPROVED** [review]
It's ok, vamos!

**Comment by ddobrigk** [comment]
Ok, that did it! Grazie mille!

**Comment by njacazio** [comment]
We missed the dpg one

**Pull request merged**
