### PR TITLE
polarization studies in the kstar and phi resonance

### PR DESCRIPTION
**Pull request by sawankumawat**

### CODE REVIEW

**Comment by skundu692** [comment]
Avoid to copy a code. It does not make any sense. A flow code for kstar is already exist if you want to add polarization then add it there.

**Review by skundu692 — CHANGES_REQUESTED** [review]
There is already a code exist for kstar flow. Would it be possible to add this observables there in order to avoid the repetition of large ammount of existing code. If you want we could discuss in resonance PAG

**Comment by dmallick2** [comment]
yes the existing phi code can be used to calculate polarization and flow using event plane. This code for polarization studies  for different axes ( helicity frame, production plane, beam and random axes ). It is possible to make a single macro. To prepare a different macro for such polarization studies where event plane calculations are not needed.

**Comment by skundu692** [comment]
@dmallick2 would it be possible to add your observable in the existing task and fill additional histogram. If you want we could also discuss this in resonance PAG.

**Comment by dmallick2** [comment]
@skundu692. okay. we will discuss in PAG meeting.

**Pull request closed without merging**
