### PR TITLE
PWGCF: JCorran: Fix track filters

### PR DESCRIPTION
**Pull request by jaelpark**
Minor fixes to track filters

### CODE REVIEW

**Review by victor-gonzalez — APPROVED** [review]

**Comment by victor-gonzalez** [comment]
@jaelpark Please, before I merge it, please, fix the compiler warning in `PWGCF/JCorran/Core/JHistManager.cxx` in the `build/O2Physics/o2` compilation. You find them under the `Details` link

The warning are going to be promoted to errors but before this is done we need a clean start
Thanks!!!

**Comment by jaelpark** [comment]
Alright, that should take care of the warnings.

**Comment by victor-gonzalez** [comment]
Thanks!

**Comment by jaelpark** [comment]
Hi @victor-gonzalez I think it needs another approval..

**Review by victor-gonzalez — APPROVED** [review]
Oh! Sorry about that!

**Pull request merged**
