### PR TITLE
pDCAcutOptimization

### PR DESCRIPTION
**Pull request by bhsaho**

### CODE REVIEW

**Comment by lucamicheletti93** [comment]
@bhsaho there is still one conflict in the histogram library. Could you just have a look at it?

**Comment by bhsaho** [comment]
Dear @lucamicheletti93 , I resolved the issue in the histogram library.

**Review by lucamicheletti93 — APPROVED** [review]

**Comment by bhsaho** [comment]
Dear @lucamicheletti93 , Sorry for troubling you again.  The auto-merge disabled for this PR. Can you please have a look at it again ?

**Comment by bhsaho** [comment]
Dear Experts, This is a gentle reminder regarding this PR. Could you kindly have a look at it ?

**Review by lucamicheletti93 — APPROVED** [review]

**Comment by bhsaho** [comment]
Thank you @lucamicheletti93

**Pull request merged**
