### PR TITLE
DPG: add the flag for the specific track selection

### PR DESCRIPTION
**Pull request by zhangbiao-phy**

### CODE REVIEW

**Review by mfaggin — DISMISSED** [review]
@njacazio I approve this PR so that the guys can profit of this commit already on tomorrow's tag. It looks good to me, but please look at it when you have time.

**Comment by mfaggin** [comment]
> Hi Mattia, I looked already, I'm not sure I like it, we need to change more if we want to be using ` soa::Filtered<TrackTableMC> const& tracks,` now

ah you are right, in the actual code we do not filter but we cut manually only when desired. We cannot accept this PR as it is, I think @njacazio is going to transalte it now

**Comment by zhangbiao-phy** [comment]
> @zhangbiao-phy fix the formatting issues and then I approve it

Hi @mfaggin, Thanks a lot! Done!

**Comment by mfaggin** [comment]
> > @zhangbiao-phy fix the formatting issues and then I approve it
> 
> Hi @mfaggin, Thanks a lot! Done!

thanks Biao, but indeed Nicolò is right, let's ait for his fix (he is working on it)

**Comment by zhangbiao-phy** [comment]
> 

Hi @mfaggin and @njacazio, thanks 

> > > @zhangbiao-phy fix the formatting issues and then I approve it
> > 
> > 
> > Hi @mfaggin, Thanks a lot! Done!
> 
> thanks Biao, but indeed Nicolò is right, let's wait for his fix (he is working on it)

Thanks @mfaggin and @njacazio!

**Comment by njacazio** [comment]
I propose the following https://github.com/AliceO2Group/O2Physics/pull/1024 if you agree we follow this there, thanks Biao for implementing this, it was highly due

**Comment by mfaggin** [comment]
> I propose the following #1024 if you agree we follow this there, thanks Biao for implementing this, it was highly due

much better, if this works for @zhangbiao-phy it's definitely in line with the older version and better for us

**Comment by njacazio** [comment]
Handled in the other PR https://github.com/AliceO2Group/O2Physics/pull/1024

**Pull request closed without merging**
