### PR TITLE
[PWG-CF] Femto3D: extend data model

### PR DESCRIPTION
**Pull request by njacazio**
- minor improvements
- remove dependencies

### CODE REVIEW

**Comment by njacazio** [comment]
@glromane please have a look
@victor-gonzalez this extends the data model to handle the comments received today during the forum. Let us know if you have suggestions for the conversions

**Comment by victor-gonzalez** [comment]
@njacazio I'm confused, do you want to get rid of the files that are empty in this PR?

**Comment by njacazio** [comment]
Hi @victor-gonzalez no, I changed the permissions for those files that were executables. I also realized that the compilation fails for mac, I will have to change it

**Comment by victor-gonzalez** [comment]
@njacazio Still fails the compilation, right?

**Comment by njacazio** [comment]
Indeed, thanks Victor, let's keep it as a draft for now

**Comment by njacazio** [comment]
Closing and handed to Gleb here https://github.com/AliceO2Group/O2Physics/pull/6098

**Pull request closed without merging**
