### PR TITLE
Quering orbitReset timestamp with EOR timestamp instead of SOR

### PR DESCRIPTION
**Pull request by ekryshen**
Sometimes CTP resets orbit after SOR (but before SOX). So ccdb query with SOR timestamp provides wrong orbitReset reference. It usually affects the first run in the fill. It is more reliable to use EOR timestamp to request orbitReset.

### CODE REVIEW

**Review by ddobrigk — DISMISSED** [review]
thanks for the quick fix!!!!

**Review by ddobrigk — APPROVED** [review]
Thanks for taking care of this!

**Comment by jgrosseo** [comment]
@ekryshen This seems to brake Run 2 analysis, see https://alice.its.cern.ch/jira/browse/O2-3416
Do you want to revert it or have a better solution?

**Comment by ekryshen** [comment]
@jgrosseo Hm, then we could simply check SOR for Run2 and EOR for Run3.

**Comment by jgrosseo** [comment]
Yes, let's do that. Or (SOR+EOR) / 2 for both cases. Could you make a PR with the solution you prefer?

**Pull request merged**
