### PR TITLE
[Commom] Add task for calculations of event plane resolution

### PR DESCRIPTION
**Pull request by jikim1290**
Add task for calculations of event plane resolution

### CODE REVIEW

**Comment by jgrosseo** [comment]
@ddobrigk Should this really be in common?

**Comment by jikim1290** [comment]
@jgrosseo This work is originated from DPG service work:
https://alice-glance.cern.ch/service-work/tasks/609

The event plane method can be used for so various PWGs that I decided locate them in common.
In AliPhysics, the same task is in AliPhysics/PWG/FLOW (let me know if wrong).

If you think the current place is not proper, we can move these codes.

**Comment by jgrosseo** [comment]
> @jgrosseo This work is originated from DPG service work: https://alice-glance.cern.ch/service-work/tasks/609
> 
> The event plane method can be used for so various PWGs that I decided locate them in common. In AliPhysics, the same task is in AliPhysics/PWG/FLOW (let me know if wrong).
> 
> If you think the current place is not proper, we can move these codes.

Fine with me

**Comment by ddobrigk** [comment]
Looks ok to me. I also think that common tools for centrality calculation etc are also under ./Common so the location is fine. Thanks!

**Review by ddobrigk — APPROVED** [review]

**Pull request merged**
