### PR TITLE
Developments of data model and tasks for skimming and candidates creation in UD

### PR DESCRIPTION
**Pull request by nburmaso**
Summary of changes:
* Add data model for reduced tables in UD: collisions, MC information, central barrel and forward tracks
* Add track skimming task for ambiguous tracks
* Add task for candidates creation using skimmed ambiguous tracks
* Merge tables from DGCandidates with new UDTables
* Adapt DG tasks to UDTables (basically, matter of renaming)

### CODE REVIEW

**Comment by pbuehler** [comment]
On line 72 of UDTables.h it says:
using SkimmedMCParticle = UDMcParticles::iterator;

which should be changed to
using UDMCParticle = UDMcParticles::iterator;

**Comment by pbuehler** [comment]
I propose to make the names of the tasks UDCandidateCreator, UDTrackSkimmer, dimuonAnalysis, trackSkimmerQA more specific to distinguish them from (future) other UD related tasks. They should somehow include the terms, UPC, Fwd, .... Also instead of Creator use Producer.

**Comment by nburmaso** [comment]
Hi @pbuehler. Thank you for your comments! I have fixed typos and naming according to your suggestions. I have also reworked analyzer task for dimuons and changed its name -- its name now is `UPCCandAnalyzer`, for consistency with your task. Please let me know if there are more issues.

Nazar

**Comment by pbuehler** [comment]
+1

**Review by pbuehler — APPROVED** [review]

**Pull request merged**
