### PR TITLE
PWGDQ: fixing the configuration file for the fit

### PR DESCRIPTION
**Pull request by lucamicheletti93**
Fixing the configuration file for the fit

### CODE REVIEW

**Review by iarsene — DISMISSED** [review]

**Comment by lucamicheletti93** [comment]
Dear @TimoWilken, I'm having this issue with MegaLinter, in particular the issue seems to be related to "PR not clear" but I don't  know how this can be fixed. Do you have any suggestion?

**Comment by TimoWilken** [comment]
Hi @lucamicheletti93, the auto-fixes applied by MegaLinter are in a pull request in your fork of O2Physics: https://github.com/lucamicheletti93/O2Physics/pull/2.

**Comment by lucamicheletti93** [comment]
Dear @TimoWilken , thanks a lot! This means that I don't need to do any action?

**Comment by TimoWilken** [comment]
No, you should look at the pull request I linked to, and merge it. Only then will the MegaLinter check in this pull request succeed. Alternatively, you can make similar formatting fixes manually.

**Comment by lucamicheletti93** [comment]
Dear @TimoWilken , thanks for the explanation! I have approved the changes but it seems that the PR is not yet merged. How should I proceed? Would it be better to apply by hand the changes and do another commit?

**Comment by TimoWilken** [comment]
Hi @lucamicheletti93, the PR https://github.com/lucamicheletti93/O2Physics/pull/2 is in your own repository, so you need to merge it directly using the large "Squash and merge" button near the bottom of the page I linked above.

Only approving it will not do anything, because the pull request is in your own repository.

Alternatively, if you prefer, you can look at the changes [here](https://github.com/lucamicheletti93/O2Physics/pull/2/files) and apply them manually. You can also [download the patch file from here](https://github.com/lucamicheletti93/O2Physics/pull/2.patch) and pass it to the `git apply` command in your repository to apply the changes, then run `git commit`.

**Comment by lucamicheletti93** [comment]
Dear @TimoWilken , thanks again for the explanation! I did "Squash and merge" and the test started

**Review by iarsene — APPROVED** [review]

**Pull request merged**
