### PR TITLE
added the competing lambda rejection cut and rapidity histograms for …

### PR DESCRIPTION
**Pull request by sawankumawat**
- Competing v0 rejection cut
- rapidity histograms for daughter particles

### CODE REVIEW

**Comment by sawankumawat** [comment]
- Added the boolean configurable for the multiplicity estimator to do both Pb-Pb and p-p studies with same code.
- Added pT depend nSigma distributions

**Comment by sawankumawat** [comment]
@BongHwi Please approve.
Thank you

**Comment by sawankumawat** [comment]
Please approve.

**Comment by sawankumawat** [comment]
@skundu692 Please approve 

Thankyou

**Review by skundu692 — APPROVED** [review]

**Comment by sawankumawat** [comment]
Please merge the changes into the master branch.
Thank you

**Comment by sawankumawat** [comment]
Please merge the changes @njacazio

**Comment by sawankumawat** [comment]
Is there a technical issue with my pull request? It seems it hasn't been merged yet. Should I try creating the pull request again? @BongHwi @skundu692 @njacazio

**Comment by sawankumawat** [comment]
Please merge this commit into the master branch @skundu692 @BongHwi @njacazio.

Thank you

**Pull request merged**
