### PR TITLE
added thnsparse for primaries/secondaries fractions analysis

### PR DESCRIPTION
**Pull request by rosarioturrisi**

### CODE REVIEW

**Review by mfaggin — COMMENTED** [review]
Thanks @rosarioturrisi , it looks ok to me from a quick look, please consider a few simple comments

**Comment by rosarioturrisi** [comment]
Ciao Mattia,
thank you for spotting those points.  My comments below.
In the future I think histos will go and just the thnsparse will stay making the class really simple, I keep those histos for the moment to have the 
machine always ready for the checks.
	R.

> On 8 Feb 2023, at 16:00, Mattia Faggin ***@***.***> wrote:
> 
> 
> @mfaggin commented on this pull request.
> 
> Thanks @rosarioturrisi <https://github.com/rosarioturrisi> , it looks ok to me from a quick look, please consider a few simple comments
> 
> In DPG/Tasks/AOTTrack/qaMatchEff.cxx <https://github.com/AliceO2Group/O2Physics/pull/1949#discussion_r1100238377>:
> 
> > +  ConfigurableAxis thnPt{"thnPt", {30, 0.0f, 15.0f}, "pt [GeV/c]"};
> +  ConfigurableAxis thnPhi{"thnPhi", {18, 0.0f, TMath::TwoPi()}, "phi"};
> +  ConfigurableAxis thnEta{"thnEta", {20, -2.0f, 2.0f}, "eta"};
> +  ConfigurableAxis thnType{"thnType", {3, -0.5f, 2.5f}, "particle class"};
> +  ConfigurableAxis thnLabelSign{"thnLabelSign", {3, -1.5f, 1.5f}, "particle label sign"};
> +  ConfigurableAxis thnSpec{"thnSpec", {5, 0.5f, 5.5f}, "particle from MC (1,2,3,4,5 -> e,pi,K,P,other)"};
> +  AxisSpec thnd0Axis{thnd0, "#it{d}_{r#it{#varphi}} [cm]"};
> +  AxisSpec thnPtAxis{thnPt, "#it{p}_{T}^{reco} [GeV/#it{c}]"};
> +  AxisSpec thnPhiAxis{thnPhi, "#varphi"};
> +  AxisSpec thnEtaAxis{thnEta, "#it{#eta}"};
> +  AxisSpec thnTypeAxis{thnType, "particle class"};
> +  AxisSpec thnLabelSignAxis{thnLabelSign, "particle label sign"};
> +  AxisSpec thnSpecAxis{thnSpec, "particle from MC (1,2,3,4,5 -> e,pi,K,P,other)"};
> +  //
> +  //
> +  ConfigurableAxis thnPDGAxis{"thnpdgaxis", {3, 0.5f, 3.5f}, "species (1: pi, 2: K, 3: p)"};
> where do you want to use it? Currently, this is not used at all, if I'm not wrong, and you are already using thnSpecAxis in place of it. Then, I would remove this line.
> 
indeed it’s a remnant of the original class, line that I modified and renamed to keep things more readable. It’s now gone.
> 
> In DPG/Tasks/AOTTrack/qaMatchEff.cxx <https://github.com/AliceO2Group/O2Physics/pull/1949#discussion_r1100250899>:
> 
> > @@ -89,6 +89,26 @@ struct qaMatchEff {
>    // pdg codes vector
>    std::vector<int> pdgChoice = {211, 213, 215, 217, 219, 221, 223, 321, 411, 521, 2212, 1114, 2214};
>    //
> +  // configuration for THnSparse's
> +  //
> +  Configurable<bool> makethn{"makethn", false, "choose if produce thnsparse"};
> +  ConfigurableAxis thnd0{"thnd0", {600, -3.0f, 3.0f}, "impact parameter in xy [cm]"};
> +  ConfigurableAxis thnPt{"thnPt", {30, 0.0f, 15.0f}, "pt [GeV/c]"};
> +  ConfigurableAxis thnPhi{"thnPhi", {18, 0.0f, TMath::TwoPi()}, "phi"};
> +  ConfigurableAxis thnEta{"thnEta", {20, -2.0f, 2.0f}, "eta"};
> +  ConfigurableAxis thnType{"thnType", {3, -0.5f, 2.5f}, "particle class"};
> +  ConfigurableAxis thnLabelSign{"thnLabelSign", {3, -1.5f, 1.5f}, "particle label sign"};
> +  ConfigurableAxis thnSpec{"thnSpec", {5, 0.5f, 5.5f}, "particle from MC (1,2,3,4,5 -> e,pi,K,P,other)"};
> +  AxisSpec thnd0Axis{thnd0, "#it{d}_{r#it{#varphi}} [cm]"};
> +  AxisSpec thnPtAxis{thnPt, "#it{p}_{T}^{reco} [GeV/#it{c}]"};
> +  AxisSpec thnPhiAxis{thnPhi, "#varphi"};
> +  AxisSpec thnEtaAxis{thnEta, "#it{#eta}"};
> +  AxisSpec thnTypeAxis{thnType, "particle class"};
> I would add explicitly in the comment that 0 mean primary, 1 from material and 2 secondary
> 
Done.
> 
> In DPG/Tasks/AOTTrack/qaMatchEff.cxx <https://github.com/AliceO2Group/O2Physics/pull/1949#discussion_r1100252654>:
> 
> > +  // configuration for THnSparse's
> +  //
> +  Configurable<bool> makethn{"makethn", false, "choose if produce thnsparse"};
> +  ConfigurableAxis thnd0{"thnd0", {600, -3.0f, 3.0f}, "impact parameter in xy [cm]"};
> +  ConfigurableAxis thnPt{"thnPt", {30, 0.0f, 15.0f}, "pt [GeV/c]"};
> +  ConfigurableAxis thnPhi{"thnPhi", {18, 0.0f, TMath::TwoPi()}, "phi"};
> +  ConfigurableAxis thnEta{"thnEta", {20, -2.0f, 2.0f}, "eta"};
> +  ConfigurableAxis thnType{"thnType", {3, -0.5f, 2.5f}, "particle class"};
> +  ConfigurableAxis thnLabelSign{"thnLabelSign", {3, -1.5f, 1.5f}, "particle label sign"};
> +  ConfigurableAxis thnSpec{"thnSpec", {5, 0.5f, 5.5f}, "particle from MC (1,2,3,4,5 -> e,pi,K,P,other)"};
> +  AxisSpec thnd0Axis{thnd0, "#it{d}_{r#it{#varphi}} [cm]"};
> +  AxisSpec thnPtAxis{thnPt, "#it{p}_{T}^{reco} [GeV/#it{c}]"};
> +  AxisSpec thnPhiAxis{thnPhi, "#varphi"};
> +  AxisSpec thnEtaAxis{thnEta, "#it{#eta}"};
> +  AxisSpec thnTypeAxis{thnType, "particle class"};
> +  AxisSpec thnLabelSignAxis{thnLabelSign, "particle label sign"};
> does it mean particle or antiparticle? If yes, please specify it as well in the comment
> 
it's the sign of the pdg code, so yes, I will mention explicitly.

**Comment by mfaggin** [comment]
Thanks @rosarioturrisi , as son as you push the few changes, I approve it

**Comment by mfaggin** [comment]
@rosarioturrisi still issues in the clang format

**Pull request closed without merging**
