### PR TITLE
PWGHF: add candidate collIision Id to treeCreatorToXiPi

### PR DESCRIPTION
**Pull request by ZFederica**
- add candidate collIision Id to treeCreatorToXiPi for rejection factor studies

### CODE REVIEW

**Comment by vkucera** [comment]
Hi @ZFederica , can you please elaborate on how the collision index is supposed to be used in the studies you mention?

**Comment by ZFederica** [comment]
Hi @vkucera, if I had this information available offline I could play around with the selections on the saved variables, making them more or less tight, and checking how many different collision indexes I have in the end. This would allow me to trace back to how many events I would save with which selections.

**Comment by vkucera** [comment]
I assume the fraction of collisions with more than one Omega_c is negligible so I would expect that whatever candidate selection you vary, the resulting change in the number of collisions will be equal to the change in the number of candidates. Am I missing something?

**Comment by vkucera** [comment]
Yes, I understand, I meant the candidates. But OK, give it a try.

**Review by vkucera — APPROVED** [review]

**Pull request merged**
