### PR TITLE
PWGHF: extending pT range to 36 GeV/c in taskD0 MC-mode histograms

### PR DESCRIPTION
**Pull request by fcolamar**

### CODE REVIEW

**Comment by fcolamar** [comment]
@ginnocen @vkucera just a minimal update to the D0 task (in agreement with Sourav).
I need a higher pT reach for some D0 histograms in order to be able to extract the efficiencies above 10 GeV/c (which I need for the D0D0bar studies)

**Comment by ginnocen** [comment]
Ciao @fcolamar, sure. it is approved and will be merged as soon as tests are passed

**Comment by vkucera** [comment]
@TimoWilken It seems that code owners are not asked for a review anymore.

**Comment by vkucera** [comment]
Hi @fcolamar , these histograms are used for the Run 3 validation as well. Can you check, whether the validation plots have changed?

**Comment by TimoWilken** [comment]
@vkucera fixed!

**Review by ginnocen — APPROVED** [review]

**Pull request merged**
