### PR TITLE
PWGDQ: Adding CCDB to table reader

### PR DESCRIPTION
**Pull request by lucamicheletti93**
Adding CCDB to table reader and small fix to the CosThetaHE range definition

### CODE REVIEW

**Comment by lucamicheletti93** [comment]
Dear @iarsene , are there comments to this PR?

**Comment by iarsene** [comment]
Hi @lucamicheletti93,
Since it was a draft i did not received notifications somehow and it slipped under the radar. To me it looks fine, but it is a bit unclear of what is the object that is loaded fromt he CCDB. Is this the "Users/lm", which i guess it is a TH1F histogram?
Cheers,
Ionut

**Comment by lucamicheletti93** [comment]
Dear @iarsene, thanks a lot for the quick answer!  For the moment the object is a TH1F, since it is rather versatile. The object is loaded into my personal directory by default, but it could be congifured by the user.
Cheers, 
Luca

**Comment by iarsene** [comment]
Thanks Luca, i understand. Ok, i think that we can merge this now. This will work nicely as an example and then we see what else we can do depending on what else we will need in the future. Can you open it for review, so we can merge?

**Comment by iarsene** [comment]
There are some conflicts that need to be fixed

**Comment by lucamicheletti93** [comment]
Dear @iarsene ,
do I have the rights to solve the conflicts? (it is the first time I do this kind of modification)

**Comment by jgrosseo** [comment]
You fix it locally and push to your branch (no need to open/close the PR)

**Comment by iarsene** [comment]
Hi @lucamicheletti93 , i fixed it.

**Comment by iarsene** [comment]
> Dear @iarsene , do I have the rights to solve the conflicts? (it is the first time I do this kind of modification)

We can chat privately on mattermost on how to do this for the future

**Review by iarsene — APPROVED** [review]

**Pull request merged**
