### PR TITLE
Slimming on updated version

### PR DESCRIPTION
**Pull request by rosarioturrisi**
A number of histograms have been commented out, and the thnsparse shortened by one axis.

### CODE REVIEW

**Comment by rosarioturrisi** [comment]
Hi Mattia, sorry for the previous PR, I keep two forks locally one for developement and the second to cross-check, I think I mixed up some stuff. I had to cut out some histos and slim a bit the thnsparse, on two AO2D's it looks fine

**Review by mfaggin — DISMISSED** [review]
thanks @rosarioturrisi now indeed it seems that you simply reduce the amount of histograms that are filled. Informing also @ChunzhengLab

**Comment by ChunzhengLab** [comment]
Got it. Thank you.

**Comment by rosarioturrisi** [comment]
Hi @mfaggin and @ChunzhengLab, sorry for the close update of the PR, I could improve the thnsparse and slim again the histo list.

**Review by mfaggin — APPROVED** [review]

**Comment by mfaggin** [comment]
@rosarioturrisi beware of the macos compilation error saying that `int itsNhits = 0;` is defined but never used. You can probably just comment it out.

**Comment by rosarioturrisi** [comment]
@mfaggin commented out itsNhits, should be ok now

**Review by mfaggin — APPROVED** [review]
thanks @rosarioturrisi

**Pull request merged**
