### PR TITLE
[DPG] Redefine the Histogram for the mother

### PR DESCRIPTION
**Pull request by upasanasharma31**
Redefine the Histogram for the mother

### CODE REVIEW

**Review by njacazio — APPROVED** [review]

**Comment by njacazio** [comment]
Hi @upasanasharma31 this does not compile. How did you test it?

**Comment by vkucera** [comment]
@upasanasharma31 This looks like a duplicate of https://github.com/AliceO2Group/O2Physics/pull/8760 which you closed. Why?

**Comment by vkucera** [comment]
Btw, the `abs` bug is still there.

**Comment by upasanasharma31** [comment]
> @upasanasharma31 This looks like a duplicate of #8760 which you closed. Why?

I Aplogies! In the previous PR. I wasn’t able to fully understand what was going wrong, so I decided to close that PR and create a new one

**Comment by upasanasharma31** [comment]
> Hi @upasanasharma31 this does not compile. How did you test it?

Sorry, I didn't test it.

**Comment by vkucera** [comment]
> > @upasanasharma31 This looks like a duplicate of #8760 which you closed. Why?
> 
> I Apologies! In the previous PR. I wasn’t able to fully understand what was going wrong, so I decided to close that PR and create a new one

Closing a PR and opening a new one with the same content never solves any problem. It just creates a duplicate which has to be reviewed and tested from scratch.

**Review by njacazio — APPROVED** [review]

**Comment by vkucera** [comment]
> Btw, the `abs` bug is still there.

Still there...

**Pull request merged**
