### PR TITLE
Adjust analysis tasks for GroupSlicer separated from AnalysisTask.h

### PR DESCRIPTION
**Pull request by saganatt**
Follow-up to AliceO2Group/AliceO2#7781

### CODE REVIEW

**Review by victor-gonzalez — DISMISSED** [review]

**Comment by jgrosseo** [comment]
@saganatt This depends on which O2 PRs?

**Comment by jgrosseo** [comment]
@saganatt We check O2Physics in the O2 CI. This means that both PR CIs will fail, right? And we possibly need to sync and force the merge.

**Comment by saganatt** [comment]
> @saganatt We check O2Physics in the O2 CI. This means that both PR CIs will fail, right? And we possibly need to sync and force the merge.

Ah, right, both repos need to be updated at once... How to do it?

**Comment by jgrosseo** [comment]
We first see if the O2 CI passes (except O2Physics), then I can force it (unless you see a trick to decouple it...)

**Comment by saganatt** [comment]
ok, thanks!

**Comment by iarsene** [comment]
@saganatt  I just merged a PR with changes in tableReader.cxx, which are now in conflict with this PR. It can be fixed easily though

**Comment by saganatt** [comment]
@iarsene thanks for the info, I rebased

**Pull request merged**
