### PR TITLE
Code for PID analysis

### PR DESCRIPTION
**Pull request by Lukaszz99**

### CODE REVIEW

**Comment by mario-krueger** [comment]
Hello Łukasz,
thanks a lot for your contribution.

As this is your first commit, I have a few general comments:
- In order to commit code to O2Physics you need to streamline the formatting according to the conventions with the `clang-format` tool. Just install it, navigate to your file and run `clang-format -i pidAnalysis.cxx`. This will fix indentation, etc as defined here: https://github.com/AliceO2Group/O2Physics/blob/master/.clang-format.
- That said, in my opinion the name `pidAnalysis` is a bit generic. If it is meant as a qa task for pid, I would stick to the naming pattern used in the other tasks and call it `qaPid` or similar. Then the executable name will be `o2-analysis-qa-pid`.
- For your variable names it would be better to stick to the coding conventions defined here https://rawgit.com/AliceO2Group/CodingGuidelines/master/naming_formatting.html. This affects all the variable and function names containing an underscore, where one should use `camelCase` instead. Admittedly, this is not really being enforced consistently, as you can see in some of the other tasks, but I think it would be nice if all the O2Phyiscis code is somehow similar in order to improve readability.
- Also, it is convention to not use one-line `if-else`, `for` and `while` statements without `readability braces` (`{}`). This means instead of `if(a) doB();` it needs to be `if(a) { doB; }`.
- Though it is possible to have multiple histogram registries, I would encourage using only one. The histogram registry always reserves 512 slots for histograms. This means that having multiple histogram registries is a bit inefficient.
Also, in the output file all your histograms will be stored at the same directory level anyway (one could put the Histogram Registry histograms in dedicated folders via the last argument in the constructor, see here: https://github.com/AliceO2Group/AliceO2/blob/dev/Framework/Core/include/Framework/HistogramRegistry.h#L90).
However, I think the cleanest way is to use just one HistogramRregistry and put the histograms in subfolders by specifying the corresponding path in the name e.g. `"contamination/some_hist"` (you can have a look at the tutorial: https://github.com/AliceO2Group/O2Physics/blob/master/Tutorials/src/histogramRegistry.cxx for inspiration). This will create a folder called `contamination` in your output file.

Please find a few more specific comments inline.
Cheers,
   Mario

**Comment by saganatt** [comment]
Hi @mario-krueger , could you please check if it looks good to you now?
We will wait for the checks to complete but we need to push a bit, as Łukasz needs this analysis for his thesis.

**Review by mario-krueger — APPROVED** [review]

**Comment by jgrosseo** [comment]
This fails the Mac CI. Please fix...

`/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DBOOST_ALL_NO_LIB -DBOOST_CONTAINER_DYN_LINK -DBOOST_ERROR_CODE_HEADER_ONLY -DBOOST_FILESYSTEM_DYN_LINK -DBOOST_IOSTREAMS_DYN_LINK -DBOOST_PROGRAM_OPTIONS_DYN_LINK -DBOOST_REGEX_DYN_LINK -DBOOST_SERIALIZATION_DYN_LINK -DDPL_ENABLE_BACKTRACE -DFAIRMQ_HAS_STD_FILESYSTEM=1 -DFMT_LOCALE -I/Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/SOURCES/O2Physics/443/0 -I/Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/SOURCES/O2Physics/443/0/Common/Core -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/osx_x86-64/O2/nightly-20220113-local2/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/osx_x86-64/Common-O2/v1.6.0-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/osx_x86-64/boost/v1.75.0-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/osx_x86-64/Configuration/v2.6.3-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/osx_x86-64/libInfoLogger/v2.4.2-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/osx_x86-64/Monitoring/v3.10.1-local2/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/osx_x86-64/curl/7.70.0-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/osx_x86-64/FairMQ/v1.4.46-local1/include/fairmq -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/osx_x86-64/FairMQ/v1.4.46-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/osx_x86-64/FairLogger/v1.10.4-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/osx_x86-64/fmt/8.0.1-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/osx_x86-64/ROOT/v6-24-06-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/osx_x86-64/O2/nightly-20220113-local2/include/GPU -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/osx_x86-64/FairRoot/v18.4.2-local2/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/osx_x86-64/arrow/v5.0.0-alice3-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/osx_x86-64/Vc/1.4.1-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/osx_x86-64/ms_gsl/3.1.0-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/osx_x86-64/libjalienO2/0.1.3-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/osx_x86-64/RapidJSON/v1.1.0-alice2-local1/include -isystem /Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/osx_x86-64/libuv/v1.40.0-local1/include -fPIC -O2 -std=c++17 -Wall -O2 -g -DNDEBUG -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.0.sdk -mmacosx-version-min=11.6 -std=gnu++17 -MD -MT DPG/Tasks/CMakeFiles/O2Physicsexe-analysis-qa-pid.dir/qaPid.cxx.o -MF DPG/Tasks/CMakeFiles/O2Physicsexe-analysis-qa-pid.dir/qaPid.cxx.o.d -o DPG/Tasks/CMakeFiles/O2Physicsexe-analysis-qa-pid.dir/qaPid.cxx.o -c /Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/SOURCES/O2Physics/443/0/DPG/Tasks/qaPid.cxx
/Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/SOURCES/O2Physics/443/0/DPG/Tasks/qaPid.cxx:359:26: error: variable-sized object may not be initialized
    float particleNSigma[arrLen] = {};
                         ^~~~~~
/Volumes/build/build/ci_checks/alice_ci_0/o2physics/sw/SOURCES/O2Physics/443/0/DPG/Tasks/qaPid.cxx:420:26: error: variable-sized object may not be initialized
    float particleNSigma[arrLen] = {};`

**Comment by jgrosseo** [comment]
https://ali-ci.cern.ch/alice-build-logs/AliceO2Group/O2Physics/443/f2b597cca4a604ec1288a2ab5c5b655eeabbfbae/build_O2Physics_o2_macOS/pretty.html

**Pull request merged**
