### PR TITLE
RecoDecay: Add message about deprecating getMassPDG

### PR DESCRIPTION
**Pull request by vkucera**
Requires #3105

### CODE REVIEW

**Comment by vkucera** [comment]
@ddobrigk What do you think?

**Comment by aalkin** [comment]
There is a conventional method to do it (https://en.cppreference.com/w/cpp/language/attributes/deprecated), it produces warnings during compilation.

**Comment by vkucera** [comment]
> There is a conventional method to do it (https://en.cppreference.com/w/cpp/language/attributes/deprecated), it produces warnings during compilation.

Hi @aalkin , thanks, I was not aware of that. I can add it. I would also keep the error though, because I suspect that most people do not read (or care about) the compilation warnings as long as it compiles and the runtime error makes this migration reminder more visible.

**Comment by aalkin** [comment]
I have to agree :)

**Pull request merged**
