### PR TITLE
debug print outs for aod-merger

### PR DESCRIPTION
**Pull request by chiarazampolli**
@catalinristea, this is what I had locally. 
@jgrosseo , we briefly discussed this last week, let me know if it is ok for you. Currently the logs from the merger are really many.

### CODE REVIEW

**Comment by chiarazampolli** [comment]
Hello @jgrosseo , 
MegaLinter gives several errors but not on things that I changed. I would prefer that you change that, if possible.
Thanks!
Chiara

**Comment by chiarazampolli** [comment]
Dear @jgrosseo , 
What should I do for the MegaLinter errors? Will you fix those? Should I give it a try? Maybe someone else should take a look?
Chiara

**Comment by jgrosseo** [comment]
Ciao @chiarazampolli 
I have added a `verbosity` option some time back and tagged you here: https://github.com/AliceO2Group/O2Physics/pull/2320#issuecomment-1495563043

I think this should do what is done in this PR. Shall we close it then?

Let me know!

**Comment by chiarazampolli** [comment]
Hello @jgrosseo , 

Ah, sorry, I missed it. 
Yes, that is very helpful, thanks! Pinging at @catalinristea, for his knowledge.

Chiara

**Pull request closed without merging**
