### PR TITLE
Event mixing: Examples for new interface

### PR DESCRIPTION
**Pull request by saganatt**
2 simple examples with declaration in struct and inside `process()`.

Note: This does not work yet with Filtered and Partitioned tables, work ongoing.

### CODE REVIEW

**Review by iarsene — APPROVED** [review]

**Comment by iarsene** [comment]
Hi Maja, 
The new implementation looks nice and easier for the user. I approved, but i see that there are some messages from aliBuild, although no check failed. So maybe @jgrosseo or @ktf can have a look into this.

**Comment by saganatt** [comment]
Thanks! I wonder if aliBuild build on older O2 (before merge of my mixing codes in framework).

**Review by jgrosseo — APPROVED** [review]

**Comment by jgrosseo** [comment]
Great work! Removing the hash task is next then?

**Comment by saganatt** [comment]
First I will check today what is wrong with Filtered and Partitioned, maybe I will find quickly what is the problem.
But in parallel, yes, I already started removing the hash task.

**Pull request merged**
