### PR TITLE
PWGF: Fix pdg codes in femtodream

### PR DESCRIPTION
**Pull request by ariedel-cern**
Use named constants for pdg codes everywhere. Also adds pdg codes for triton and He3 go the get mass functions and removes obsolte functions to select PID.

### CODE REVIEW

**Review by victor-gonzalez — DISMISSED** [review]
@ariedel-cern Thanks!!!

**Comment by victor-gonzalez** [comment]
Don't pay attention to the `linter` error. The code is correct!

**Comment by ariedel-cern** [comment]
Thanks for the info and fast approval, Victor. I saw the discussion on mattermost. I ran cpplint locally and it did not report any errors there so yes, the code should be fine.

**Comment by ariedel-cern** [comment]
Hi @vkucera , thanks for spotting it. I also made the change there.

**Review by victor-gonzalez — APPROVED** [review]

**Pull request merged**
