### PR TITLE
[COMMON] updates on event-plane reconstruction

### PR DESCRIPTION
**Pull request by jikim1290**
updates on ep reco.

### CODE REVIEW

**Comment by jikim1290** [comment]
Please approve this PR if available

**Review by ddobrigk — APPROVED** [review]
thanks!

**Comment by ddobrigk** [comment]
Ah wait - I think I approved too quickly... @jikim1290 , are you sure about this bit: `if (am != 0)` - seems like `am` is a `float` and you are comparing floats without a tolerance (e.g. `1e-8`). _Usually_ this is ok with zero but you should _really_ still add a tolerance whenever comparing floats. Can you please still change that? Also, please check for other occurrences of float comparison without tolerances as there seem to be a few others. Thank you!

**Comment by jikim1290** [comment]
@ddobrigk Thanks for comment, I have added the tolerance.

**Review by ddobrigk — APPROVED** [review]

**Pull request merged**
