### PR TITLE
Move Strangeness Tables to LF, str improvements

### PR DESCRIPTION
**Pull request by ddobrigk**

### CODE REVIEW

**Comment by ddobrigk** [comment]
This PR: 
- moves the StrangenessTables.h file into the PWGLF directory, where they belong (and where the corresponding builders are located). The StrangenessTables.h file has been renamed into LFStrangenessTables.h to match the PWG naming convention. This change triggered a change in many other files that used the Strangeness Tables. 
- fixes a subscription issue in the LambdaKZero labeler that led to crashing of the labeler if activated
- other minor adjustments, etc in strangeness analysis code

**Review by vkucera — APPROVED** [review]

**Review by njacazio — APPROVED** [review]
Good, thanks!

**Review by mpuccio — APPROVED** [review]

**Review by ercolessi — APPROVED** [review]

**Review by jgrosseo — APPROVED** [review]
Looks good.

the file https://github.com/AliceO2Group/AliceO2/blob/dev/scripts/datamodel-doc/inputCard.xml
needs to be adapted to find the new location...

**Review by m-c-danisch — APPROVED** [review]

**Comment by ddobrigk** [comment]
Hi everyone, I think this we may have to force-merge (too many approvers + the change is uncontroversial, I hope!). The error is also not an error, as the logs are empty. Could you please help? Thanks!

**Pull request merged**
