### PR TITLE
PWGHF: Adding some input features to the HfMlResponseDsToKKPi

### PR DESCRIPTION
**Pull request by scattaru**
Dear all,
I've just added some input features (combined PID and impactParameterXY) in the HfMlResponseDsToKKPi to be used for the ML selection.

Best regards,
Samuele

### CODE REVIEW

**Review by fcatalan92 — APPROVED** [review]
Hi @scattaru, LGTM!
There is something strange happening with the MegaLinter checks, basically it is now suggesting to undo the fix proposed before. @vkucera could you have a look?

**Review by fcatalan92 — APPROVED** [review]
Hi @scattaru, I think the check is broken so even if you apply its suggestions it will not go green. It is non blocking for the merge although so we can go ahead.

**Comment by scattaru** [comment]
Hi @fcatalan92, ok perfect. Thanks a lot!

**Comment by vkucera** [comment]
> Hi @scattaru, I think the check is broken so even if you apply its suggestions it will not go green. It is non blocking for the merge although so we can go ahead.

The check is not broken. It is just using a more recent version of clang-format. PR to fix it has been pending.

**Pull request merged**
