### PR TITLE
[PWGUD] Added few more TPC N Sigmas

### PR DESCRIPTION
**Pull request by ananthapadmanabhan18**
Could anyone tell me how to remove the error caused by O2 linter? I will fix it and update it in PR

### CODE REVIEW

**Review by rolavick — COMMENTED** [review]
With the remaining O2 linter you might want to consult with @vkucera . Currently, I do not see it as an obstacle for the merge, so I approve

**Review by rolavick — APPROVED** [review]

**Comment by ananthapadmanabhan18** [comment]
Sure, I will consult with him. Thanks for letting me know!

**Comment by vkucera** [comment]
Hi @ananthapadmanabhan18 , how can I help with the O2 linter errors?

**Comment by ananthapadmanabhan18** [comment]
Hello @vkucera . 90% of the errors in the O2 linter is due to the following error shown in the picture:

image

The problem is...for the data types say `PtEtaPhiVector`, which is the types in standard C++ or O2 replaces these ?

( I have checked the lines in which the error is showing and found out one of them was `PtEtaPhiVector`. There are many others like this only )

**Comment by vkucera** [comment]
> `PtEtaPhiVector`

Those errors are not referring to `PtEtaPhiVector`, they are referring to `Double_t` which should be replace with `double`.

**Comment by vkucera** [comment]
> Hello @vkucera . 90% of the errors in the O2 linter is due to the following error shown in the picture:
> 
> image
> 
> The problem is...for the data types say `PtEtaPhiVector`, which is the types in standard C++ or O2 replaces these ?
> 
> ( I have checked the lines in which the error is showing and found out one of them was `PtEtaPhiVector`. There are many others like this only )

Those errors are not referring to `PtEtaPhiVector`, they are referring to `Double_t` which should be replace with `double`.

**Pull request merged**
