### PR TITLE
Proper event selection for match reco-gen task

### PR DESCRIPTION
**Pull request by victor-gonzalez**

### CODE REVIEW

**Comment by victor-gonzalez** [comment]
@jgrosseo  If I enable the auto merge I get an error in the `approve` CI
```
github.GithubException.BadCredentialsException: 401 {"message": "Bad credentials", "documentation_url": "https://docs.github.com/rest"}
```

**Comment by jgrosseo** [comment]
Can you rebase to master? There was a fix by @TimoWilken this morning, which would then be taken into account. It would be good to see if this fixes the problem.

**Comment by victor-gonzalez** [comment]
I will
Thanks!

**Comment by victor-gonzalez** [comment]
It initially failed with
```
Run actions-ecosystem/action-add-labels@v1
Error: Error: Parameter token or opts.auth is required
Error: Parameter token or opts.auth is required
```
but this seems to not be finally reported

But I was not allowed to merge it

**Comment by victor-gonzalez** [comment]
Strange!
When I check the error and return back it says all checks have passed
But if I refresh the page then I see the `approve` failure

**Comment by victor-gonzalez** [comment]
@jgrosseo It keeps failing after the rebase

**Comment by jgrosseo** [comment]
@TimoWilken Could you check why the auto approve does not work and make a few tests tomorrow?
I merge this for now...

**Review by jgrosseo — APPROVED** [review]

**Pull request merged**
