### PR TITLE
PWGHF: Update XicToXiPiPi tree creator

### PR DESCRIPTION
**Pull request by pstahlhu**
@creetz16 @JaeYoonCHO
- restructure output tables (lite/full)
- Bug fix: correct matching of reconstructed (MC) candidates to generated particles before filling residual table

### CODE REVIEW

**Comment by pstahlhu** [comment]
Hi @vkucera, could you maybe have a look at it? Many thanks in advance!

**Review by mfaggin — APPROVED** [review]
Hi @pstahlhu , good to me. Let me know if you want me to merge it already, or if you prefer Vit to have a closer look since (probably) you discussed together about this fix.

**Comment by pstahlhu** [comment]
Hi @mfaggin, thanks for the feedback! From my side it is ready for merging.
I just pinged Vit because he was involved in all previous PRs regarding the XicToXiPiPi workflow and I discussed with him separately before, but not for these specific changes.

**Comment by mfaggin** [comment]
ok, then let's merge it

**Pull request merged**
