### PR TITLE
Fix histogram names for processRun3

### PR DESCRIPTION
**Pull request by ercolessi**
Hi @ddobrigk, I think the changes of this commit should be propagated also to processRun3 otherwise it crashes https://github.com/AliceO2Group/O2Physics/commit/5ffe363208e4f66044be0852983e13d4dfa13a5f

Is that ok?

### CODE REVIEW

**Comment by njacazio** [comment]
Hi @ddobrigk what should we do?

**Comment by ddobrigk** [comment]
Hi @ercolessi , you're completely correct. However, I think we should use the same filling scheme for both processes (and not just change the names)... Could you please still adjust accordingly? Super thanks!!!

**Comment by ercolessi** [comment]
Hi @ddobrigk you're right, now should be fixed!

**Comment by ddobrigk** [comment]
Thanks a lot @ercolessi ! I think this looks good now!! Nicolo, can you please merge?

**Review by njacazio — APPROVED** [review]

**Pull request merged**
