### PR TITLE
MeanptFluctuation-Task-O2

### PR DESCRIPTION
**Pull request by SwatiSaha-1997**

### CODE REVIEW

**Review by victor-gonzalez — APPROVED** [review]
Please, use `EbyEFluctuations` directory as I mentioned in my e-mail

**Review by victor-gonzalez — CHANGES_REQUESTED** [review]
I approved it by mistake
Please, use `EbyEFluctuations` directory as I mentioned in my e-mail

**Comment by SwatiSaha-1997** [comment]
Hi Victor,
So the structure would be
EbyEFluctuations/Tasks/<mycode> ?
And the directories, EbyEFluctuations/Core, EbyEFluctuations/TableProducers and EbyEFluctuations/Tasks and file EbyEFluctuations/CMakeLists.txt should also be there?

**Comment by SwatiSaha-1997** [comment]
Hi Victor, Changes are updated now.

**Pull request closed without merging**
