### PR TITLE
[PWGCF] Fix compilation warnings

### PR DESCRIPTION
**Pull request by vkucera**

### CODE REVIEW

**Review by victor-gonzalez — APPROVED** [review]

**Comment by victor-gonzalez** [comment]
@vkucera, please, give me some time until I fix the MegaLinter errors

**Review by victor-gonzalez — APPROVED** [review]

**Comment by victor-gonzalez** [comment]
Thanks @vkucera! Ready!
In the process of being merged!

**Comment by vkucera** [comment]
Thanks a lot @victor-gonzalez !

**Comment by victor-gonzalez** [comment]
@vkucera The CI machines seem to be getting exhausted!

**Comment by vkucera** [comment]
@victor-gonzalez The PR should be ready again.

**Review by victor-gonzalez — APPROVED** [review]

**Comment by victor-gonzalez** [comment]
> @victor-gonzalez I hope it's fine now.
Thanks @vkucera!!!

**Pull request merged**
