### PR TITLE
RecoDecay, PWGHF: Add protection for index double-counting

### PR DESCRIPTION
**Pull request by fgrosa**
@jgrosseo @vkucera I noticed that sometimes the indices are overflow (@aalkin told me something similar in a private chat when helping me with the debugging). This causes a segmentation violation (e.g. I debugged downloading locally the same inputs used for this hyperloop train https://alimonitor.cern.ch/train-workdir/tests/0002/00020645/stdout.log). I remember that this could be likely avoided asking for primary particles from a chat with @jgrosseo, but I also think that the method in `RecoDecay.h` should be generic for any usecase (also non primary particles). Let me know if you have different opinions or suggestions for better implementations!

### CODE REVIEW

**Comment by vkucera** [comment]
@jgrosseo Isn't this something that should be fixed directly in the code of `daughtersIds` to return a single daughter when `front == back`?

**Comment by jgrosseo** [comment]
yes, I agree, sure. @aalkin (why) isn't it so?

**Comment by aalkin** [comment]
It should return a slice of size 1, creating a single iteration when using `for(auto& d : daughters)` loop. If that is not the case, there is probably a bug in either slicing or the getter function implementation.

**Comment by fgrosa** [comment]
Hi @vkucera @aalkin @jgrosseo I added a printout of the daughter indices in case of `front == back` in the for loop and I always get two of them as you can see it in the attached log. Isn't this behaviour expected?
[log.txt](https://github.com/AliceO2Group/O2Physics/files/8184343/log.txt)

**Review by vkucera — APPROVED** [review]

**Comment by vkucera** [comment]
@jgrosseo Would you agree to merge this now and follow up on the slicing issue separately?

**Comment by jgrosseo** [comment]
Fine with me.

**Comment by jgrosseo** [comment]
Maybe make a JIRA ticket on the issue...

**Comment by vkucera** [comment]
> Fine with me.

@jgrosseo OK, then can you approve it so that it can be merged?

**Review by jgrosseo — APPROVED** [review]

**Comment by fgrosa** [comment]
> > Fine with me.
> 
> @jgrosseo OK, then can you approve it so that it can be merged?

Thanks a lot! I opened a JIRA, see here: https://alice.its.cern.ch/jira/browse/O2-2828

**Pull request merged**
