### PR TITLE
Error blocking execution on MC trains solved

### PR DESCRIPTION
**Pull request by rosarioturrisi**
Commented out few histo fillings giving error - not deleted for future use

### CODE REVIEW

**Comment by vkucera** [comment]
Please give the PR a proper informative title.

**Comment by mfaggin** [comment]
@rosarioturrisi there is [this](https://github.com/AliceO2Group/O2Physics/pull/6355) pending PR from @ChunzhengLab , not sure if you know.

Since it's older, I'd wait for it, and align the code t his modifications before merging yours

**Comment by rosarioturrisi** [comment]
> Please give the PR a proper informative title.

Hi, hope this helps. Thank you

**Comment by rosarioturrisi** [comment]
@mfaggin fine with me, once it gave an error in the MC part I’ll wait for this pr to submit the MC train. 
Data is ok.
Maybe me and @ChunzhengLab should both work on the same fork to let git do its job? Don’t know if it’s the best solution, though.

**Comment by rosarioturrisi** [comment]
I'll reissue the pr on the updated version.

**Pull request closed without merging**
