### PR TITLE
[Common] PID: Add AO2D metadata handling for pass name in TPC CCDB calls

### PR DESCRIPTION
**Pull request by jezwilkinson**
* Adds lookup from AO2D metadata for pass name when retrieving 
* Add report in log for metadata from retrieved objects (LPMProductionTag and RecoPassName)
* Force neural network CCDB lookup to use same pass name as retrieved Bethe-Bloch parametrisation

### CODE REVIEW

**Comment by jezwilkinson** [comment]
@njacazio @amaringarcia @wiechula FYI

**Comment by njacazio** [comment]
Thanks a lot @jezwilkinson does it allow for override of the metadata info?

**Comment by jezwilkinson** [comment]
> Thanks a lot @jezwilkinson does it allow for override of the metadata info?

Yes, this is handled as before by setting the "recoPass" configurable - if that is set, the AO2D metadata will be ignored: https://github.com/AliceO2Group/O2Physics/blob/34887aa566a5422f28434ef24e4822b2e58b7e6e/Common/TableProducer/PID/pidTPC.cxx#L195-L204

In both cases, if there is no matching upload in the CCDB, it will try to fall back to the latest available BB for the timestamp and throw a warning: https://github.com/AliceO2Group/O2Physics/blob/34887aa566a5422f28434ef24e4822b2e58b7e6e/Common/TableProducer/PID/pidTPC.cxx#L503-L508

**Comment by jezwilkinson** [comment]
@ddobrigk @jgrosseo @ktf @iarsene Can this be merged, please?
Should be seamless for the users, no modifications needed on the core service wagons.

**Comment by njacazio** [comment]
Hi @jezwilkinson @amaringarcia if this is still relevant we can go on

**Comment by jezwilkinson** [comment]
This is still relevant, yes (I've been away for a couple weeks so couldn't respond to the bot closing the PR)

**Comment by jezwilkinson** [comment]
@ddobrigk @jgrosseo @iarsene @ktf @njacazio Coming back to this, can it still be merged? It would be especially useful to have the metadata-based access for the TPC objects now that there are multiple passes available for the 2023 Pb-Pb

**Pull request closed without merging**
