### PR TITLE
[PWGHF] taskFlow.cxx: changes in how multiplicites are obtained.

### PR DESCRIPTION
**Pull request by AlexianL**
I discovered that the previous way I was acquiring multiplicities was wrong.
In this PR I change the way I retrieve multiplicities : 
- collision.numContrib() in the event mixing lambda function
- collision.multNTracksPV() as an estimator in same event 

I also added a new cut on the HF candidates eta.

### CODE REVIEW

**Comment by AlexianL** [comment]
I give up on the O2 linter for now. For the moment it doesn't block the PR merging. I will figure out the right correction locally when I will have updated my O2 build to run O2 linter locally.

**Review by fgrosa — CHANGES_REQUESTED** [review]
Hi @AlexianL I don't think that getting the number of tracks is the best way to estimate the multiplicity, since the total number of tracks includes all tracks (primaries, secondaries, etc) and it is not corrected for detector acceptance (i.e. Zvtx equalization). Is there a reason why you do not use the multiplicity estimators provided centrally?

**Comment by fgrosa** [comment]
> > Hi @AlexianL I don't think that getting the number of tracks is the best way to estimate the multiplicity, since the total number of tracks includes all tracks (primaries, secondaries, etc) and it is not corrected for detector acceptance (i.e. Zvtx equalization). Is there a reason why you do not use the multiplicity estimators provided centrally?
> 
> Hello, I also realized that this is probably not the best method to use recently.
> 
> I unfortunately can't really answer if there is a specific reason this method was used : this was the way it was used when I started carrying the work initiated by my supervisor (I am currently not in contact with my supervisor for reason of newborn child leave, so can't simply ask them), and from the last contact with them discussing multiplicities (around June) they still encouraged me to use this method. The main reason that I see is that it uses event mixing with lambda binning but even this I think no one really use this method for event mixing.
> 
> I think that anyway I will have to switch to a different way of getting multiplicities soon (if there is a generally accepted way to get it from, I would be glad to know it). If possible I would still like to keep this way for the moment and have this PR merged because I think I implemented the "most consistent way" to get multiplicities from this method (even if they are incorrect) and would like to know if it solves some of the obvious problems I have in my produced results until now.

Hi @AlexianL I would suggest you to use the number of PV contributors (`collision.numContr()`) if you need it for the mixed event, and in case you need it as multiplicity estimator, to use the one provided by the multiplicity task (which is equalized for the Zvtx position) https://github.com/AliceO2Group/O2Physics/blob/f14605b7b96480eb84e408c914b5630079a1f6a5/Common/DataModel/Multiplicity.h#L106

**Comment by AlexianL** [comment]
> > > Hi @AlexianL I don't think that getting the number of tracks is the best way to estimate the multiplicity, since the total number of tracks includes all tracks (primaries, secondaries, etc) and it is not corrected for detector acceptance (i.e. Zvtx equalization). Is there a reason why you do not use the multiplicity estimators provided centrally?
> > 
> > 
> > Hello, I also realized that this is probably not the best method to use recently.
> > I unfortunately can't really answer if there is a specific reason this method was used : this was the way it was used when I started carrying the work initiated by my supervisor (I am currently not in contact with my supervisor for reason of newborn child leave, so can't simply ask them), and from the last contact with them discussing multiplicities (around June) they still encouraged me to use this method. The main reason that I see is that it uses event mixing with lambda binning but even this I think no one really use this method for event mixing.
> > I think that anyway I will have to switch to a different way of getting multiplicities soon (if there is a generally accepted way to get it from, I would be glad to know it). If possible I would still like to keep this way for the moment and have this PR merged because I think I implemented the "most consistent way" to get multiplicities from this method (even if they are incorrect) and would like to know if it solves some of the obvious problems I have in my produced results until now.
> 
> Hi @AlexianL I would suggest you to use the number of PV contributors (`collision.numContr()`) if you need it for the mixed event, and in case you need it as multiplicity estimator, to use the one provided by the multiplicity task (which is equalized for the Zvtx position)
> 
> https://github.com/AliceO2Group/O2Physics/blob/f14605b7b96480eb84e408c914b5630079a1f6a5/Common/DataModel/Multiplicity.h#L106

Thank you ! I will start working on implementing multiplicities this way. If I understood well, I can simply change my lambda function to get multiplicity with "collision.numContrib()" to do event mixing and use "collision.multNTracksPV()" to get multiplicity in same event right ?

**Comment by vkucera** [comment]
> I give up on the O2 linter for now. For the moment it doesn't block the PR merging. I will figure out the right correction locally when I will have updated my O2 build to run O2 linter locally.

Not a problem. Just to clarify, do you know what the expected order is or where to find it?

**Comment by AlexianL** [comment]
> > I give up on the O2 linter for now. For the moment it doesn't block the PR merging. I will figure out the right correction locally when I will have updated my O2 build to run O2 linter locally.
> 
> Not a problem. Just to clarify, do you know what the expected order is or where to find it?

Hi, I don't know yet what the expected order is, but I guess it is explained in the HF-specific O2 documentation so I'll check it out for the next PR.

**Comment by vkucera** [comment]
> > > I give up on the O2 linter for now. For the moment it doesn't block the PR merging. I will figure out the right correction locally when I will have updated my O2 build to run O2 linter locally.
> > 
> > 
> > Not a problem. Just to clarify, do you know what the expected order is or where to find it?
> 
> Hi, I don't know yet what the expected order is, but I guess it is explained in the HF-specific O2 documentation so I'll check it out for the next PR.

Very good!

**Comment by fgrosa** [comment]
> > > > Hi @AlexianL I don't think that getting the number of tracks is the best way to estimate the multiplicity, since the total number of tracks includes all tracks (primaries, secondaries, etc) and it is not corrected for detector acceptance (i.e. Zvtx equalization). Is there a reason why you do not use the multiplicity estimators provided centrally?
> > > 
> > > 
> > > Hello, I also realized that this is probably not the best method to use recently.
> > > I unfortunately can't really answer if there is a specific reason this method was used : this was the way it was used when I started carrying the work initiated by my supervisor (I am currently not in contact with my supervisor for reason of newborn child leave, so can't simply ask them), and from the last contact with them discussing multiplicities (around June) they still encouraged me to use this method. The main reason that I see is that it uses event mixing with lambda binning but even this I think no one really use this method for event mixing.
> > > I think that anyway I will have to switch to a different way of getting multiplicities soon (if there is a generally accepted way to get it from, I would be glad to know it). If possible I would still like to keep this way for the moment and have this PR merged because I think I implemented the "most consistent way" to get multiplicities from this method (even if they are incorrect) and would like to know if it solves some of the obvious problems I have in my produced results until now.
> > 
> > 
> > Hi @AlexianL I would suggest you to use the number of PV contributors (`collision.numContr()`) if you need it for the mixed event, and in case you need it as multiplicity estimator, to use the one provided by the multiplicity task (which is equalized for the Zvtx position)
> > https://github.com/AliceO2Group/O2Physics/blob/f14605b7b96480eb84e408c914b5630079a1f6a5/Common/DataModel/Multiplicity.h#L106
> 
> Thank you ! I will start working on implementing multiplicities this way. If I understood well, I can simply change my lambda function to get multiplicity with "collision.numContrib()" to do event mixing and use "collision.multNTracksPV()" to get multiplicity in same event right ?

Yes exactly! For the Zvtx equalised multiplicity (`multNTracksPV`) you will also need to join the collision table with the multiplicity table.

**Review by apalasciano — APPROVED** [review]

**Comment by vkucera** [comment]
@AlexianL Please fix the reported issues.

**Comment by AlexianL** [comment]
> @AlexianL Please fix the reported issues.

Hello, what are the reported issues ? Beside O2 linter which I said I will address in the next PR, I am not sure to know what are the remaining issues.

**Comment by vkucera** [comment]
> > @AlexianL Please fix the reported issues.
> 
> Hello, what are the reported issues ? Beside O2 linter which I said I will address in the next PR, I am not sure to know what are the remaining issues.

@AlexianL I am sorry. I overlooked that this was still the same PR.

**Comment by AlexianL** [comment]
Hello @fgrosa , could you please make the requested changes as "addressed" status ? I think this is preventing auto-merging.

**Review by fgrosa — APPROVED** [review]

**Pull request merged**
