### PR TITLE
Add DCAz histograms

### PR DESCRIPTION
**Pull request by mfaggin**
- `doMC` flag set to `false` by default, to be able to run on data (no `PROCESS_SWITCH` implemented yet)
- DCAz distributions added
- for MC version of the task, propagation toward the MC vertex added (dirty solution)

### CODE REVIEW

**Comment by mfaggin** [comment]
@jgrosseo I inserted the possibility to evaluate also the DCAz component. In addition, I added some other feature for the MC, even if still as "dirty solutions". Nevertheless, we would ask to approve this code to be ready to process the async reconstructed data for the pilot run. The plan is to clean the code and merge it with `PWGPP/Tasks/qaEventTrack.cxx.cxx` in collaboration with @mario-krueger .

**Comment by victor-gonzalez** [comment]
Be aware your code will only run locally and having the proper files in the cwd
I would suggest to implement what is in the latest version of https://github.com/AliceO2Group/O2Physics/pull/187
Otherwise I guess you will not be able to test it in hyperloop

**Comment by mfaggin** [comment]
> Be aware your code will only run locally and having the proper files in the cwd I would suggest to implement what is in the latest version of #187 Otherwise I guess you will not be able to test it in hyperloop
> 
> Ok! I saw you only run on data So you will not have problems for running it on hyperloop Sorry about the noise

Indeed by default I only run on data. No problem at all, thanks for your comment!

**Comment by mfaggin** [comment]
@jgrosseo I have just implemented the possibility to configure the binning and range of the impact parameter axis at runtime, just for flexibility.

**Comment by mfaggin** [comment]
Thanks a lot @mario-krueger , I followed your suggestion. It is implemented in the last commit.

**Comment by mfaggin** [comment]
@jgrosseo do you think it is ok to go on?

**Review by jgrosseo — APPROVED** [review]

**Pull request merged**
