### PR TITLE
[PWGLF] pwglf: table addition and bug fixes

### PR DESCRIPTION
**Pull request by GiorgioAlbertoLucia**
- Added collision id  and z vertex position in multiplicity table for offline event mixing
- Fixed name of the unlike-sign flag in the table
- Fixed a bug in tof selection 
- Fixed a bug to store the correct signed pt of protons in unlike-sign background

### CODE REVIEW

**Review by fmazzasc — DISMISSED** [review]

**Comment by fmazzasc** [comment]
@skundu692 , @njacazio could you approve this?

**Review by njacazio — APPROVED** [review]
looking good

**Comment by GiorgioAlbertoLucia** [comment]
@fmazzasc @njacazio Sorry, I had to add one more column to the table

**Review by njacazio — APPROVED** [review]
No problem

**Pull request merged**
