### PR TITLE
Added ONNXRuntime as dependency

### PR DESCRIPTION
**Pull request by saganatt**
Requires alidist from https://github.com/alisw/alidist/pull/3197

### CODE REVIEW

**Comment by jgrosseo** [comment]
@saganatt Are you sure you wanted to merge this into O2Physics and not O2?

**Comment by saganatt** [comment]
Well, @ktf told me to merge in O2Physics and not O2, I had previously a PR for O2...

For now we use ONNXRuntime only in analysis tasks, so it might actually make sense...?

**Comment by jgrosseo** [comment]
OK, then it is fine. It is just that we will not use O2Physics until end August for tasks. So you cannot yet use it.

**Comment by jgrosseo** [comment]
Is the change in alidist already in? Can you link the PR here?

**Comment by saganatt** [comment]
OK, but the users can still run O2Physics locally?

alidist PR is here: https://github.com/alisw/alidist/pull/3197

**Comment by jgrosseo** [comment]
> 
> 
> OK, but the users can still run O2Physics locally?

Not really. Mid August we will move all tasks from O2 to O2Physics. Until then nothing should be added here (except for testing)

**Comment by saganatt** [comment]
OK, anyways, merging to O2 just for a month neither wouldn't make sense.
So till that time we will manage on my forks, and let's come back to these PRs at the end of August.

**Comment by jgrosseo** [comment]
Sounds good.

As soon as the alidist is merged, we can merge this PR as well. We should just not add the tasks yet.
Can you ping me when alidist is done?

**Comment by saganatt** [comment]
Yes, thanks, cool! That'd already make the task running easier for the others.

**Comment by saganatt** [comment]
> As soon as the alidist is merged, we can merge this PR as well. We should just not add the tasks yet.
> Can you ping me when alidist is done?

Hi @jgrosseo ,
the alidist PR has just been merged.

**Review by ktf — APPROVED** [review]
Fine for tests. (First time contributors are not automatically tested).

**Review by jgrosseo — APPROVED** [review]

**Pull request merged**
