### PR TITLE
[DPG] Adding track and ft0 occupancy in tine range variables to deriv…

### PR DESCRIPTION
**Pull request by amaringarcia**
…e data for TPC PID

### CODE REVIEW

**Review by chiarazampolli — APPROVED** [review]

**Comment by amaringarcia** [comment]
Hi @chiarazampolli @alcaliva , if I understand the error is due to "fatal error: error writing to /tmp/ccrDUjXm.s: No space left on device". Can the test be restarted?

Thanks in advance,
Ana

**Comment by amaringarcia** [comment]
Hi, I think the /tmp directory of whatever computer has to be clean-up. Or?
Should I contact somebody? Or do something from my side?

Thanks in advance.

Regards,
Ana

**Comment by chiarazampolli** [comment]
Hello @ktf , @singiamtel , 

Can you please take a look at the problem here?

Thanks,

Chiara

**Comment by chiarazampolli** [comment]
Thanks @singiamtel !

**Comment by amaringarcia** [comment]
Hi @chiarazampolli ,

now that the checks have passed, can this pull request be merged into the master?
Thanks in advance,
Ana

**Pull request merged**
