### PR TITLE
TOF for PID configurable

### PR DESCRIPTION
**Pull request by alcaliva**

### CODE REVIEW

**Comment by njacazio** [comment]
I'm wondering if we should move this to the QC part

**Review by njacazio — APPROVED** [review]
If, let's do this after PR is merged

**Comment by alcaliva** [comment]
> 

Hi Nicolò,
indeed, this is a good idea. I suggest that we keep it in the LF folder for testing. Once we are happy with the setting and it runs full steam, we can move it to QC. 
What do you think?

**Comment by njacazio** [comment]
Nono I meant, LF QC https://github.com/AliceO2Group/O2Physics/tree/master/PWGLF/Tasks/QC !

**Comment by alcaliva** [comment]
OK. Yes, at the next round, I move it

**Comment by njacazio** [comment]
Top!

**Pull request merged**
