### PR TITLE
PIDTPC: Add possibility to skip TPC only tracks

### PR DESCRIPTION
**Pull request by njacazio**

### CODE REVIEW

**Comment by njacazio** [comment]
After discussion with @ddobrigk it does not make much sense for TOF. However for the TPC it might still play a role @jezwilkinson what do you think of this?

**Comment by ddobrigk** [comment]
Thanks a lot, @njacazio ! If @jezwilkinson agrees, and if offline tests look ok, I would suggest we merge and create a core service wagon that skips tpc-only (and without NN evaluation of PID, which I guess is anyway the default?). It could save quite some CPU, I suppose...

**Comment by njacazio** [comment]
That was my idea, I'm testing it

**Review by ddobrigk — APPROVED** [review]

**Comment by njacazio** [comment]
Tested and ready to merge in agreement with what discussed with @jezwilkinson offline. We should just make sure that the wagon is correctly labelled

**Pull request merged**
