### PR TITLE
PWG-LF-V0 reconstruction

### PR DESCRIPTION
**Pull request by 15071832337**
Dear Experts,
I am a newcomer.I'm sorry to bother you. I'm Youpeng Su. I come from China and major in particle physics in Central China Normal University.My email is youpeng.su@cern.ch.
I want to start my job at PWGLF regarding the  V0(Lambda).My recent research is about spin polarization.According to the tutorial about strangeness particles analysis based O2 Physics,I have written  an analysis to produce V0(Lambda) candidate.
The code contain my analysis such as V0 reconstruction and storing V0(Lambda) candidate in some histograms created by me.
In order to overcome the difficult that I will spend a lot of time to run my analysis locally and to input more and more AO2D file with statistic increasing,I wish that I can submit my code to Hyperloop to share the ALICE computing sources.
I wish the code can be submitted successfully.Thank you for your reply if there is anything to address.
Youpeng Su.

### CODE REVIEW

**Comment by skundu692** [comment]
Dear Youpeng,
You may need to remove the white spaces and fix the clang-format. see the guideline https://github.com/AliceO2Group/CodingGuidelines.
Just to inform you that @jikim1290 is already involved in lambda polarization measurements using Run 3 Pb-Pb data a working version of code is already committed in the Strangeness directory. It might be very useful to have an internal discussion at upcoming strangeness meeting  to discuss your analysis plan in order to see if there is any overlap with @jikim1290 work and code. Will you be available next week for a discussion.

Best regards,
Sourav

**Comment by 15071832337** [comment]
I have just uploaded three code files, two of which have not been modified, and the third has been automatically formatted through the code you sent. Currently,If it doesn't pass, I will consider re-uploading. I am preparing for polarization starting with the experimental data from proton-proton collisions.

**Comment by 15071832337** [comment]
> Dear Youpeng, You may need to remove the white spaces and fix the clang-format. see the guideline https://github.com/AliceO2Group/CodingGuidelines. Just to inform you that @jikim1290 is already involved in lambda polarization measurements using Run 3 Pb-Pb data a working version of code is already committed in the Strangeness directory. It might be very useful to have an internal discussion at upcoming strangeness meeting to discuss your analysis plan in order to see if there is any overlap with @jikim1290 work and code. Will you be available next week for a discussion.
> 
> Best regards, Sourav

**Comment by 15071832337** [comment]
> Dear Youpeng, You may need to remove the white spaces and fix the clang-format. see the guideline https://github.com/AliceO2Group/CodingGuidelines. Just to inform you that @jikim1290 is already involved in lambda polarization measurements using Run 3 Pb-Pb data a working version of code is already committed in the Strangeness directory. It might be very useful to have an internal discussion at upcoming strangeness meeting to discuss your analysis plan in order to see if there is any overlap with @jikim1290 work and code. Will you be available next week for a discussion.
> 
> Best regards, Sourav

Dear Expert,
I have just uploaded three code files, two of which have not been modified, and the third has been automatically formatted through the code you sent. Currently,If it doesn't pass, I will consider re-uploading. I am preparing for polarization starting with the experimental data from proton-proton collisions.
Best regards, Youpeng Su

**Pull request closed without merging**
