### PR TITLE
Per-BC analysis was added

### PR DESCRIPTION
**Pull request by udmitrie**
Per-collision analysis was supplemented by per-BC analysis.  FT0 time, amplitude and multiplicity histograms for BC task were added to HistogramRegistry.

### CODE REVIEW

**Comment by udmitrie** [comment]
Dear @ddobrigk , could you have a look, please?

**Comment by udmitrie** [comment]
Dear @ddobrigk , could you have a look, please?

**Comment by ddobrigk** [comment]
@ktf @pzhristov @TimoWilken I think the CI error is unrelated... I'll approve but then I guess the merge will have to be done by hand

**Review by ddobrigk — APPROVED** [review]

**Comment by TimoWilken** [comment]
Merged. FYI @ddobrigk, since the Intel Mac check isn't marked as "Required", you should still be able to merge as normal, even if it fails!

**Pull request merged**
