### PR TITLE
[EPDev] add occupancy study

### PR DESCRIPTION
**Pull request by jikim1290**
add occupancy study

### CODE REVIEW

**Comment by jikim1290** [comment]
Hi @strogolo @ddobrigk, I don't know why this is so much pending here. Could you please remind me of whatever you think about why this should not be merged? Note that this PR is not affecting anything on the current analyzers as this utilizes already produced tables.

**Comment by dsekihat** [comment]
Dear @jikim1290 , Thank you for preparing this PR. Indeed, this is necessary. I have a minor thing about your occupancy bins. If occupancy is not calculated, the  default value -1. So, it is better to have [-1, 0, XXX]  in your occupancy bins when you submit your wagon.

**Comment by jikim1290** [comment]
HI @dsekihat , Thanks for the comment, it is added

**Comment by jgrosseo** [comment]
@ddobrigk @strogolo I will merge this unless there are objections until noon

**Comment by strogolo** [comment]
@jikim1290 for me this PR is fine if the default is not to use the occupancy cut but it is just used for testing.
If this is the case, then @jgrosseo can approve and merge it.

**Review by jgrosseo — APPROVED** [review]

**Pull request merged**
