### PR TITLE
Fix centrality config and remove POI

### PR DESCRIPTION
**Pull request by ilikmeta**

### CODE REVIEW

**Comment by ilikmeta** [comment]
Hello @victor-gonzalez 
alibuilt showed many errors and I believe from line 446
`  fGFW->Fill(track.eta(), 1, track.phi(), wacc * weff, 1);`
It should be :
`  fGFW->Fill(track.eta(), fPtAxis->FindBin(track.pt()) - 1, track.phi(), wacc * weff, 1);`

However it was compiling locally, but here I did not work.

**Comment by victor-gonzalez** [comment]
You have to fix it locally in your master at your local repository and push your master to the master of your fork in gitHub

**Comment by victor-gonzalez** [comment]
All compiler errors are correct compiler errors according to the current content of the `FlowGFWPbPb.cxx` source code file
Have in mind that you allowed merges in your gitHub fork which you don't have locally

**Comment by ilikmeta** [comment]
Whenever I try to push code with

**Comment by victor-gonzalez** [comment]
From where did you get the latest update on which you are trying to rebase?

**Comment by ilikmeta** [comment]
before I push the code I did: inside O2Physis
git pull --rebase upstream master

**Comment by victor-gonzalez** [comment]
But that did not fail because you were able to push for creating the pull request, right?

**Comment by ilikmeta** [comment]
Once I pushed the new changes for the first time, then there was a conflicing file that appeared below the checks which was showing the latest changes I did to my code. By opening the conflicting file, the FlowGFWPbPb.cxx , I removed the lines that I had deleted before I push and then I clicked on the Resolved button and merge. Then alibuilt returned with errors and now I cannot even do a hard reset:
`iris_antreas_likmeta@Iris-Antreass-MacBook-Pro O2Physics % git checkout master
git fetch --all
git reset --hard upstream/master

PWGCF/Flow/Tasks/FlowGFWPbPb.cxx: needs merge
error: you need to resolve your current index first
Fetching upstream
Fetching origin
HEAD is now at 1f2f492c Introducing a new util to get the OTS bits (ZORRO) (#6087)
`

**Comment by ilikmeta** [comment]
@victor-gonzalez Is it possible to discard this pull request and make a new one as now the git status is up to date?

**Comment by victor-gonzalez** [comment]
Two questions before
- what `git remote -v` gives you 
- what you said here
> By opening the conflicting file, the FlowGFWPbPb.cxx , I removed the lines that I had deleted before I push and then I clicked on the Resolved button and merge. 

means you did the changes directly on gitHub?

If that is the case you should never do that unless they are really minor changes, i.e. the ones suggested by the formatter

**Comment by ilikmeta** [comment]
iris_antreas_likmeta@Iris-Antreass-MacBook-Pro O2Physics % git remote -v
origin	git@github.com:ilikmeta/O2Physics.git (fetch)
origin	git@github.com:ilikmeta/O2Physics.git (push)
upstream	https://github.com/AliceO2Group/O2Physics (fetch)
upstream	https://github.com/AliceO2Group/O2Physics (push)

Yes, I did changes on GitHub as I thought I will not let the checks to be done. Thanks for mentioning to avoid this!

I just pushed again after fixing my local repo. So far no errors occured. 

My appologies for giving hard time with this.

**Comment by victor-gonzalez** [comment]
No problem!
But as a strict rule, one has to be always completely sure that what is in the PR compiles locally first
If the content of the PR is changed on gitHub that rule is broken

**Review by victor-gonzalez — APPROVED** [review]

**Pull request merged**
