### PR TITLE
Calo Tender implemented

### PR DESCRIPTION
**Pull request by peressounko**
First implementation of Run2  PHOS Tender and EMCAL AnalysisFramework.
Table CaloCluster to be discussed/agreed with EMCAL and probably replace table PWGJE/DataModel/EMCALClusters.h

### CODE REVIEW

**Comment by peressounko** [comment]
Dear @mfasDa, @raymondEhlers 
please have a look at class CaloClusters.h and caloClusterProducer.cxx. I think we should develop common table for PHOS and EMCAL. Also it would be nice to have one producer class.
      Best regards, Dmitri

**Comment by iarsene** [comment]
@mfasDa , @raymondEhlers 
I will wait for your go ahead on this.

**Comment by mfasDa** [comment]
Adding @fjonasALICE who takes over responsibility over the emcal-correction-task from Raymond. For dynamic SOA we can probably agree on a common table for EMCAL and PHOS, this has worked for run2, we need to agree here that the relevant information is available for both detectors. For the producer I am not so convinced, the correction framework was done on purpose, there is a chain of corrections applied for EMCAL (clusterization, non-lin- correction, exotics rejection, hadronic correction), which to some extend requires different customisations for different objects (i.e. stronger E-cuts for photons and electrons vs. jets but no hadronic correction), so I think we might want to keep the correction framework.

**Comment by peressounko** [comment]
Dear @mfasDa, all. I propose to implement minimal bricks: clusterization (can be common for PHOS and EMCAL)  in caloClusterProducer, track matching (not implemented yet, but also can be common) and configurable corrections suitable for analysis (has to be separate). All elementary bricks can be combined by some envelope class to minimize customization for final user.  Best regards, Dmitri

**Comment by mfasDa** [comment]
This structure we had in the early version of the correction chain, the chain was very complicated to configure, macros with a lot of free parameters (more than 20), in order to allow for studies to tweak parameters. This setup turned out to be very complicated and error-prone for the users. Therefore decided for the new implementation of the correction task with one task to rule all components, and configuration based on a modern markup language that allows us to provide a default configuration and the user just to change the params that actually need to be changed. This improved the stability a lot. I am not in favour of going back to the old approach.

**Comment by peressounko** [comment]
Dear @mfasDa, I do not see any contradiction between small classes dedicated to specific tasks which finally will be hidden in one user-available task with default full framework and list of default parameters - as you described. 
Let us then concentrate on common CaloCluster table: do we have all necessary fields implemented? Can we use current design as starting point, see how suitable it will be in real analysis and add missing fields later if necessary?

**Comment by peressounko** [comment]
Dear  @fjonasALICE, @mfasDa, do you have any comment on proposed table? If not, can approve design as is and commit changes?

**Comment by peressounko** [comment]
Dear @iarsene, @mfasDa, @raymondEhlers, I think we can commit draft as is and return to discussion if EMCAL will want to change something.

**Comment by mfasDa** [comment]
As this is not a persistent structure it should be find to merge, however for EMCAL will probably add a couple of fields.

**Comment by peressounko** [comment]
@mfasDa , adding fields is completely fine. Removing/renaming will cause modification of dependencies. Hope, give naming is acceptable for you.

**Review by iarsene — APPROVED** [review]

**Pull request merged**
