### PR TITLE
PWGHF: B+ Tree Creator

### PR DESCRIPTION
**Pull request by apalasciano**
B+ Tree Creator

### CODE REVIEW

**Comment by vkucera** [comment]
Hi @apalasciano , sorry for coming to your PR late. Can you please first resolve the conflicts? I will then have a look.

**Comment by fcolamar** [comment]
Hello Antonio, please note that you should move to the McParticles_000 table instead of McParticles, see how this modification is implemented in this very recent commit by Jan Fiete:
https://github.com/AliceO2Group/O2Physics/commit/43709316d98269bda8841bbd36a3bbe7ea39758e
Cheers,
Fabio

**Comment by apalasciano** [comment]
I implemented the provided comments (@vkucera )
Is it possible to have a review of this PR?
It would be usefull for ALICE 3 predictions (and actually it's a bit urgent)

**Comment by fcolamar** [comment]
Hi @vkucera, I see that the modification you asked have been implemented. I'm not directly approving the PR since you might have further comments, but this is now urgent since is blocking some ALICE3 studies for the LoI, could you have a look whethere it's ok for you as well?
Thanks, Fabio

**Review by vkucera — APPROVED** [review]

**Review by vkucera — APPROVED** [review]

**Pull request merged**
