### PR TITLE
[PWGJE] EP resolution+histograms

### PR DESCRIPTION
**Pull request by joachimckh**
Added histograms for calculating event plane resolution using 3-sub events for several detectors.

### CODE REVIEW

**Comment by joachimckh** [comment]
@nzardosh can you approve this? Thank you!

**Comment by nzardosh** [comment]
Hi Joachim,

Could you please fix your megalinter error? I will then approve
Thanks,
Nima

**Comment by joachimckh** [comment]
Hi @nzardosh,

I am not sure what is actually complains about. I think there was an issue last week with it, so it might not be my code. Maybe @vkucera knows, since I saw him comment on some of it.

Cheers,
Joachim

**Comment by vkucera** [comment]
> Hi @nzardosh,
> 
> I am not sure what is actually complains about. I think there was an issue last week with it, so it might not be my code. Maybe @vkucera knows, since I saw him comment on some of it.
> 
> Cheers, Joachim

The `checkov` error is unrelated and already fixed in upstream. It still occurs in this PR because the source branch is not up to date.

**Review by nzardosh — APPROVED** [review]

**Pull request merged**
