### PR TITLE
Code reduction/refactoring: Use existing utility to fetch SOR-EOR

### PR DESCRIPTION
**Pull request by sawenzel**
Queries to RCT/../RunInformation to fetch SOR and EOR are replaced by a call to a existing (static) utility function in O2.

Benefits:
* code reduction / less boilerplate
* harmonization of queries to CCDB (which where not consistent ... sometimes with additional timestamp ... sometimes not)

### CODE REVIEW

**Comment by sawenzel** [comment]
PR proposed after discussion with Costin in the effort to harmonize (and reduce) calls to CCDB concerning RunInformation.

**Review by ekryshen — DISMISSED** [review]
Thanks, looks good for evsel-related changes.

**Comment by sawenzel** [comment]
The complaints from megalinter have nothing to do with this PR.

**Review by njacazio — DISMISSED** [review]

**Comment by costing** [comment]
Ping on this ticket, could it be merged please?

**Review by rolavick — APPROVED** [review]

**Pull request merged**
