### PR TITLE
PWGHF: Fix the error of using a wrong table in MCRec for Ds-h correlations

### PR DESCRIPTION
**Pull request by scattaru**
Dear all, 
I have found out an error regarding the table used to run over the candidates in MCRec process of the correlatorDsHadrons. Before I selected all Ds with a flagDs = 1, 5 or 7; now I use a table where the Ds selected are all with a flagDs = 7.

Samuele

### CODE REVIEW

**Review by fcolamar — DISMISSED** [review]

**Comment by scattaru** [comment]
Could you please let this pull request open until tomorrow? I have found some bugs in the execution of MC processes, so I can fix them.

Thanks in advance,
Samuele

**Comment by vkucera** [comment]
> Could you please let this pull request open until tomorrow? I have found some bugs in the execution of MC processes, so I can fix them.
> 
> Thanks in advance, Samuele

I converted your PR into a draft. Please use this option whenever you need more time to work on your PR.

**Comment by scattaru** [comment]
> > Could you please let this pull request open until tomorrow? I have found some bugs in the execution of MC processes, so I can fix them.
> > Thanks in advance, Samuele
> 
> I converted your PR into a draft. Please use this option whenever you need more time to work on your PR.

Ok, thanks @vkucera.

**Comment by scattaru** [comment]
Dear all,
Just a comment on what I've done:
- I've removed the table I've declared to select collisions with Ds in order to use the general table for the same purpose declared for all D mesons;
- I've introduce another processMc for calculating the efficiencies of reconstruction of Ds mesons and particles associated;
- I've corrected some small errors in the code.

Waiting for your feedback,
Best regards,
Samuele

**Review by mmazzilli — APPROVED** [review]

**Review by vkucera — APPROVED** [review]

**Pull request merged**
