### PR TITLE
[Common,PWGJE] Add getParticleOrigin and modified init problem

### PR DESCRIPTION
**Pull request by hanseopark**
To use jet-flavour definition from jet group

Modification of problem about initialize for track and particle

### CODE REVIEW

**Comment by hanseopark** [comment]
@hahassan7 @vkucera @fgrosa
A review would be appreciated

**Comment by nzardosh** [comment]
Hi Hanseo,

Why is this better to be added here rather than to recodecay?

Thanks,
Nima

**Comment by hanseopark** [comment]
Hi @nzardosh 
If we use searchUpToQuark==false, recodecay function have to return prompt and non-prompt only, not none
I should have implemented for tagging

**Comment by nzardosh** [comment]
Hi Hanseo, but my quesion is cant we modify reco decay instead?

**Comment by hanseopark** [comment]
Hi Nima @nzardosh
This function is currently under development because quark level doesn't work well, and `getCharmHadronOrigin` is a function developed specifically for Charm hadrons (at hardron level). Modification the recodecay function might solve it for now, but I'm thinking that updating the quark level part might change the code a lot in the process.

**Comment by hanseopark** [comment]
@vkucera @nzardosh 
I move to the function of `getParticleOrigin`() on `RecoDecay.h`

**Pull request merged**
