### PR TITLE
Update QA tasks

### PR DESCRIPTION
**Pull request by njacazio**
- Update A3 mult task
  - Add MinContrib cut

- Update efficiency task
  - Add multiplicity in efficiency task
  - Add track length to efficiency task

### CODE REVIEW

**Review by jgrosseo — APPROVED** [review]

**Review by iarsene — APPROVED** [review]

**Comment by njacazio** [comment]
Do we really need more than two approvals?

**Comment by ktf** [comment]
I think you need one for PWGPP and one for ALICE3.

**Review by vkucera — APPROVED** [review]

**Comment by ktf** [comment]
I checked. PWGPP does not have an entry in CODEOWNERS, so that's why Core is involved.

**Comment by njacazio** [comment]
Thanks Giulio! I will add PWGPP CODEOWNERS then

**Comment by jgrosseo** [comment]
Why wasn't my approval for Core enough?

**Comment by jgrosseo** [comment]
I think the one from ALICE3 was missing (mine was OK for core)

**Comment by jgrosseo** [comment]
The point is that one cannot approve oneself. This is rather annoying (not only for us), and does not seem to have a solution:
https://github.community/t/do-not-require-owner-approval-if-the-pull-request-is-from-an-owner/369/66

We may need an external tool then like we have for AliPhysics...

**Comment by njacazio** [comment]
Ok indeed you are right, this would not help

**Pull request merged**
