### PR TITLE
PWGHF: taskFlow.cxx: Add mixed-event process function for h-MFT

### PR DESCRIPTION
**Pull request by AlexianL**
Few minor changes too : change of the default axisMass binning, typo correction, re-organization of the AnalysisResults root file, renaming of "MyCollisions" and "MyTracks" by more comprehensive names.

### CODE REVIEW

**Comment by fgrosa** [comment]
@NicoleBastid @mmazzilli @deepathoms could you please have a look? Thanks!

**Review by mmazzilli — COMMENTED** [review]
The PR is fine with me. My only suggestion is to use a better naming wrt "MyCollisions" and "MyTracks"

**Comment by Katka19** [comment]
Hi Marianna, thanks a lot for checking the PR. I see that the change to "MyCollisions" was done in this HF-wide PR: https://github.com/AliceO2Group/O2Physics/pull/3454 . So maybe this is how it should be? I don't have a strong preference, so I can check how the naming should be and we can change it if needed.

**Comment by vkucera** [comment]
> Hi Marianna, thanks a lot for checking the PR. I see that the change to "MyCollisions" was done in this HF-wide PR: #3454 . So maybe this is how it should be? I don't have a strong preference, so I can check how the naming should be and we can change it if needed.

How about `FilteredCollisionsWSelMult`, `TracksWDcaSel`?

**Comment by mmazzilli** [comment]
> Hi Marianna, thanks a lot for checking the PR. I see that the change to "MyCollisions" was done in this HF-wide PR: #3454 . So maybe this is how it should be? I don't have a strong preference, so I can check how the naming should be and we can change it if needed.

Hi Katarina, 
indeed this was not something introduced with this PR but it was a good occasion to take care of it. Thanks to @vkucera for the suggestion and to @AlexianL for the implementation. As soon as the MegaLinter issue is solved, I will approve the PR.

**Review by mmazzilli — APPROVED** [review]

**Pull request merged**
