### PR TITLE
PWGLF: Fix autodetect in strangeness builders

### PR DESCRIPTION
**Pull request by rspijkers**
Look for Casc/V0 Indices tables instead of Datas tables

### CODE REVIEW

**Comment by ddobrigk** [comment]
Thanks a lot @rspijkers for catching this! However, I think the subscription that the autodetect should look for is the `V0Cores` and `[]CascCores` tables. It's entirely possible to analyse without subscribing to the `Indices` but not possible to analyse without subscribing to the `Cores`... Can you please adjust? Many many thanks!! :-D

**Comment by rspijkers** [comment]
Hi @ddobrigk , done! Would it make sense to add some extra logic to the V0-builder autodetect in case one is looking at cascades? Instead of trying to match settings with the cascade-builder (which doesn't make much sense), one can look at the process that subscribes to the cascades and scan that for any V0 settings.

**Comment by ddobrigk** [comment]
@rspijkers thank you very very much! :-D

**Review by njacazio — APPROVED** [review]
Thanks!

**Pull request merged**
