### PR TITLE
Update Run3 track selection

### PR DESCRIPTION
**Pull request by njacazio**
@mario-krueger I think this should be needed to ask for real global tracks, what do you think?

### CODE REVIEW

**Comment by mario-krueger** [comment]
good point, thanks!

**Review by mario-krueger — APPROVED** [review]

**Comment by njacazio** [comment]
Hi @mario-krueger thanks, I mark it as ready for review

**Comment by mario-krueger** [comment]
On second thought I would suspect however, that it does not change anything for the globalTrack selection, since there are other conditions which require hits in the ITS and clusters in the TPC.

**Comment by njacazio** [comment]
I see. We need to investigate this issue as it seems that we get tracks that pass the global requirement that are ITS only so this triggered the change. I'm on it but probably there is no harm in merging this already

**Comment by jgrosseo** [comment]
Isn't it misleading that this bypasses then the setting `mRequireTPC(ITS)Refit`?

**Comment by njacazio** [comment]
@jgrosseo you are indeed right, I was hasty

**Review by jgrosseo — APPROVED** [review]

**Pull request merged**
