### PR TITLE
Labels hadling added; track matching and MCLabels made joinable

### PR DESCRIPTION
**Pull request by peressounko**

### CODE REVIEW

**Comment by peressounko** [comment]
Dear @aalkin, 
here is code which produces errors like 
[8890:calo-cluster-producer-task]: [21:52:33][ERROR] Dropping incomplete AOD/CALO/0 Lifetime::0 data in slot 0 with timestamp 0 < 1 as it can never be completed.
[8890:calo-cluster-producer-task]: [21:52:33][ERROR] Dropping incomplete AOD/CALOTRIGGER/0 Lifetime::0 data in slot 0 with timestamp 0 < 1 as it can never be completed.
[8890:calo-cluster-producer-task]: [21:52:33][ERROR] Dropping incomplete AOD/COLLISION/1 Lifetime::0 data in slot 0 with timestamp 0 < 1 as it can never be completed.
[8890:calo-cluster-producer-task]: [21:52:33][ERROR] Dropping incomplete AOD/CPVCLUSTER/0 Lifetime::0 data in slot 0 with timestamp 0 < 1 as it can never be completed.
[8890:calo-cluster-producer-task]: [21:52:33][ERROR] Dropping incomplete AOD/BC/0 Lifetime::0 data in slot 0 with timestamp 0 < 1 as it can never be completed.
[8890:calo-cluster-producer-task]: [21:52:33][ERROR] Dropping incomplete AOD/TIMESTAMPS/0 Lifetime::0 data in slot 0 with timestamp 0 < 1 as it can never be completed.

To reproduce error, please use O2sim with filling CaloLabels (https://github.com/AliceO2Group/AliceO2/pull/11399)
and run script https://cernbox.cern.ch/s/KxiQSyuOTbWmDqR  or use directly AO2D file: https://cernbox.cern.ch/s/rwRqC6nbyfMPx7I
Thanks, Dmitri

**Comment by peressounko** [comment]
In commit  d1a5cb8  an access to mcParticles in caloClusterProducer is removed, only sorting of labels left, as Anton suggested. However, Dropping incomplete AOD/* and Segmentation fault persist. @nburmaso , could you please have a look if AO2D creation is correct?
   Dmitri

**Comment by nburmaso** [comment]
Dear @peressounko, I am checking the AO2D producer and will let you know if I have a solution asap

**Comment by nburmaso** [comment]
Dear @peressounko,

I have built the latest O2 and O2Physics with changes from this PR and tested both AOD creation and your workflow (calo-cluster-producer-task).

- Your AOD produced with `runMC.sh` seems ok to me. Your test workflow finished successfully, and the error did not occur (see test.sh in [1]). I suspect that this AOD doesn't have any tracks and collisions because you used boxgen with photons in PHOS acceptance...

- I also produced AOD from simulation of 100 pp collisions (see sim_challenge.sh and also the AOD file in [1], a bit modified macro from O2). This AOD seems to be fine, contains all the tables and works with your test workflow.

Could you please check if the problem persists with Pythia simulated events? Is it possible that there is an issue with your O2 installation?

[1] folder with test files -- https://cernbox.cern.ch/s/tNO2RuObJ9HCAdc

**Pull request closed without merging**
