### PR TITLE
[EMCAL-670] Add cluster nonlinearity and shaper saturation correction

### PR DESCRIPTION
**Pull request by mfasDa**
- Correction for nonlinearity based on
  NonlinearityHandler
- Nonlinearity function selectable
- Energy corrected for nonlinearity as additional
  column in cluster table

### CODE REVIEW

**Comment by mfasDa** [comment]
Needs https://github.com/AliceO2Group/AliceO2/pull/10845

**Comment by mfasDa** [comment]
@fjonasALICE @jokonig @mhemmer-cern for reference

Shall we use the default energy column for the energy corrected for the nonlinearity? We should keep in mind that we should make the code also easy to use, and most users will care about the corrected energy. The uncorrected energy should be there as core energy in any case.

**Comment by fjonasALICE** [comment]
i would use calibrated energy as default and make uncorrected energy available in a different field. Also, correct nonlin should be automatically applied by default without needing to specify in the configuration of the CF

**Comment by mfasDa** [comment]
@fjonasALICE I also think the default should be the corrected energy. I have changed the pull request accordingly.

For what concerns the selection of the function: I agree with you that it should be automatised. For the first iteration however I would like to keep the Configurable, and we care about this it further iterations.

**Review by nzardosh — APPROVED** [review]

**Comment by mfasDa** [comment]
Retrigger CI after update of O2 version in the o2 CI.

**Review by nzardosh — APPROVED** [review]

**Pull request merged**
