### PR TITLE
PWGHF: Dplus-hadron pair tables added

### PR DESCRIPTION
**Pull request by Simple-Shyam**
Dplus-hadron pairs table added for Dplus-hadron correlation task.
I will also add the correlation task soon.

### CODE REVIEW

**Review by Simple-Shyam — COMMENTED** [review]
PWGHF: Dplus-hadron correlation tasks are committed.

**Review by fcolamar — CHANGES_REQUESTED** [review]
.

**Review by fcolamar — APPROVED** [review]

**Comment by fcolamar** [comment]
Hi Shyam, you should rename your Y method to y, and check also the other renamings done in RecoDecay.h with PR https://github.com/AliceO2Group/O2Physics/pull/872.
I assume that in your local tests you used a not up-do-date version of the software, and in particular of RecoDecay.h

**Comment by Simple-Shyam** [comment]
> Hi Shyam, you should rename your Y method to y, and check also the other renamings done in RecoDecay.h with PR #872. I assume that in your local tests you used a not up-do-date version of the software, and in particular of RecoDecay.h

Ciao Fabio, Yes, I will fix it and commit again after update of software.

**Review by Simple-Shyam — COMMENTED** [review]
Fixed for the compilation in recent version of software.

**Review by fcolamar — APPROVED** [review]

**Pull request merged**
