### PR TITLE
Use C++20 concepts to determine which Centrality to return

### PR DESCRIPTION
**Pull request by ktf**
Avoid recursive lookup in the schema while doing so.

### CODE REVIEW

**Comment by ktf** [comment]
No rush, I just wanted it as an example of a good practice C++20 usage.

**Comment by victor-gonzalez** [comment]
In the queue to be tested

**Review by victor-gonzalez — APPROVED** [review]
Thanks @ktf ! This works great! And it is really clean!
I only have rights on the PWGCF part
But I can fix the linter errors in `Centrality.h` if so you want
Just let me know

**Comment by jgrosseo** [comment]
@ktf can you fix the clang error?
If it is fine for @victor-gonzalez , we can merge it then.

**Comment by ktf** [comment]
I think my code is correct, actually. The issue is that cpplint / clang-format does not seem to understand requires. Is it ok if I bump them?

**Comment by jgrosseo** [comment]
> I think my code is correct, actually. The issue is that cpplint / clang-format does not seem to understand requires. Is it ok if I bump them?

This is in O2. I am not the right person to answer...

**Comment by ktf** [comment]
It's actually the tests of O2Physics which I need to touch.

**Comment by jgrosseo** [comment]
Yes, true. Sorry for overlooking this. I don't mind.  @vkucera ?

**Comment by vkucera** [comment]
I fully support bumping `clang-format`, although one has to be careful about potential discrepancies in the config file `.clang-format` that we currently use in many `AliceO2Group` repositories, because some parameters might have changed.

For `cpplint`, the version is picked up by MegaLinter and I'm not sure that one can require a specific version.

@ktf do you know which version of each we need to support the concepts?

**Comment by ktf** [comment]
clang-format was bumped to use version 18.
cpplint needs to be bumped to a new version. As it is now, it's simply not working correctly.

Merging.

**Comment by vkucera** [comment]
> clang-format was bumped to use version 18. cpplint needs to be bumped to a new version. As it is now, it's simply not working correctly.
> 
> Merging.

Thanks @ktf

**Comment by ktf** [comment]
(I should mention the working version of cpplint does not yet exist)

**Pull request merged**
