### PR TITLE
PHOS analysis bug fixes

### PR DESCRIPTION
**Pull request by peressounko**

### CODE REVIEW

**Comment by peressounko** [comment]
Dear @mikesas, could you approve this PR, this time should work. Thanks, Dmitri

**Comment by peressounko** [comment]
MegaLinter errors are not related to commit

**Comment by peressounko** [comment]
These tasks for QC and calibration, not directly related to meson analysis

**Review by mikesas — APPROVED** [review]

**Comment by peressounko** [comment]
Hi @mikesas , still investigating this system. In O2 Ruben is able to merge commits even if some tests failed due to unrelated reasons. Here it is better to have all tests OK. And naturally your approval did not survive new commit. Could you approve once more? Thanks, Dmitri

**Comment by peressounko** [comment]
hi @mikesas , could you approve once more?

**Review by mikesas — APPROVED** [review]

**Pull request merged**
