### PR TITLE
[Event plane] add vectors columns for multiple event planes

### PR DESCRIPTION
**Pull request by jikim1290**
add vectors columns for multiple event planes
Q-vector from TPC full tracks

### CODE REVIEW

**Comment by strogolo** [comment]
Dear @jikim1290,
is this PR following the presentation we had at the last AOT meeting? If so, have you tested the performance of the new task as agreed at the meeting before opening this PR? We didn't receive any update on this point which was important.
Please inform us as soon as possible and if you have done the test report on it.
Regards,
Stefano

**Review by ddobrigk — APPROVED** [review]

**Comment by jikim1290** [comment]
@strogolo This PR is what we discussed in the previous AOT meeting and I locally tested this. I was thinking these proposals were accepted in the meeting if I remember correctly.

**Comment by ddobrigk** [comment]
@jikim1290 please clarify @strogolo's point before doing the (auto-)merge. Thanks!

**Comment by strogolo** [comment]
@jikim1290 yes the modification was fine but we agreed on having a test and a report of this test. We need to be sure that what you are asking to include in this code is not creating troubles or reducing the performances of other analysers, that's why asked you a test on a reasonable sample and report on the performance.

**Comment by jikim1290** [comment]
@strogolo Do you want me to close this first and come back with local test results? I can run the task for 5k events in my local

**Comment by strogolo** [comment]
@jikim1290 there is no need to close the PR, you can move it to "draft mode", do the test and once we see that the test is satisfactory we can agree to move it back for approval.

**Comment by jikim1290** [comment]
@strogolo The results and CPU usage obtained from the local test was shared with you so could you please approve this?

**Review by ddobrigk — APPROVED** [review]

**Pull request merged**
