### PR TITLE
PWGHF: optimise HF combinatorial

### PR DESCRIPTION
**Pull request by fgrosa**
This PR implements the proper filters and partitions in order to speedup the HF combinatorial (especially when multiple channels are enabled).

Still to be tested, please do not merge yet.

### CODE REVIEW

**Comment by fgrosa** [comment]
The MegaLinter error seems to be unrelated to this PR (it complains about the position of headers in `Common/TableProducer/ft0CorrectedTable.cxx`

**Comment by vkucera** [comment]
> The MegaLinter error seems to be unrelated to this PR (it complains about the position of headers in `Common/TableProducer/ft0CorrectedTable.cxx`

I'm suspecting that for some reason the MegaLinter workflow is now checking all files that differ between the source and the target branch. If you update your branch, the error should disappear.

**Comment by fgrosa** [comment]
By factorising the loops on the third track for 3-prong and D* candidates, I obtain a speedup factor of at least 3 in Pb-Pb (it also depends on the selections). The results obtained are the same before and after this optimisation.
It is now ready for review and it would be great to merge it asap, since it is needed for the production of derived data in Pb-Pb collisions.

**Comment by fgrosa** [comment]
> > The MegaLinter error seems to be unrelated to this PR (it complains about the position of headers in `Common/TableProducer/ft0CorrectedTable.cxx`
> 
> I'm suspecting that for some reason the MegaLinter workflow is now checking all files that differ between the source and the target branch. If you update your branch, the error should disappear.

It is now fixed now indeed, thanks!

**Review by mfaggin — APPROVED** [review]
thanks @fgrosa , all clear to me

**Pull request merged**
