### PR TITLE
Added col-vs-ft0 for colisions with TRD

### PR DESCRIPTION
**Pull request by ekryshen**
* col-vs-ft0 bc diff analysis for colisions with TRD
* track-vs-ft0 bc diff for ITSTPC-only tracks

### CODE REVIEW

**Comment by ekryshen** [comment]
Please, merge. The error(warning) seems to be unrelated to this PR:

In file included from /Volumes/build/build/nomad/alloc/e878e5ed-79d8-9b56-47fb-dbca0326b3e4/ci/local/o2physics/sw/SOURCES/O2Physics/1279/0/Tools/PIDML/simpleApplyPidOnnxModel.cxx:22:
/Volumes/build/build/nomad/alloc/e878e5ed-79d8-9b56-47fb-dbca0326b3e4/ci/local/o2physics/sw/SOURCES/O2Physics/1279/0/Tools/PIDML/pidOnnxModel.h:249:7: error: private field 'mPid' is not used [-Werror,-Wunused-private-field]
  int mPid;

**Review by jgrosseo — APPROVED** [review]

**Comment by jgrosseo** [comment]
@saganatt Could you check the error in the macOS build (or is it of someone else?)

**Comment by saganatt** [comment]
@jgrosseo indeed, it is mine. I will fix it.

**Comment by saganatt** [comment]
It came here: https://github.com/AliceO2Group/O2Physics/pull/1273, good question how then all checks passed in that PR

**Pull request merged**
