### PR TITLE
PWGHF: Lc task: Remove the redundant Configurable and keep using the Filter

### PR DESCRIPTION
**Pull request by zhangbiao-phy**
-  remove the redundant Configurable "applyML" 
-  replace the "Partition" with "Filter"
- Fixes https://github.com/AliceO2Group/O2Physics/pull/5040

### CODE REVIEW

**Review by mfaggin — DISMISSED** [review]

**Comment by zhangbiao-phy** [comment]
Hi @vkucera @DelloStritto, this is the new PR based on the previous comments. I keep using the Filter since there is no need to use Partition in the Lc task for the moment.

**Review by vkucera — CHANGES_REQUESTED** [review]

**Comment by vkucera** [comment]
Thanks @zhangbiao-phy , did you test the changes locally and can you confirm that you are getting the same results now as before https://github.com/AliceO2Group/O2Physics/pull/5040 ?

**Comment by zhangbiao-phy** [comment]
> Thanks @zhangbiao-phy , did you test the changes locally and can you confirm that you are getting the same results now as before #5040 ?
@vkucera, yes, I have done the test. I have many more candidates from the #5040 w.r.t the keep using the "Filter". Then the candidates look reasonable now. Thanks for spotting this issue!

**Comment by vkucera** [comment]
> > Thanks @zhangbiao-phy , did you test the changes locally and can you confirm that you are getting the same results now as before #5040 ?
> > @vkucera, yes, I have done the test. I have many more candidates from the #5040 w.r.t the keep using the "Filter". Then the candidates look reasonable now. Thanks for spotting this issue!

Thanks @zhangbiao-phy for checking. However, this is not what I asked. Sorry if I was not clear. I want you to compare the histograms produced with your PR branch and histograms produced by master before https://github.com/AliceO2Group/O2Physics/pull/5040 was merged.

**Review by vkucera — APPROVED** [review]

**Pull request merged**
