### PR TITLE
PWGEM: Fix compilation warnings: unused-parameter

### PR DESCRIPTION
**Pull request by vkucera**

### CODE REVIEW

**Review by mhemmer-cern — DISMISSED** [review]
looks good from photon side

**Review by ivorobye — DISMISSED** [review]

**Comment by vkucera** [comment]
Thanks @mhemmer-cern @ivorobye . Sorry, I need to resolve conflicts still.

**Comment by vkucera** [comment]
Ready

**Review by ivorobye — APPROVED** [review]

**Comment by mhemmer-cern** [comment]
@vkucera MegaLinter is still complaining, should we wait?

**Comment by vkucera** [comment]
@mhemmer-cern The errors reported by MegaLinter are not related to this PR and they were there before. It is not the purpose of this PR to fix them. But they are so trivial that I'm happy to fix them if you prefer. Let me know.

**Review by feisenhu — APPROVED** [review]

**Pull request merged**
