### PR TITLE
Add workflow for MFT-MCH matching by machine learning

### PR DESCRIPTION
**Pull request by motomioya**

### CODE REVIEW

**Comment by iarsene** [comment]
Hi @motomioya, I suggest to change the name of the data model file. Start with a capital letter as the other files in the DataModel directory.

**Review by iarsene — DISMISSED** [review]

**Comment by motomioya** [comment]
@iarsene Hello, Thank you for the comment. The beginning of the name of the data model file is capitalized.

**Review by iarsene — APPROVED** [review]

**Comment by motomioya** [comment]
Hello, @iarsene. The automatic checks for build/O2Physics/o2 and build/O2Physics/o2/macOS-arm failed in the previous commit. I've identified the issue and committed a fix after verifying that the build was successful in my local environment again. I'm sorry for bothering you many times.

**Comment by fcatalan92** [comment]
Hi @motomioya, I'm sorry to jump in after the PR has been approved (and moments before the merging).
I had a look at the code you wrote for the ML inference. You imported the general `model.h` class and used it to initialise the ML model, but then you retrieved the underling onnxruntime session and used it. 
I was wondering if this is really necessary or if you could use the `evalModel` method of `OnnxModel`, this would streamline your code and make it more robust vs further updates of the library. If you use case is not yet supported by `model.h`, it would be good having a look at how to include it (@ChSonnabend).

**Pull request merged**
