### PR TITLE
PWGMM: dndeta-hi.cxx update for hyperloop

### PR DESCRIPTION
**Pull request by hyungjun-lee**
Add dN/dEta distribution code for heavy-ion based on dndeta.cxx code 
If you have some asking for me, please contact.

### CODE REVIEW

**Comment by aalkin** [comment]
Please rename the PR to something more descriptive, as this is not an addition of a task but a modification of it. Other than that it seems fine.

**Review by aalkin — DISMISSED** [review]

**Comment by aalkin** [comment]
@hyungjun-lee PRs to any repository are done exactly in the same way - you just need to chose the different target. Instead of the main O2Physics repository you would use a certain branch in some user's fork of it that is found at `https://github.com/<username>/O2Physics` with appropriate user name.  The owner of the fork can accept and merge the PR and then create a new PR to the main repository, that will have both yours and user's commits in it. Or the other user can make PRs to your fork, this is completely symmetric.

**Comment by hyungjun-lee** [comment]
> @hyungjun-lee PRs to any repository are done exactly in the same way - you just need to chose the different target. Instead of the main O2Physics repository you would use a certain branch in some user's fork of it that is found at `https://github.com/<username>/O2Physics` with appropriate user name. The owner of the fork can accept and merge the PR and then create a new PR to the main repository, that will have both yours and user's commits in it. Or the other user can make PRs to your fork, this is completely symmetric.

I went to hyebin-P repository and clicked the "New pull request"
I saw that the notice about "able to merge : These branches can be automatically merged."
Is it merged? I'm sorry for not fully understand your explanation. 
and thanks your reply!

**Comment by aalkin** [comment]
"Able to merge" only indicates that there are no conflicts and the merge can be done without editing anything. If you have clicked "create pull request", now the owner of the repository needs to accept and merge it.

**Comment by hyungjun-lee** [comment]
> "Able to merge" only indicates that there are no conflicts and the merge can be done without editing anything. If you have clicked "create pull request", now the owner of the repository needs to accept and merge it.

aalkin, I think I cannot solve this problem easily. I uploaded this code a week ago, and I can delay my work more. 
It is not good solution but I asked for closing the other "dndeta-hi.cxx" PR to my group people. 
Can you tag it?

**Review by aalkin — APPROVED** [review]

**Pull request merged**
