### PR TITLE
PWGCF: Update lambdaR2Correlation.cxx

### PR DESCRIPTION
**Pull request by yashpatley**

### CODE REVIEW

**Comment by yashpatley** [comment]
Dear @victor-gonzalez , 

This is a temporary workaround for the current problem we face on hyperloop for not being able to create subwagons because we the previous task has derived data output. 

Please provide your valuable comments and suggestions so we can further modify this new version of the code. The part to update lambda list is still under construction. I will make a PR in future with that part modified. For the time being I want to run this one to get some results and comparison plots.

**Review by victor-gonzalez — APPROVED** [review]

**Review by victor-gonzalez — CHANGES_REQUESTED** [review]
Yash, I aproved it by mistake before

**Comment by victor-gonzalez** [comment]
The rule in O2 is to use the information that is stored in a really efficient way in the tables that are resident in memory and don't create new complex structures that mimic in some way that information. This structures have quite inefficient memory access and, of course, occupy memory 

I would not suggest to modify an already functional task because it cannot be run with subwagons
Subwagons are also limited resources

**Comment by yashpatley** [comment]
Hello Victor,

I understand what you are implying. I will change the task as before. Thank you.

**Review by victor-gonzalez — APPROVED** [review]

**Pull request merged**
