### PR TITLE
ppPhi trigger merged into CFFilterAll

### PR DESCRIPTION
**Pull request by echizzal**

### CODE REVIEW

**Comment by ariedel-cern** [comment]
Hi @echizzal ,
thanks a lot for the PR. The changes look good to me. The functionally of the other triggers should not be impacted by your changes.

**Review by lauraser — COMMENTED** [review]
Hi @echizzal @ariedel-cern , the code looks good for me. I also discussed with Emma the tests I asked for and these properly prove that the old triggers are not affected by the includion of p-p-phi as expected. Emma is finishing last test on phis and then I approve the code.

**Comment by echizzal** [comment]
@lauraser i just pushed the bug fix! thx for the help!

**Review by lauraser — APPROVED** [review]
@echizzal thanks Emma!

**Pull request merged**
