### PR TITLE
[PWGHF]: Fix search of mothers to work also at partonic level

### PR DESCRIPTION
**Pull request by fgrosa**
This PR fixes the search of the mother particles, in particular when needed at partonic level (i.e. non-prompt tagging for HF analyses). In the previous version, only the first element of the mothers vector was checked, however most of the times the beauty quark is not in the first element. This was the origin of the issue related to the non-prompt tagging found in [O2-2761](https://alice.its.cern.ch/jira/browse/O2-2761), now fixed with this PR.

### CODE REVIEW

**Comment by vkucera** [comment]
Thanks for the fix. Can you please add comments in the code to help understand how you use the new variables?

**Comment by fgrosa** [comment]
> Thanks for the fix. Can you please add comments in the code to help understand how you use the new variables?

Sure, I added them! Let me know if something is still unclear

**Review by vkucera — APPROVED** [review]

**Comment by vkucera** [comment]
@jgrosseo @iarsene It is fine with me to merge this.

**Comment by fgrosa** [comment]
> @jgrosseo @iarsene It is fine with me to merge this.

Thanks @vkucera! I noticed now that the test on MacOs became red, but the error is unrelated to this PR, can we merge it anyway? It would be good to have it merged because the current version on Run3 MC productions leads to a wrong result

**Review by jgrosseo — APPROVED** [review]

**Pull request merged**
