### PR TITLE
PWGHF: add THn axis for prompt BDT score in D0 task

### PR DESCRIPTION
**Pull request by Mingyu3360715**
Prompt BDT score axis added for studying the performance of selection based on prompt score

### CODE REVIEW

**Comment by mfaggin** [comment]
hi @Mingyu3360715 , for the D0 there is this PR here still in draft, but that should be merged quickly: https://github.com/AliceO2Group/O2Physics/pull/7805

Is I a problem for you to wait of it?

**Comment by Mingyu3360715** [comment]
> hi @Mingyu3360715 , for the D0 there is this PR here still in draft, but that should be merged quickly: #7805
> 
> Is I a problem for you to wait of it?

Hi @mfaggin Of course, no problem. But this modification of taskD0 will not affect the PR #7805, right?
Anyway, this PR can wait. No need to hurry

**Comment by mfaggin** [comment]
thanks @Mingyu3360715 yes in principle they should go smoothly, but ok since with the other PR we are basically done I'd just wait, since it's quite a massive development

**Comment by mfaggin** [comment]
sorry Mingyu..... you are right! I am not touching the taskD0 in the other PR, sorry!! 
Approved

**Review by mfaggin — APPROVED** [review]

**Pull request merged**
