### PR TITLE
Propagation of MClables to clusters added

### PR DESCRIPTION
**Pull request by peressounko**

### CODE REVIEW

**Comment by peressounko** [comment]
Dear @ktf , @mikesas  could you please have a look at this PR? Thanks, Dmitri

**Comment by ktf** [comment]
As far as I can tell, it looks good to me. Anything in particular for which you wanted my review explicitly?

**Comment by peressounko** [comment]
@ktf thanks, indeed there is nothing special here. I need your approval to merge into Common/DataModel/ dir.

**Review by ktf — APPROVED** [review]
New table, so nothing to object from the Framework side.

**Review by mikesas — APPROVED** [review]

**Pull request merged**
