### PR TITLE
[Common] Fix the bug -PR8901

### PR DESCRIPTION
**Pull request by miranov25**
Fixes https://github.com/AliceO2Group/O2Physics/pull/8901

### CODE REVIEW

**Comment by vkucera** [comment]
> @vkucera is this okay to merge? CI is currently broken otherwise
> 
> CC @ktf

Yes, I confirm this fixes the O2Physics compilation.

**Review by ddobrigk — APPROVED** [review]

**Comment by pzhristov** [comment]
I will merge it as soon as my local test is OK.

**Comment by ddobrigk** [comment]
disabling auto-merge - the fastest way to fix the problem is to revert the original PR and force-merge the revert immediately ...

**Comment by ddobrigk** [comment]
reversal here https://github.com/AliceO2Group/O2Physics/pull/8964

**Comment by pzhristov** [comment]
It compiles, so I merged it and the CI should be fine

**Pull request merged**
