### PR TITLE
[Event selection] add metadata

### PR DESCRIPTION
**Pull request by njacazio**
add possibility to use metadata in the event selection to pick between Run2 and Run3

### CODE REVIEW

**Comment by ekryshen** [comment]
Nicolo, thanks a lot! Indeed, this is a long-awaited feature! The changes are fine with me.

**Comment by njacazio** [comment]
Hi @ddobrigk I think we could merge this PR and https://github.com/AliceO2Group/O2Physics/pull/6677 if the metadata is now working on HL

**Comment by jgrosseo** [comment]
@njacazio I have enabled the metadata on Hyperloop starting from today's tag

**Review by jgrosseo — APPROVED** [review]

**Comment by jgrosseo** [comment]
Let's start with this one and when it works merge the other tomorrow...

**Pull request merged**
