### PR TITLE
Fixes to support version 1

### PR DESCRIPTION
**Pull request by jgrosseo**

### CODE REVIEW

**Comment by sawenzel** [comment]
Thanks. Then it would be good to go ahead. I'll take away the draft status to see if it compiles.

**Comment by benedikt-voelkel** [comment]
Mh, that is unexpected. I will check

**Comment by jgrosseo** [comment]
> Mh, that is unexpected. I will check

It is not. We need to wait for the daily O2 tag which @ktf triggered. That's why I left this as draft actually...

**Comment by benedikt-voelkel** [comment]
ah, right, sorry for my ignorance and thanks for the clarification

**Comment by jgrosseo** [comment]
The tag is there. I made a dummy commit, to run the CI again

**Pull request merged**
