### PR TITLE
PWGLF: Fix compilation warnings in rsnOutput.h

### PR DESCRIPTION
**Pull request by vbarbaso**

### CODE REVIEW

**Review by BongHwi — APPROVED** [review]

**Comment by BongHwi** [comment]
Thanks for the update! let's see if this clears the warning.

**Comment by BongHwi** [comment]
Great, now it's cleared. I'll merge it.

**Comment by vkucera** [comment]
This PR also reverts fixes made in https://github.com/AliceO2Group/O2Physics/pull/5654. Please add them back.

**Comment by vkucera** [comment]
@vbarbaso , please update your repository properly when you make a PR. I fixed this bug already two weeks ago in https://github.com/AliceO2Group/O2Physics/pull/5442 but then you put it back the next day in https://github.com/AliceO2Group/O2Physics/pull/5459.

**Comment by vbarbaso** [comment]
@vkucera  I'm really sorry about that. I did not notice. I've already reverted your changes in #5700. Hope everything is fine now. Please let me know if not.

**Comment by vkucera** [comment]
> @vkucera I'm really sorry about that. I did not notice. I've already reverted your changes in #5700. Hope everything is fine now. Please let me know if not.

@vbarbaso Thanks, it looks got to me.

**Pull request merged**
