### PR TITLE
Common: add multNGlobalTracks in multiplicity table

### PR DESCRIPTION
**Pull request by dsekihat**
Common: add multNGlobalTracks in multiplicity table

### CODE REVIEW

**Comment by ddobrigk** [comment]
Hi @dsekihat , from what I can see this adds a dependency on track selection in all process functions. Did I understand that correctly? That is probably not a good feature, since we avoided that dependency on purpose... we should try to compartmentalize this or we will have to even change a lot of dependencies in hyperloop. Can you please adapt? Thank youo!

**Comment by dsekihat** [comment]
Hi @ddobrigk , I agree. I don't like the extra dependency, either. Do you have any idea about how to compartmentalize them?

**Comment by dsekihat** [comment]
Hi @altsybee , Do you mind, if I modify your process function "processGlobalTrackingCounters"?

**Comment by ddobrigk** [comment]
> Hi @altsybee , Do you mind, if I modify your process function "processGlobalTrackingCounters"?

Hi @dsekihat , yes, this is what I would suggest and in fact this extra process function is exactly disabled by default to avoid creating that dependency. You could add your counters also to the table produced by that process function or so. Can you look into that? Thank you!

**Comment by dsekihat** [comment]
Dear @ddobrigk and @altsybee , Thank you for your suggestions. I modified "processGlobalTrackingCounters". Can you check it again? Thank you.

**Comment by altsybee** [comment]
> Hi @altsybee , Do you mind, if I modify your process function "processGlobalTrackingCounters"?

Hi @dsekihat , I think I never touched this file, and the processGlobalTrackingCounters is not "mine" ..  :)

**Comment by dsekihat** [comment]
Hi @altsybee , I see. Thank you for clarification. I thought it is yours, because I found a comment "counter from Igor".
Anyway, nGlobalTracks is not modified.

**Review by ddobrigk — APPROVED** [review]
thanks, this looks good and now it's nicely modular!

**Pull request merged**
