### PR TITLE
Symlinks to reproduce the directory structure

### PR DESCRIPTION
**Pull request by pzhristov**
This gives the possibility to use include files which internally refer to the original directory structure.

### CODE REVIEW

**Comment by pzhristov** [comment]
@adriansev This PR fixes some of the issues when we try to use O2Physics as external package in O2OpenAccess.

**Comment by adriansev** [comment]
@pzhristov wow, thanks a lot!! I will try it shortly and let you know the status. Thanks a lot!!

**Comment by pzhristov** [comment]
Can anybody of you ( @ktf @alibuild @jgrosseo @iarsene @ddobrigk @AliceO2Group/core ) approve this PR? Of course, I can merge it as administrator, but prefer to have your opinion.

**Comment by ddobrigk** [comment]
Thanks! This looks okay to me but I am not particularly good with CMake and such, so maybe it's better to have the attention of @iarsene @jgrosseo @ktf :-D

**Comment by jgrosseo** [comment]
Can we do some kind of test build with it? Or is there no risk associated?
I'd also like to have @ktf and/or @TimoWilken 's opinion :-)

**Comment by pzhristov** [comment]
It does not change the existing installation, just adds some links to mimic the original directory structure in O2Physics. A test build would be interesting just to make sure the links are indeed in include/ :)

**Comment by TimoWilken** [comment]
Hi @pzhristov, on Linux the links are not there, because the `ln` command fails with:

```
ln: invalid option -- 'h'
```

**Comment by pzhristov** [comment]
@TimoWilken Very good, thanks for checking. I will modify the link command.

**Pull request merged**
