### PR TITLE
Some CMake fixes/improvements

### PR DESCRIPTION
**Pull request by aphecetche**
@hristov @TimoWilken  A few fixes / improvements (hopefully) in some CMake files for your consideration : 

- the `o2physics_add_header_only_library` was creating libraries in the `O2::` namespace instead of `O2Physics::' one (which might explain the failed attempt by @adriansev #1324) 
- with the fix above DataModel can now be a proper (header-only) library
- the two added CMake find modules are not strictly necessary for a stack completely driven by aliBuild, but helps in case e.g. ONNXRuntime is installed by other means (and should not hurt 100% alibuild stacks)

### CODE REVIEW

**Comment by aphecetche** [comment]
obviously the `fjcontrib` change is less innocent that what I thought from my tests on my Mac and a dev FLP.
Investigating...

**Comment by adriansev** [comment]
@aphecetche Thanks a lot for looking at this!!
looking at cmake/O2PhysicsAddHeaderOnlyLibrary.cmake it seems to me that it requires to move all includes to a `include` sub-directory (but of course this will break other tasks)
Looking at O2 usage of o2_add_header_only_library seems that this is how it was used ..

**Comment by jgrosseo** [comment]
What is a o2physics_add_header_only_library?

We do not need the DataModel headers in a library. They are only includes for somewhere else.

**Comment by aphecetche** [comment]
@adriansev first, note that I've just force-pushed a new version of the `o2_add_header_only_library` (in case you've looked at the previous one), as the previous version failed at install stage.

As far as I can tell (but I'm no O2Physics expert) the location of the (installed) include is different from O2 (where a XXX target includes get installed under `INSTALLROOT/include/XXX/include`. For `O2Physics` the installed includes are in a single flat top directory. Looking e.g. on lxplus I get : 

```
[O2Physics/nightly-20220926-2] ~ > ls $O2PHYSICS_ROOT/include
AnalysisCompositeCut.h	    CorrelationContainer.h  EventSelectionParams.h  GFWCumulant.h	JetFinder.h  MixingHandler.h  ProfileSubset.h		TriggerAliases.h  multGlauberNBDFitter.h
AnalysisConfigurableCuts.h  DGCutparHolder.h	    FlowContainer.h	    GFWWeights.h	MCProng.h    OrbitRange.h     TrackSelection.h		VarManager.h	  multMCCalibrator.h
AnalysisCut.h		    DGPIDSelector.h	    GFW.h		    HistogramManager.h	MCSignal.h   ParamBase.h      TrackSelectionDefaults.h	multCalibrator.h  pidTPCML.h
```   

I believe my (latest) change in `o2_add_header_only_library` does that.

**Comment by aphecetche** [comment]
@jgrosseo the idea of the `o2physics_add_header_only_library` is to define a CMake target that only contains, as the name implies, only headers. In retrospect maybe the proper name would be `o2physics_add_header_only_target`, but I guess the name (and the code) was derived from the O2 version...  It allows to properly express in some `CMakeLists.txt` that some other libraries do depend on those includes, and to avoid the usage of the `include_directories` command in the top `CMakeLists.txt` which is not using the concept of targets at all and should be avoided.  

Whether we install or not those includes (for instance to allow usage from something depending on `O2Physics` is another story, and I must confess I've not checked whether or not that's working).

**Comment by jgrosseo** [comment]
> @jgrosseo the idea of the `o2physics_add_header_only_library` is to define a CMake target that only contains, as the name implies, only headers. In retrospect maybe the proper name would be `o2physics_add_header_only_target`, but I guess the name (and the code) was derived from the O2 version... It allows to properly express in some `CMakeLists.txt` that some other libraries do depend on those includes, and to avoid the usage of the `include_directories` command in the top `CMakeLists.txt` which is not using the concept of targets at all and should be avoided.
> 
> Whether we install or not those includes (for instance to allow usage from something depending on `O2Physics` is another story, and I must confess I've not checked whether or not that's working).

OK, thanks! So in a library is not created. Then this is good of course.

I also confirm that the header layout is flat in O2Physics. We also decided to install all headers but just those which are needed downstream.

**Comment by adriansev** [comment]
> @adriansev first, note that I've just force-pushed a new version of the `o2physics_add_header_only_library` (in case you've looked at the previous one), as the previous version failed at install stage.
> 
> As far as I can tell (but I'm no O2Physics expert) the location of the (installed) include is different from O2 (where a XXX target includes get installed under `INSTALLROOT/include/XXX/include`. For `O2Physics` the installed includes are in a single flat top directory. Looking e.g. on lxplus I get :
> 
> ```
> [O2Physics/nightly-20220926-2] ~ > ls $O2PHYSICS_ROOT/include
> AnalysisCompositeCut.h	    CorrelationContainer.h  EventSelectionParams.h  GFWCumulant.h	JetFinder.h  MixingHandler.h  ProfileSubset.h		TriggerAliases.h  multGlauberNBDFitter.h
> AnalysisConfigurableCuts.h  DGCutparHolder.h	    FlowContainer.h	    GFWWeights.h	MCProng.h    OrbitRange.h     TrackSelection.h		VarManager.h	  multMCCalibrator.h
> AnalysisCut.h		    DGPIDSelector.h	    GFW.h		    HistogramManager.h	MCSignal.h   ParamBase.h      TrackSelectionDefaults.h	multCalibrator.h  pidTPCML.h
> ```
> 
> I believe my (latest) change in `o2physics_add_header_only_library` does that.

@aphecetche Thanks a lot!! Yes, i did not see it, checking it out right away

**Comment by adriansev** [comment]
> > > > @jgrosseo the idea of the `o2physics_add_header_only_library` is to define a CMake target that only contains, as the name implies, only headers. In retrospect maybe the proper name would be `o2physics_add_header_only_target`, but I guess the name (and the code) was derived from the O2 version... It allows to properly express in some `CMakeLists.txt` that some other libraries do depend on those includes, and to avoid the usage of the `include_directories` command in the top `CMakeLists.txt` which is not using the concept of targets at all and should be avoided.
> > > > Whether we install or not those includes (for instance to allow usage from something depending on `O2Physics` is another story, and I must confess I've not checked whether or not that's working).
> > > 
> > > 
> > > OK, thanks! So in a library is not created. Then this is good of course.
> > > I also confirm that the header layout is flat in O2Physics. We also decided to install all headers but just those which are needed downstream.
> > 
> > 
> > @jgrosseo well, if one want/need O2Physics to be upstream dependency (for downstream software that dependends on O2Physics) then all (or by selection) includes are needed to be installed in $INSTALLDIR/include
> 
> Yes, selected ones should be installed. On request. We have also includes which are only used by some executable, they should not be exposed.

@jgrosseo ok, and as you can see in this PR, the target is first to be able to do it, then it's about the Common/DataModel includes which are of general usage in analyses .. are there any objections to this?

**Comment by TimoWilken** [comment]
Sorry, the Mac builder has a bit of a queue at the moment. It'll pick this PR up eventually.

**Comment by jgrosseo** [comment]
> Sorry, the Mac builder has a bit of a queue at the moment. It'll pick this PR up eventually.

Good. We should certainly wait for this

**Comment by aphecetche** [comment]
All green (including Mac builder), so ready to be reviewed (and/or merged :wink:)

**Comment by adriansev** [comment]
@jgrosseo @TimoWilken Could you review this please? Thanks a lot!!

**Comment by TimoWilken** [comment]
Looks like a good effort to me in general, thank you!

One thing though: it looks like the new explicit "FastJet::Contrib" dependency relies on aliBuild loading fastjet transitively for O2. This should probably be specified explicitly in alidist as well: https://github.com/alisw/alidist/pull/4612.

**Comment by adriansev** [comment]
gentle ping @TimoWilken IMHO if does not break anything it could be a situation of good enough (the intended jobs is done), and having a step forward where one can then improve further .. would it be ok to just merge it and then build upon this? Thanks a lot!!

**Comment by ktf** [comment]
This is fine with me, however the fact the analysis data model is header only is just an accident at the model. In principle it might happen in the future that a full fledged library will be needed.

**Pull request merged**
