### PR TITLE
Tutorials: a pair of example tasks where the configuration is inherited

### PR DESCRIPTION
**Pull request by aalkin**
A tutorial example of how a task can adjust its configuration based on the requirements of other tasks in the workflow.

@ddobrigk

### CODE REVIEW

**Comment by aalkin** [comment]
@TimoWilken I see that MegaLinter often has an error from `secretlint` check due to missing `branch_protection_rules.json`. Do we need the `secretlint` at all for O2Physics?

**Comment by TimoWilken** [comment]
Good point @aalkin, I've disabled it (you might have to rebase or push to this PR to make GitHub pick up the updated MegaLinter workflow).

Cc: @vkucera

**Comment by vkucera** [comment]
> Good point @aalkin, I've disabled it (you might have to rebase or push to this PR to make GitHub pick up the updated MegaLinter workflow).
> 
> Cc: @vkucera

Hi @TimoWilken , I cannot judge how serious the `secretlint` errors are, but please move the `DISABLE` line from the workflow file into the configuration file.

https://github.com/AliceO2Group/O2Physics/blob/master/.mega-linter.yml#L13

**Comment by TimoWilken** [comment]
> Hi @TimoWilken , I cannot judge how serious the `secretlint` errors are, but please move the `DISABLE` line from the workflow file into the configuration file.

Done, thanks for the hint Vit!

**Review by ddobrigk — APPROVED** [review]
Many many thanks!

**Pull request merged**
