### PR TITLE
Extend tasks for ALICE3

### PR DESCRIPTION
**Pull request by njacazio**

### CODE REVIEW

**Comment by njacazio** [comment]
Apologies for the long PR but I was waiting to have O2Physics online. This essentially changes tasks for ALICE3 and updates PID tasks so that now they don't clash with the Run3 MC AODs

**Review by jgrosseo — APPROVED** [review]
Congratulations to the first O2Physics physics PR :)

**Comment by njacazio** [comment]
I won ;)

**Comment by jgrosseo** [comment]
Just for the record @ktf @TimoWilken, this build took 32 minutes. It looks like a full rebuild probably triggered by the change in cmake files (or should a cmake file change in a sub directory only retrigger the build of that sub directory)?

**Pull request merged**
