### PR TITLE
Adding histograms

### PR DESCRIPTION
**Pull request by arossi81**

### CODE REVIEW

**Comment by arossi81** [comment]
Sorry, I forgot the formatting, updating it

**Review by mfaggin — APPROVED** [review]

**Comment by arossi81** [comment]
Dear all, could this be merged?
Cheers,
Andrea

**Comment by arossi81** [comment]
Hi @ktf, @ddobrigk , can you approve this pull request?
Cheers,
Andrea

**Review by ddobrigk — APPROVED** [review]

**Comment by ddobrigk** [comment]
> Hi @ktf, @ddobrigk , can you approve this pull request?
> Cheers,
> Andrea

Yes sure, sorry, didn't spot it! Don't hesitate to ping me if I miss something

**Comment by arossi81** [comment]
Hi David,
thanks! I still see it open. Maybe it has to be approved also by @njacazio since I modified (one line) of TrackSelectionDefaults?

**Comment by arossi81** [comment]
Hi @ktf ,
I have this pull request open since long, it is a minor change... can it be approved?

Cheers,
Andrea

**Review by iarsene — APPROVED** [review]

**Comment by arossi81** [comment]
Hi @njacazio ,
can you approve it (you're owner of 1 file)?
Cheers,
Andrea

**Review by njacazio — APPROVED** [review]

**Pull request merged**
