### PR TITLE
bug fix for TOF nsigma

### PR DESCRIPTION
**Pull request by noferini**
This mainly contains two fixes:
1) One condition was inverted when flagging tracks with TOF event time available

2) All tracks without a defined event time flagged (i.e. TOF) were discarded for Nsigma (because of bug 1 all tracks with TOF event time)

Here both fixes are provided (working with pp@13 TeV GP MC)

### CODE REVIEW

**Comment by noferini** [comment]
@njacazio , @giovannimalfattore
These are fixes required to do PID with TOF (urgent for trigger studies)

**Comment by noferini** [comment]
One more comment.
In principle the fix (1) should allow to recover the peak center to zero also in LHC22f for the majority of the tracks independently of miscalibrations

**Comment by noferini** [comment]
MagaLinter check failing for
[markdown-link-check] PWGCF/Tutorial/README.md
[markdown-link-check] PWGDQ/Macros/README.md
I don't know what is this check but log refers to something not related to this PR

**Comment by noferini** [comment]
Dear all,
can this PR be merged?

**Review by ddobrigk — APPROVED** [review]
Thank you!

**Pull request merged**
