### PR TITLE
PWGHF: Implement the possibility to apply proton PID for baryons in skimming

### PR DESCRIPTION
**Pull request by fgrosa**
This PR addresses the issue https://github.com/AliceO2Group/O2Physics/issues/3761 implementing the possibility to apply a PID selection for the proton in the Lc and Xic decays. Main features:
- not to force the dependency on the PID tasks, the process function is templatised (allowing also for the depency on TPC or TOF separately if only one of the two is needed)
- the tracks are tagged as protons or not only once in the struct for the track tagging
- a different selection for each channel can be set

In addition, in this PR I removed the `MY_DEBUG` option.

I tested that it works properly in all the cases (so it is ready for review), but before merging it I would like to compare in detail the outputs before and after this implementation and profile the performances (I will post here the results in the next days).

### CODE REVIEW

**Comment by vkucera** [comment]
Thanks @fgrosa , I would remove all the occurrences of `MY_DEBUG` (also in `candidateCreatorCascade.cxx`) together with `utilsDebugLcToK0sP.h`.

**Comment by mfaggin** [comment]
Hi @fgrosa , I looked at the code and it looks ok from my side. Feel free to approve it by yourself after yor tests.

**Comment by fgrosa** [comment]
> Hi @fgrosa , I looked at the code and it looks ok from my side. Feel free to approve it by yourself after yor tests.

Hi @mfaggin, after few fixes, I checked that the same result is obtained in case of no PID selection enabled. If the PID is enabled instead, only for the baryons (Lc->pKpi in my test) is obtained a difference as expected.

image

The same holds both in case of no PVrefit and PVrefit.

I then checked the CPU and memory performance with the previous version:

image
image
 
And the new version with no PID applied:

image
image

And no overhead is observed. 
In case of PID the only overhead is due to the dependencies on the TPC and/or TOF PID tasks.

**Comment by mfaggin** [comment]
Thanks Fabrizio, it looks good to me, thank you

**Review by mfaggin — APPROVED** [review]

**Pull request merged**
