### PR TITLE
PWGEM: added lmee-lf-cocktail task

### PR DESCRIPTION
**Pull request by DanielSamitz**
Added first version of the lmee-lf-cocktail task.
(corresponds to https://github.com/alisw/AliPhysics/blob/master/PWGDQ/dielectron/LMEE/AliAnalysisTaskLMeeCocktailMC.cxx in Run2)

### CODE REVIEW

**Comment by dsekihat** [comment]
Hi @DanielSamitz , Thank you for your nice works. Can you implement comments from Mega Linter?

**Comment by DanielSamitz** [comment]
I still get errors from MegaLinter, but they do not seem to be related to my task

**Review by ivorobye — APPROVED** [review]

**Comment by ivorobye** [comment]
hi @DanielSamitz , @dsekihat , approved this commit since the MegaLinter errors are from other tasks (and the checks are not actually obligatory for merging)

**Comment by ktf** [comment]
This was merged while breaking on macOS.

**Pull request merged**
