### PR TITLE
PWGCF/Flow: Fixed format errors

### PR DESCRIPTION
**Pull request by Preet-Bhanjan**
Fixed the specified format errors by alibuild.

### CODE REVIEW

**Comment by Preet-Bhanjan** [comment]
@victor-gonzalez Please approve my code

**Review by victor-gonzalez — APPROVED** [review]
There are quite an amount of code which is replicated. Replicating code is error prone and difficult to maintain and to evolve. I would suggest trying to minimize the amount of replicated code by making use of the template mechanism as much as possible

Also there are several invocations of `selectionPID` for checking the different species. 
If the execution time is excessive this is definitely a point of improvement

**Comment by Preet-Bhanjan** [comment]
@victor-gonzalez Please merge my code

**Comment by victor-gonzalez** [comment]
Any reason why the PR was closed?
If the PR is closed the whole history is lost if a new one is open with the same functional changes
If you keep moving forward with this functionality, please, re-open this PR and continue pushing your modifications. The PR will get automatically updated
I was going to merge it (I'm currently at the USA timezone and just waited until the compilation went through)

**Comment by Preet-Bhanjan** [comment]
@victor-gonzalez The PR was closed due to an oversight on my part. I have reopened the PR.

**Pull request merged**
