### PR TITLE
PWGUD: Analysis in photonuclear events

### PR DESCRIPTION
**Pull request by JosueMtzGar**
First code to start  a mean pT and angular correlation analysis in photonuclear events

### CODE REVIEW

**Review by aalkin — CHANGES_REQUESTED** [review]
Please rebase your branch on the current master, lumiStability.cxx already contains these changes.

**Review by aalkin — DISMISSED** [review]

**Comment by JosueMtzGar** [comment]
the conflicts were resolved

**Comment by aalkin** [comment]
I was accidentally assigned to review this, due to extra files affected. I cannot merge this, since @pbuehler is the one responsible for PWGUD.

**Comment by JosueMtzGar** [comment]
@pbuehler, could you review this PR please?

**Comment by abylinkin** [comment]
Hi Josue,

I see you requested review and then made 6 commits to the repository after this.
I would suggest that you first convert your project to draft, make all necessary commits and then request a review.
Each new commit (even clang-format or fixing Mega-linter errors) would require the new review from us.

Can you confirm that this iteration is final?

Thank you!

**Comment by JosueMtzGar** [comment]
Hi

Thanks for let me know that information, I did not know it. I will be careful the next times. 
And yes, that was my final iteration.

Thanks!

**Review by rolavick — APPROVED** [review]

**Comment by aortizve** [comment]
+1

**Comment by rolavick** [comment]
> +1

**Review by abylinkin — APPROVED** [review]

**Review by ddobrigk — APPROVED** [review]

**Review by aalkin — APPROVED** [review]

**Pull request merged**
