### PR TITLE
removing FDD options

### PR DESCRIPTION
**Pull request by aortizve**

### CODE REVIEW

**Comment by aortizve** [comment]
Hello @strogolo , I am trying to compile my multiplicity task, I implemented the corresponding changes in filterTables.h However, I get the following errors related with filterTables.h   /github/workspace/EventFiltering/filterTables.h:11:  #ifndef header guard has wrong style, please use: EVENTFILTERING_FILTERTABLES_H_  [build/header_guard] [5]
  /github/workspace/EventFiltering/filterTables.h:186:  #endif line should be "#endif  // EVENTFILTERING_FILTERTABLES_H_"  [build/header_guard] [5]
  /github/workspace/EventFiltering/filterTables.h:167:  Add #include <unordered_map> for unordered_map<>  [build/include_what_you_use] [4]
  /github/workspace/EventFiltering/filterTables.h:173:  Add #include <string> for string  [build/include_what_you_use] [4]
  /github/workspace/EventFiltering/filterTables.h:173:  Add #include <vector> for vector<>  [build/include_what_you_use] [4]
Could you please have a look ?

**Comment by strogolo** [comment]
Hi @aortizve,
before checking the error message, I see that the PR is broken at `MegaLinter` check.
Could you try to update your branch? Hopefully this should fix the issue with `MegaLinter`.

**Comment by vkucera** [comment]
Hi @aortizve , I noticed your question about the MegaLinter errors. They seem quite clear and easy to fix. Are you having some troubles fixing them?

**Review by mpuccio — APPROVED** [review]

**Comment by mpuccio** [comment]
@aortizve sorry for the very late review, if you enable the automerging it should get merged.

**Pull request closed without merging**
