### PR TITLE
[PID] use metadata

### PR DESCRIPTION
**Pull request by njacazio**

### CODE REVIEW

**Comment by ddobrigk** [comment]
@njacazio this is awesome :-D - did you check that all is fine also for the Run 2 path? I have to ask ;-)

**Comment by njacazio** [comment]
For run 2 it's ok

**Review by ddobrigk — APPROVED** [review]

**Comment by jgrosseo** [comment]
@njacazio @ddobrigk The meta data is disabled on Hyperloop at present!
There is a bug preventing its use.

Does this also work without metadata? Otherwise revert.

**Comment by njacazio** [comment]
Hi, 
Apologies I just read the comment. The pr should be safe for disabled metadata

**Pull request merged**
