### PR TITLE
PWGHF: Unify different partitions in Ds task

### PR DESCRIPTION
**Pull request by fchinu**
This PR fixes the filling of the number of contributors in the Ds task output. 
After an interesting chat with @aalkin, I was suggested to drop the usage of the `std::map` to indicate the partition to be used, as it increases both compilation and run time, and remove redundant multiple definitions of the partitions, as it is not needed to have different specialisations for the different `Join`s.

### CODE REVIEW

**Review by fgrosa — DISMISSED** [review]
Nice solution, thanks!

**Comment by aalkin** [comment]
@fchinu I took a closer look at the code, and what you are doing with selecting preslice is in fact redundant. Since you are always slicing on the MC collision index, there is no reason to have several instances of preslice, it is actually enough to have `PresliceUnsorted<CollisionsMc> colPerMcCollision = aod::mccollisionlabel::mcCollisionId;` or even `PresliceUnsorted<aod::McCollisionLabels> colPerMcCollision = aod::mccollisionlabel::mcCollisionId;` and it is usable for any join that contains it.

**Comment by fchinu** [comment]
Thanks a lot @aalkin for your time and suggestions! I have changed the code following your advice, it is now much cleaner!

**Review by mfaggin — APPROVED** [review]
all good for me, I approve it. @aalkin if you can confirm that it's ok for you as well I merge it. Thanks

**Comment by aalkin** [comment]
The code looks good, please go ahead and merge it.

**Pull request merged**
