### PR TITLE
[Common,PWGCF,PWGDQ,PWGHF,PWGLF,Trigger] DPL Analysis: more compatibility changes for the upcoming O2 update

### PR DESCRIPTION
**Pull request by aalkin**
This is (hopefully) the last compatibility change in O2Physics to unblock updating of O2.

Important notes:
* `aod-data-model-graph` is temporarily disabled, as it is impossible to make it compile with both versions of O2 - it uses a lot of internal functions. After O2 is update, I will move framework-specific back into O2, so that data model graph can use abstracted API instead of relying on internals
* CEPF task reverted to use `persistent_columns_t` temporarily, same as with the data model graph I will move it to dedicated API that hides the framework internals
* PWGCF/Femto3D: declaration of versioned tables using existing `_VERSIONED` macro
* PWGDQ: the table description together with the table will become the primary distinctive feature of the table declaration, it will define the set of columns. Therefore different tables should have different descriptions. Additionally, the declarations are repeated 3 times in different tasks, consider moving them to a single header. Please also note that changed description also means you need to change the configuration of aod-writer if you want to store these tables.
* PWGHF:  declaration of versioned tables using existing `_VERSIONED` macro
* PWGLF:  declaration of staged/versioned tables using existing `_VERSIONED` macro; `Spawns<>` requires a table type, and not an iterator alias, it was functional essentially by accident.

### CODE REVIEW

**Comment by njacazio** [comment]
Thanks a lot Anton

**Review by njacazio — APPROVED** [review]

**Review by vkucera — APPROVED** [review]

**Review by ddobrigk — APPROVED** [review]
Approving on behalf of common (small and uncontroversial)

**Comment by aalkin** [comment]
The approvals for trigger, DQ and CF are still required. 
@mpuccio, @iarsene, @saganatt could you please add your review?

**Review by victor-gonzalez — APPROVED** [review]
Thanks Anton!

**Review by mpuccio — APPROVED** [review]

**Comment by aalkin** [comment]
An approval for DQ is still required.
@iarsene @dsekihat @feisenhu @lucamicheletti93 could you please take a look?

**Review by iarsene — APPROVED** [review]

**Pull request merged**
