### PR TITLE
Full refactoring of O2Physics folder structure

### PR DESCRIPTION
**Pull request by jgrosseo**

### CODE REVIEW

**Review by vkucera — CHANGES_REQUESTED** [review]
I see that `trackUtilities.h` was renamed to `TrackUtilities.h` which is not in line with the [Coding guidelines](https://rawgit.com/AliceO2Group/CodingGuidelines/master/naming_formatting.html?showone=File_Names#File_Names):
> Program file names and utility file names, which do not define a class or a namespace, start with a lower case letter.
> ```c++
> myUtilities.h   // Utility functions/definitions
> testMyClass.cxx // Test program
> ```

**Comment by jgrosseo** [comment]
I actually thought it was a typo...

**Comment by vkucera** [comment]
> I actually thought it was a typo...

Now the diff shows that the renamed files were deleted. Could it be that you forgot `git add` them?

**Comment by jgrosseo** [comment]
The usual mess that `git add -A` is not picking up the same files as `git commit -a`...

Further reading: https://stevebennett.me/2012/02/24/10-things-i-hate-about-git/

**Comment by jgrosseo** [comment]
Apparently, it was green earlier. Merging.

**Pull request merged**
