### PR TITLE
Preparation for ML tutorial at O2AT3

### PR DESCRIPTION
**Pull request by fcatalan92**
@ddobrigk Please merge at your earliest convenience. Thanks!

### CODE REVIEW

**Review by ddobrigk — DISMISSED** [review]
Thanks

**Review by ddobrigk — DISMISSED** [review]
Thanks!!

**Comment by fcatalan92** [comment]
@ddobrigk Now I fixed everything, sorry for the inconvenience.

**Review by ddobrigk — APPROVED** [review]
No problem, thanks a lot for all the work!!

**Pull request merged**
