### PR TITLE
DPG: Update TOF skims

### PR DESCRIPTION
**Pull request by njacazio**

### CODE REVIEW

**Comment by njacazio** [comment]
@chiarazampolli with this we extend the features of the TOF skimmed data. We should also understand why @noferini is not triggered in this DPG PRs, in principle he's in the CODEOWNERS

**Comment by jgrosseo** [comment]
@noferini Did you get the invite?

**Comment by noferini** [comment]
Yes, but I missed it, sorry.

**Comment by noferini** [comment]
I accepted it now, but I see invitation was expired in this PR

**Comment by noferini** [comment]
But I see
You now have push access to the AliceO2Group/O2Physics repository.  
So I guess it worked

**Review by noferini — APPROVED** [review]

**Pull request merged**
