### PR TITLE
Adding the chargedKstar prduction task

### PR DESCRIPTION
**Pull request by navneetkumar231295**
I am trying to look for the charged kStar production. So, I am making the pull request.

### CODE REVIEW

**Comment by navneetkumar231295** [comment]
Dear, all 

This is a gentle reminder for the pull request.

Thanks, 
With Regards, 
Navneet Kumar

**Comment by BongHwi** [comment]
Hello @navneetkumar231295 ,

Thanks for the contribution. 
Currently, we already have two charged K star analysis task in the repository.
Are there any chances to implement it to the current analysis tasks?

**Comment by navneetkumar231295** [comment]
Dear Bong,

We want to check the spectra independently, so implementing it cannot affect the other analyses. Additionally, we are trying to obtain the spectra without using LFResonanceTables.h.

Thanks, 
With Regards,
Navneet Kumar

**Comment by navneetkumar231295** [comment]
Dear Bong, 

This is a gentle reminder for the pull request.

Thanks, 
With Regards,
Navneet Kumar

**Pull request closed without merging**
