### PR TITLE
Update tutorial with labelled string array

### PR DESCRIPTION
**Pull request by njacazio**

### CODE REVIEW

**Review by jgrosseo — APPROVED** [review]

**Comment by njacazio** [comment]
@jgrosseo the CI should be ok now!

**Review by jgrosseo — APPROVED** [review]

**Comment by jgrosseo** [comment]
@aalkin @njacazio We are implementing this in Hyperloop at present. We noticed that the json does not reproduce the default values properly.

See here from the json:
`                    "defaultValue": "{\"labels_rows\":[\"rS 1\",\"rS 2\",\"rS 3\"],\"labels_cols\":[\"cS 1\",\"cS 2\",\"cS 3\",\"cS 4\"],\"values\":[[],[],[]]}",
`

while from the code it should contain the content of
`const std::string defaultmS[3][4] = {{"One.One", "One.Two", "One.Three", "One.Four"}, {"Two.One", "Two.Two", "Two.Three", "Two.Four"}, {"Three.One", "Three.Two", "Three.Three", "Three.Four"}};
`

Is there a bug?

**Comment by aalkin** [comment]
@jgrosseo @njacazio 
Indeed, I apologize for not paying attention earlier, but the actual JSON export function (https://github.com/AliceO2Group/AliceO2/blob/093db2bb4fb77f0f35a3c76a3c1f5c8727453174/Framework/Core/include/Framework/VariantJSONHelpers.h#L343) does not have a branch for strings. Should be a trivial addition.

**Comment by njacazio** [comment]
@aalkin thanks! I added it in https://github.com/AliceO2Group/AliceO2/pull/12290

**Pull request merged**
