### PR TITLE
Adding 1d Pion Femtoscopy

### PR DESCRIPTION
**Pull request by deependra170598**

### CODE REVIEW

**Comment by lgraczykCern** [comment]
Hi @deependra170598 - can you contact me, @saganatt, and @zchochul on Mattermost so that we see where you are with your code for pion analysis first, before accepting the PR? As FemtoWorld is still in the development stage we need to talk to each other before adding new features, and since this is the first one, we need to discuss it.

**Comment by victor-gonzalez** [comment]
Please @deependra170598, put your PR in draft until you agree with the FemtoWorld people

**Comment by victor-gonzalez** [comment]
Converted to draft until you converge with Femto people
The PR will be kept active able to receive comments and new commits but it will not overload CI

**Comment by deependra170598** [comment]
I asked to make a new PR again.

**Pull request closed without merging**
