### PR TITLE
fix FT0 MC QA

### PR DESCRIPTION
**Pull request by AllaMaevskaya**

### CODE REVIEW

**Comment by AllaMaevskaya** [comment]
What is wrong here? Can it be merged?

**Comment by ktf** [comment]
Merging this, it needed a review by someone at top-level because apparently Common/Tasks is apparently not in the CODEOWNERS file. @pzhristov  @iarsene @jgrosseo is that intended?

**Comment by jgrosseo** [comment]
Yes, Common should be approved by @iarsene or me

**Comment by jgrosseo** [comment]
Sorry that we both overlooked it

**Comment by iarsene** [comment]
Sorry for the delay. Please ping me over mattermost if i don't react to the PR.

**Pull request merged**
