### PR TITLE
implementation of TuneOnData for MC in TPC PID

### PR DESCRIPTION
**Pull request by jezwilkinson**
Original pull request for TuneOnData https://github.com/AliceO2Group/O2Physics/pull/4733 had diverged due to large conflicting changes made in https://github.com/AliceO2Group/O2Physics/pull/5563. This commit resolves the conflicts and re-implements the tuneondata option based on the new NN configurables (beta-gamma cutoff and per-species "useNetwork" flags).

### CODE REVIEW

**Comment by jezwilkinson** [comment]
(for information: @wiechula @njacazio )

**Comment by njacazio** [comment]
Hi, this looks good, shall we release it and enable a test wagon so that analysers can test it?

**Comment by wiechula** [comment]
Fine from my side. But I would not enable it by default.

**Comment by njacazio** [comment]
> Fine from my side. But I would not enable it by default.

I fully agree

**Comment by njacazio** [comment]
Hi @jezwilkinson what do you think? Can we go ahead?

**Comment by jezwilkinson** [comment]
Hi @njacazio ,
Sorry, I was away on a group event and completely offline the last couple of days.
Sounds great to me! 
> "I would not enable it by default."
Indeed the process switch is defaulted to false (not least because the TuneOnData process loop requires subscription to MC info and so wouldn't work on real data). We can announce in the mattermost how to use it

**Review by ddobrigk — APPROVED** [review]
thanks a lot!

**Comment by njacazio** [comment]
Hi, I propose that we add a debug wagon with the tune on data enabled. I will do this tomorrow with the new tag and test it

**Comment by jgrosseo** [comment]
@jezwilkinson @ddobrigk This PR introduced a problem: Now TPC full and TPC tiny produce both the same table which means on Hyperloop wagons which require full and wagons which require tiny cannot be combined into a train anymore. It should be removed from one of the two, and if that is not good, be moved to a separate executable...
image

**Comment by njacazio** [comment]
Indeed https://github.com/AliceO2Group/O2Physics/pull/5946

**Pull request merged**
