### PR TITLE
Add compile_commands.json and build directory to gitignore

### PR DESCRIPTION
**Pull request by mfasDa**

### CODE REVIEW

**Comment by mfasDa** [comment]
Two more dynamic entries that should be ignored by git by default

**Comment by ktf** [comment]
What is `build`?

**Comment by mfasDa** [comment]
Suddenly appearing in my source location after build:
```
build
build/CMakeCache.txt
build/Testing
build/Testing/Temporary
build/Testing/Temporary/CTestCostData.txt
build/Testing/Temporary/LastTest.log
build/CMakeFiles
build/CMakeFiles/cmake.check_cache
```

**Comment by ktf** [comment]
Are you using vscode?

**Comment by mfasDa** [comment]
> Are you using vscode?

Yes

**Pull request merged**
