### PR TITLE
Add customizable track selection

### PR DESCRIPTION
**Pull request by njacazio**

### CODE REVIEW

**Comment by jgrosseo** [comment]
On Hyperloop as soon as someone customizes the track selection, we cannot join wagons of different people anymore... I wonder if we having a wrong strategy...

**Comment by njacazio** [comment]
Would you have a set of different pT and Eta selection then? So that one can filter on those afterwards?

**Comment by njacazio** [comment]
A solution would also be to remove the acceptance range from these cuts and leave it to the analyzers

**Comment by jgrosseo** [comment]
Yes, I think this is better. And in that case analyzers have to put the pT and eta cut themselves.

**Review by iarsene — APPROVED** [review]

**Pull request merged**
