### PR TITLE
Set a new flag to mark if use analysis track cuts

### PR DESCRIPTION
**Pull request by ChunzhengLab**
Set a new configurable `b_useAnalysisTrackSelections`  to mark if use analysis track cuts.
When set to true, TrackSelection `cutObject` will be replaced by `getGlobalTrackSelectionRun3ITSMatch` calling from `TrackSelectionDefaults`

### CODE REVIEW

**Comment by vkucera** [comment]
@ChunzhengLab please remove the `b_` prefix. It is not allowed by the naming conventions.

**Comment by mfaggin** [comment]
thanks a lot @ChunzhengLab , as we discussed I'd change the conditions in lines 1254, 1274, 1290 to

`if (!b_useTrackSelections && !b_useAnalysisTrackSelections)`

otherwise the application of track selections is neglected in cases where `!b_useTrackSelections && b_useAnalysisTrackSelections`

**Comment by mfaggin** [comment]
and of course fix the formatting issues, otherwise we cannot merge the PR

**Comment by ChunzhengLab** [comment]
Thanks for the comments. I made the corresponding modifications and pushed it.

**Review by mfaggin — APPROVED** [review]

**Pull request merged**
