### PR TITLE
[Common] Uniform tracks extra converter to the coding conventions

### PR DESCRIPTION
**Pull request by fmazzasc**
@vkucera

### CODE REVIEW

**Review by vkucera — CHANGES_REQUESTED** [review]
Thanks @fmazzasc , please also fix the capitalisation of task (`struct`) names and add the Doxygen documentation.

**Comment by fmazzasc** [comment]
@vkucera , is it fine now?

**Review by vkucera — APPROVED** [review]

**Comment by vkucera** [comment]
> @vkucera , is it fine now?

Yes, perfect! Thanks a lot!

**Comment by fmazzasc** [comment]
C.I. is apparently failing for unrelated issues? Could we merge this p.r. anyway?

**Review by ddobrigk — APPROVED** [review]

**Comment by ddobrigk** [comment]
> C.I. is apparently failing for unrelated issues. Could we merge this p.r. anyway?

Thanks!! Done! @fmazzasc I will try and keep an eye on the change to `001` and once that's merged then I can take care of creating the core service on hyperloop for the converter.

**Pull request merged**
