### PR TITLE
Cleaner logic for nSigma selection

### PR DESCRIPTION
**Pull request by fmazzasc**
@lbariogl

### CODE REVIEW

**Review by lbariogl — APPROVED** [review]

**Comment by njacazio** [comment]
Great work. @fmazzasc could you please move this in the table producer in the next pr? Thanks and have a nice weekend

**Comment by mpuccio** [comment]
Ciao @njacazio, why? This produces a table to be stored as an output, not a table to be consumed by other tasks

**Comment by njacazio** [comment]
Ciao @mpuccio in principle there is no difference between the two cases

**Comment by njacazio** [comment]
Actually, you have a good point here, we might consider moving the table definition to the datamodel

**Pull request merged**
