### PR TITLE
PWGHF: Add χc from photon conversion

### PR DESCRIPTION
**Pull request by amaringarcia**

### CODE REVIEW

**Comment by vkucera** [comment]
Hi @amaringarcia , are there any news on this PR?

**Comment by amaringarcia** [comment]
Hi @vkucera , to my knowledge I have consider all the comments  , as well as fixed all compilation issues.
Let me know how to proceed.

Ana

**Comment by fcolamar** [comment]
Hello Ana, a general comment on the taskChicPCM.cxx structure (but holds also for the candidate creator).
If you use the doMC option approach to switch on/off the tasks to be run, it won't be possible to deactivate the MC task when running on Hyperloop - because such global options cannot be set in Hyperloop, and the defaults value 'true' will be considered.
So if you plan to run on Hyperloop and to switch off the MC tasks at some point (but I'd say the following approach is also suggested in general), you should modify the structure by moving to a single task with two processes, activated/deactivated via a PROCESS_SWITCH (that can be set as a standard configurable), look e.g. at #230 or #231. Let me know if you plan to do this modification.

**Comment by amaringarcia** [comment]
Dear @fcolamar , I can do the proposed change, but I would like to hear first from @ginnocen , @alessandrodefalco, or antonio.uras@cern.ch what are the plans on merging this taskChicPCM task and the taskChic task.
Regards,
Ana

**Comment by fcolamar** [comment]
Hi @amaringarcia, sure, let's wait for a feedback from them then

**Comment by vkucera** [comment]
> Dear @fcolamar , I can do the proposed change, but I would like to hear first from @ginnocen , @alessandrodefalco, or [antonio.uras@cern.ch](mailto:antonio.uras@cern.ch) what are the plans on merging this taskChicPCM task and the taskChic task. Regards, Ana

Hi @amaringarcia , can you please clarify what kind of feedback you are waiting for? Can you not just extend the existing code by @alessandrodefalco?

**Comment by vkucera** [comment]
Hi @amaringarcia , I don't think this code even compiles, as many things have changes since January. Plus, I see several obsolete structures in the code, like `doMC` or the selector that should be updated. Please make sure to push a working version before reopening the PR.

**Pull request closed without merging**
